discourse/discourse-ai

app/models/reviewable_ai_chat_message.rb, lib/modules/toxicity/jobs/regular/toxicity_classify_chat_message.rb, lib/modules/toxicity/toxicity_classification.rb, lib/shared/classificator.rb, spec/lib/modules/toxicity/entry_point_spec.rb, spec/models/reviewable_ai_chat_message_spec.rb
This should be merged right after https://github.com/discourse/discourse/pull/20690
=> DEV: applies chat namespacing

app/controllers/discourse_ai/ai_helper/assistant_controller.rb, app/models/completion_prompt.rb, app/models/model_accuracy.rb, app/models/reviewable_ai_chat_message.rb, app/models/reviewable_ai_post.rb, assets/javascripts/discourse/components/ai-helper.js, config/locales/client.en.yml, config/locales/server.en.yml, config/routes.rb, db/fixtures/ai-helper/600_completion_prompts.rb, db/migrate/20230316160714_create_completion_prompt_table.rb, lib/modules/ai_helper/entry_point.rb, lib/modules/ai_helper/open_ai_prompt.rb, spec/lib/modules/ai_helper/open_ai_prompt_spec.rb, spec/requests/ai_helper/assistant_controller_spec.rb, spec/support/openai_completions_inference_stubs.rb
This change makes it easier to add new prompts to our AI helper. We don't have a UI for it yet. You'll have to do it through a console.
=> REFACTOR: Store prompts in a dedicated table.

app/models/completion_prompt.rb, config/locales/server.en.yml, db/fixtures/ai-helper/600_completion_prompts.rb, db/migrate/20230320185619_multi_message_completion_prompts.rb, db/post_migrate/20230320191928_drop_completion_prompt_value.rb, lib/modules/ai_helper/open_ai_prompt.rb, lib/shared/inference/openai_completions.rb, spec/models/completion_prompt_spec.rb, spec/support/openai_completions_inference_stubs.rb
A prompt with multiple messages leads to better results, as the AI can learn for given examples. Alongside this change, we provide a better default proofreading prompt.
=> FEATURE: Prompts can consist of multiple messages.

app/controllers/discourse_ai/embeddings/embeddings_controller.rb, assets/javascripts/initializers/semantic-full-page-search.js, config/locales/server.en.yml, config/settings.yml
Depends on discourse/discourse#20939.
=> FIX: Don't try to use pg headlines for semantic search.

lib/shared/inference/openai_completions.rb, spec/shared/inference/openai_completions_spec.rb, spec/support/openai_completions_inference_stubs.rb
Also adds some tests around completions and supports additional params
such as top_p, temperature and max_tokens
This also migrates off Faraday to using Net::HTTP directly
=> FEATURE: add internal support for streaming mode

app/models/ai_api_audit_log.rb, db/migrate/20230424055354_create_ai_api_audit_logs.rb, lib/shared/inference/openai_completions.rb, spec/shared/inference/openai_completions_spec.rb
Still need to build a job to purge logs
=> FEATURE: add a table to audit OpenAI usage

lib/tasks/modules/embeddings/database.rake
- Creates embeddings in topic ID order, so it's easier to stop and
restart from where we stopped
- Update index parameters with current best practices
=> Updates to embedding rake tasks

config/settings.yml, plugin.rb
Also... ensures that plugin has a link to more info and proper description
=> FEATURE: hide various api keys in site settings

assets/javascripts/discourse/components/ai-bot-header-icon.hbs, assets/javascripts/discourse/components/ai-bot-header-icon.js, config/locales/client.en.yml, config/settings.yml
- Humanize model names
- Focus composer editor when starting a PM with a bot
- Correctly close the models dropdown when clicking outside
=> UX: Improvements to the AI Bot header shortcut

config/locales/server.en.yml, lib/modules/ai_bot/anthropic_bot.rb, lib/modules/ai_bot/bot.rb, lib/modules/ai_bot/commands/categories_command.rb, lib/modules/ai_bot/commands/command.rb, lib/modules/ai_bot/commands/google_command.rb, lib/modules/ai_bot/commands/search_command.rb, lib/modules/ai_bot/commands/summarize_command.rb, lib/modules/ai_bot/commands/tags_command.rb, lib/modules/ai_bot/open_ai_bot.rb, spec/lib/modules/ai_bot/bot_spec.rb, spec/lib/modules/ai_bot/commands/command_spec.rb, spec/lib/modules/ai_bot/commands/google_command_spec.rb, spec/lib/modules/ai_bot/commands/search_command_spec.rb, spec/lib/modules/ai_bot/commands/summarize_command_spec.rb
- FEATURE: introduce a more efficient formatter
- Slight improvement to summarizer Stop blowing up context with custom prompts
- ensure we include the guiding message
=> iterate commands

lib/modules/ai_bot/commands/search_command.rb
- We only support searching public topics - make it clear
- Stop using bug/feature, cause is poisons system - these may not exist
- Add after: and before: which are very handy for bounding search results
=> FEATURE: improve search prompt

db/fixtures/ai_bot/602_bot_users.rb, lib/modules/ai_bot/anthropic_bot.rb, lib/modules/ai_bot/bot.rb, lib/modules/ai_bot/commands/categories_command.rb, lib/modules/ai_bot/commands/command.rb, lib/modules/ai_bot/commands/google_command.rb, lib/modules/ai_bot/commands/image_command.rb, lib/modules/ai_bot/commands/search_command.rb, lib/modules/ai_bot/commands/summarize_command.rb, lib/modules/ai_bot/commands/tags_command.rb, lib/modules/ai_bot/commands/time_command.rb, lib/modules/ai_bot/open_ai_bot.rb, lib/shared/inference/openai_completions.rb, spec/lib/modules/ai_bot/anthropic_bot_spec.rb, spec/lib/modules/ai_bot/bot_spec.rb, spec/lib/modules/ai_bot/commands/categories_command_spec.rb, spec/lib/modules/ai_bot/commands/command_spec.rb, spec/lib/modules/ai_bot/commands/google_command_spec.rb, spec/lib/modules/ai_bot/commands/search_command_spec.rb, spec/lib/modules/ai_bot/commands/tags_command_spec.rb, spec/lib/modules/ai_bot/jobs/regular/create_ai_reply_spec.rb, spec/lib/modules/ai_bot/open_ai_bot_spec.rb, spec/shared/inference/openai_completions_spec.rb
Given latest GPT 3.5 16k which is both better steered and supports functions
we can now support rich bot integration.
Clunky system message based steering is removed and instead we use the
function framework provided by Open AI
Tests still need fixing and system needs a bit more debugging, but early
results are very promising!
=> FEATURE: add full bot support for GPT 3.5

lib/modules/embeddings/strategies/truncation.rb, lib/tasks/modules/embeddings/database.rake
- Fix embeddings rake task for new db structure
- PERF: .find_each instead of .find to save us from memory allocation peaks
=> embeddings fixes

config/locales/client.en.yml, config/settings.yml, lib/modules/ai_bot/anthropic_bot.rb, lib/modules/ai_bot/entry_point.rb, lib/modules/summarization/entry_point.rb, lib/shared/inference/anthropic_completions.rb, spec/lib/modules/ai_bot/anthropic_bot_spec.rb, spec/lib/modules/ai_bot/entry_point_spec.rb, spec/lib/modules/ai_bot/jobs/regular/create_ai_reply_spec.rb, spec/lib/modules/summarization/models/anthropic_spec.rb, spec/shared/inference/anthropic_completions_spec.rb, spec/support/anthropic_completion_stubs.rb
Claude 1 costs the same and is less good than Claude 2. Make use of Claude
2 in all spots ...
This also fixes streaming so it uses the far more efficient streaming protocol.
=> FEATURE: port to use claude-2 for chat bot

assets/javascripts/discourse/connectors/topic-above-suggested/related-topics.hbs, assets/javascripts/discourse/connectors/topic-more-content/related-topics.hbs, assets/javascripts/discourse/connectors/topic-more-content/related-topics.js, config/locales/client.en.yml, lib/modules/embeddings/entry_point.rb
Requires discourse/discourse#22880
=> UX: Update related-topics to follow <MoreTopics/> conventions

lib/modules/ai_bot/bot.rb, lib/modules/ai_bot/open_ai_bot.rb
Previously we were not counting functions correctly and not
accounting for minimum token count per message
This corrects both issues and improves documentation internally
=> FIX: improve token counting

lib/modules/ai_bot/anthropic_bot.rb, lib/modules/ai_bot/bot.rb, lib/modules/ai_bot/commands/image_command.rb, lib/modules/ai_bot/commands/search_command.rb, lib/modules/ai_bot/open_ai_bot.rb, lib/shared/inference/function.rb, lib/shared/inference/function_list.rb, lib/shared/inference/openai_completions.rb, plugin.rb, spec/lib/modules/ai_bot/anthropic_bot_spec.rb, spec/shared/inference/function_list_spec.rb, spec/shared/inference/openai_completions_spec.rb
Open AI support function calling, this has a very specific shape
that other LLMs have not quite adopted.
This simulates a command framework using system prompts on LLMs
that are not open AI.
Features include:
- Smart system prompt to steer the LLM
- Parameter validation (we ensure all the params are specified correctly)
This is being tested on Anthropic at the moment and intial results
are promising.
=> FEATURE: implement command framework for non Open AI

config/locales/server.en.yml, config/settings.yml, lib/modules/ai_bot/entry_point.rb, lib/modules/ai_bot/personas/persona.rb, lib/modules/ai_bot/personas/researcher.rb, spec/lib/modules/ai_bot/personas/persona_spec.rb, spec/lib/modules/ai_bot/personas/researcher_spec.rb
The researcher persona has access to Google and can perform
various internet research tasks. At the moment it can not read
web pages, but that is under consideration
=> FEATURE: add researcher persona

lib/modules/ai_bot/commands/search_command.rb, lib/tasks/modules/embeddings/database.rake, spec/lib/modules/ai_bot/commands/search_command_spec.rb
- FEATURE: add semantic search to bot
- FIX: embedding backfill rake task not working
=> FEATURE: add semantic search with hyde bot

lib/modules/embeddings/semantic_search.rb
This affects both full page search and AIBot who use this method
=> FEATURE: Respect search filters in semantic search

lib/modules/ai_bot/commands/command.rb, lib/modules/ai_bot/commands/search_command.rb, spec/lib/modules/ai_bot/commands/search_command_spec.rb
Previously we would bypass semantic search if any filters were
present
Also shows progress now.
=> FEATURE: add filter support to ai bot semantic search

config/locales/client.en.yml, config/locales/server.en.yml, lib/discourse_automation/llm_triage.rb, plugin.rb, spec/lib/discourse_automation/llm_triage_spec.rb
=> FEATURE: automation rule for triaging posts using LLM

lib/modules/ai_bot/commands/command.rb, lib/modules/ai_bot/commands/image_command.rb, lib/modules/ai_bot/personas/artist.rb, lib/shared/inference/function.rb, lib/shared/inference/stability_generator.rb, spec/lib/modules/ai_bot/commands/image_command_spec.rb
This allows for 2 big features:
1. Artist can ship up to 4 prompts for image generation
2. Artist can regenerate images cause it is aware of seed
This allows for iteration on images maintaining visual style
=> FEATURE: Make artist more creative

lib/shared/inference/amazon_bedrock_inference.rb
AWS updated their endpoints per https://docs.aws.amazon.com/general/latest/gr/bedrock.html
=> FIX: Update bedrock endpoint

assets/stylesheets/modules/ai-helper/common/ai-helper.scss
Followup to [e2d9117](https://github.com/discourse/discourse/commit/e2d9117378ead0dbfcc6533d7cf6a7bf8a14d033)
=> UX: update border on AI topic helpers

app/models/ai_api_audit_log.rb, db/migrate/20231031050538_add_topic_id_post_id_to_ai_audit_log.rb, lib/modules/ai_bot/anthropic_bot.rb, lib/modules/ai_bot/bot.rb, lib/modules/ai_bot/open_ai_bot.rb, lib/shared/inference/anthropic_completions.rb, lib/shared/inference/openai_completions.rb, spec/lib/modules/ai_bot/bot_spec.rb
This makes it easier to track who is responsible for a completion
in logs
Note: ai helper and summarization are not yet implemented
=> FEATURE: support topic_id and post_id logging in ai audit log

plugin.rb
This was not a complete sentence before
=> DEV: Fix plugin.rb wording

spec/system/page_objects/modals/diff_modal.rb
https://github.com/discourse/discourse/pull/23967
=> DEV: Update tests for core change

lib/completions/endpoints/aws_bedrock.rb, spec/lib/completions/endpoints/aws_bedrock_spec.rb
Reverts discourse/discourse-ai#308
=> Revert "FIX: We don't need to prepend anthropic. to bedrock models"

lib/completions/endpoints/aws_bedrock.rb, lib/modules/embeddings/semantic_search.rb, lib/modules/summarization/strategies/fold_content.rb
Other changes:
- Don't use Bedrock for non claude models if credentials are set.
- Remove extra sentence from HyDE prompt.
=> FIX: Make summaries more cohesive by tweaking prompt.

assets/javascripts/discourse/connectors/composer-fields/persona-selector.gjs, assets/stylesheets/modules/ai-bot/common/bot-replies.scss
=> FIX: allow selection of persona when list gets too long

app/models/completion_prompt.rb
=> FIX: Missing closing `>` in input tag

assets/javascripts/discourse/connectors/post-text-buttons/ai-helper-options-menu.gjs, assets/stylesheets/modules/ai-helper/common/ai-helper.scss
=> UX: Improve focus state of post options item by making full width

app/controllers/discourse_ai/ai_helper/assistant_controller.rb, app/models/completion_prompt.rb, assets/javascripts/discourse/components/modal/thumbnail-suggestions.gjs, assets/javascripts/discourse/components/thumbnail-suggestion-item.gjs, assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.hbs, assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js, assets/stylesheets/modules/ai-helper/common/ai-helper.scss, config/locales/client.en.yml, config/locales/server.en.yml, config/routes.rb, db/fixtures/ai_helper/603_completion_prompts.rb, lib/ai_helper/assistant.rb, lib/ai_helper/painter.rb, spec/lib/modules/ai_helper/painter_spec.rb, spec/requests/ai_helper/assistant_controller_spec.rb
This PR adds the ability to add AI generated images to posts based on selection.
https://github.com/discourse/discourse-ai/assets/30090424/c91318bf-6807-4d77-a119-2b3aff9563aa
=> FEATURE: Generate post illustrations

app/views/list/related_topics.html.erb, lib/embeddings/entry_point.rb, lib/embeddings/semantic_related.rb
Depends on https://github.com/discourse/discourse/pull/25060
Looks like
=> FEATURE: Render Related Topics for Crawlers

lib/completions/dialects/chat_gpt.rb, lib/completions/dialects/claude.rb, lib/completions/dialects/gemini.rb, lib/completions/dialects/llama2_classic.rb, lib/completions/dialects/mixtral.rb, lib/completions/dialects/orca_style.rb, lib/completions/endpoints/aws_bedrock.rb, lib/completions/endpoints/base.rb, lib/completions/endpoints/gemini.rb, lib/completions/endpoints/open_ai.rb, spec/lib/completions/dialects/chat_gpt_spec.rb, spec/lib/completions/endpoints/anthropic_spec.rb, spec/lib/completions/endpoints/aws_bedrock_spec.rb, spec/lib/completions/endpoints/endpoint_examples.rb, spec/lib/completions/endpoints/gemini_spec.rb, spec/lib/completions/endpoints/hugging_face_spec.rb, spec/lib/completions/endpoints/open_ai_spec.rb, spec/lib/completions/endpoints/vllm_spec.rb
I tested against the live models for the AI bot migration. It ensures Open AI's tool syntax is correct and we can correctly read the replies. :
=> FIX: Correctly translate and read tools for Claude and Chat GPT.

lib/ai_bot/personas/persona.rb, lib/ai_bot/site_settings_extension.rb, lib/ai_bot/tools/dall_e.rb, spec/lib/modules/ai_bot/personas/persona_spec.rb
- FIX: array arguments not parsed correctly
- Side quest ... don't use update! it calls validations and will now fail due to email validation
=> FIX: array arguments not parsed correctly

lib/completions/dialects/claude.rb, lib/completions/dialects/dialect.rb, lib/completions/dialects/gemini.rb, spec/lib/completions/dialects/claude_spec.rb, spec/lib/completions/dialects/gemini_spec.rb, spec/lib/completions/dialects/llama2_classic_spec.rb, spec/lib/completions/dialects/mixtral_spec.rb, spec/lib/completions/dialects/orca_style_spec.rb
- Provide more information to Gemini context post function execution
- Use system prompts for Claude (fixes Dall E)
- Ensure Assistant is properly separated
- Teach Claude to return arrays in JSON vs XML
Also refactors tests so we do not copy tool preamble everywhere
=> FIX: improve bot behavior

assets/javascripts/initializers/ai-bot-replies.js, assets/stylesheets/modules/ai-bot/common/bot-replies.scss, config/locales/server.en.yml, lib/ai_bot/bot.rb, lib/ai_bot/playground.rb, lib/ai_bot/tools/dall_e.rb, lib/ai_bot/tools/image.rb, spec/lib/modules/ai_bot/bot_spec.rb, spec/lib/modules/ai_bot/playground_spec.rb
Previous to this change it was very hard to tell if completion was
stuck or not.
This introduces a "dot" that follows the completion and starts
flashing after 5 seconds.
https://github.com/discourse/discourse-ai/assets/5213/8846ed96-0280-4f53-aca1-3c9f8281bcb8
=> FEATURE: more elegant progress

assets/javascripts/discourse/lib/ai-bot-streamer.js, assets/javascripts/discourse/lib/ai-streamer.js, assets/javascripts/initializers/ai-bot-replies.js, assets/stylesheets/modules/ai-bot/common/bot-replies.scss, lib/ai_bot/bot.rb, lib/ai_bot/entry_point.rb, lib/ai_bot/site_settings_extension.rb, lib/completions/dialects/claude.rb, lib/completions/dialects/dialect.rb, lib/completions/dialects/fake.rb, lib/completions/endpoints/base.rb, lib/completions/endpoints/fake.rb, spec/lib/completions/dialects/claude_spec.rb, spec/lib/completions/llm_spec.rb, test/javascripts/unit/lib/ai-streamer-test.js
Introduces a new mechanism for streaming content from the server in a "smooth" way on the client.
We hold a local buffer and only add a limited amount of text to the screen every PROGRESS_INTERVAL
https://github.com/discourse/discourse-ai/assets/5213/f40e41cc-a1d9-4084-8ac6-59ecac4ad4ce
Also introduces a "fake" llm dialect and endpoint which can make it much easier to test
=> FEATURE: smooth streaming of AI responses on the client

lib/completions/dialects/chat_gpt.rb, lib/completions/endpoints/open_ai.rb, lib/summarization/entry_point.rb
The new model has better performance and is always preferable to
the old one which has unicode issues during function calls.
=> FEATURE: support gpt-4-0125 which was just released

config/settings.yml, db/migrate/20240126013358_create_openai_text_embedding_tables.rb, lib/ai_bot/entry_point.rb, lib/embeddings/semantic_related.rb, lib/embeddings/vector_representations/base.rb, lib/embeddings/vector_representations/text_embedding_3_large.rb, lib/embeddings/vector_representations/text_embedding_3_small.rb, lib/embeddings/vector_representations/text_embedding_ada_002.rb, lib/inference/open_ai_embeddings.rb, spec/shared/inference/openai_embeddings_spec.rb
This adds support for just released text_embedding_3_small and large
Note, we have not yet implemented truncation support which is a
new API feature. (triggered using dimensions)
=> FEATURE: add support for new OpenAI embedding models

config/locales/client.en.yml, discourse_automation/llm_report.rb, lib/automation/report_context_generator.rb, lib/automation/report_runner.rb, spec/lib/modules/automation/report_runner_spec.rb
Also
- Better diagnostics, output model being used
- Prompt LLM that true content is being injected in <context> tag
=> FEATURE: allow excluding tags and categories from LLM report

config/locales/client.en.yml, discourse_automation/llm_report.rb, lib/automation/report_runner.rb, lib/completions/endpoints/gemini.rb, lib/completions/llm.rb
- Allow users to supply top_p and temperature values, which means people can fine tune randomness
- Fix bad localization string
- Fix bad remapping of max tokens in gemini
- Add support for top_p as a general param to llms
- Amend system prompt so persona stops treating a user as an adversary
=> FEATURE: fine tune llm report to follow instructions more closely

app/models/completion_prompt.rb, lib/ai_helper/assistant.rb, spec/lib/modules/ai_helper/assistant_spec.rb, spec/plugin_spec.rb
We were not properly expiring prompt cache
=> DEV: correct flaky spec

assets/javascripts/discourse/connectors/editor-preview/ai-image-caption-container.gjs, assets/stylesheets/modules/ai-helper/common/ai-helper.scss
Some minor style adjustments and edge case coverage 
Before:
After:
=> UX: minor image caption style adjustments

lib/completions/endpoints/base.rb, lib/inference/cloudflare_workers_ai.rb, lib/inference/discourse_classifier.rb, lib/inference/discourse_reranker.rb, lib/inference/gemini_embeddings.rb, lib/inference/hugging_face_text_embeddings.rb, lib/inference/open_ai_embeddings.rb, lib/inference/open_ai_image_generator.rb, lib/inference/stability_generator.rb, spec/lib/completions/endpoints/endpoint_compliance.rb
The Faraday adapter and `FinalDestionation::HTTP` will protect us from admin-initiated SSRF attacks when interacting with the external services powering this plugin features.:
=> SECURITY: Place a SSRF protection when calling services from the plugin.

config/locales/client.en.yml, discourse_automation/llm_triage.rb, lib/automation/llm_triage.rb, spec/lib/discourse_automation/llm_triage_spec.rb, spec/lib/modules/automation/llm_triage_spec.rb
=> FEATURE: Option for AI triage to send a post to the review queue

config/locales/client.en.yml, config/settings.yml, lib/ai_bot/bot.rb, lib/ai_bot/entry_point.rb, lib/ai_bot/personas/researcher.rb, lib/ai_bot/playground.rb, lib/automation.rb, lib/automation/report_runner.rb, lib/completions/dialects/claude_messages.rb, lib/completions/dialects/dialect.rb, lib/completions/endpoints/anthropic_messages.rb, lib/completions/endpoints/base.rb, lib/completions/llm.rb, spec/lib/completions/dialects/claude_messages_spec.rb, spec/lib/completions/endpoints/anthropic_messages_spec.rb, spec/lib/completions/endpoints/open_ai_spec.rb, spec/lib/modules/ai_bot/playground_spec.rb
This provides new support for messages API from Claude.
It is required for latest model access.
Also corrects implementation of function calls.
=> FEATURE: support for claude opus and sonnet

lib/ai_bot/bot.rb, lib/ai_bot/personas/persona.rb, lib/ai_bot/personas/sql_helper.rb, lib/ai_bot/playground.rb, lib/completions/dialects/chat_gpt.rb, lib/completions/dialects/claude.rb, lib/completions/dialects/dialect.rb, lib/completions/dialects/gemini.rb, lib/completions/dialects/mixtral.rb, lib/completions/dialects/orca_style.rb, lib/completions/prompt.rb, spec/lib/completions/dialects/chat_gpt_spec.rb, spec/lib/completions/dialects/claude_spec.rb, spec/lib/completions/dialects/dialect_context.rb, spec/lib/completions/dialects/gemini_spec.rb, spec/lib/completions/dialects/mixtral_spec.rb, spec/lib/completions/dialects/orca_style_spec.rb, spec/lib/modules/ai_bot/personas/persona_spec.rb
Adds support for "name" on functions which can be used for tool calls
For function calls we need to keep track of id/name and previously
we only supported either
Also attempts to improve sql helper
=> FIX: Tune function calling

app/controllers/discourse_ai/ai_bot/shared_ai_conversations_controller.rb, app/helpers/discourse_ai/ai_bot/shared_ai_conversations_helper.rb, app/views/discourse_ai/ai_bot/shared_ai_conversations/show.html.erb, config/locales/server.en.yml, public/ai-share/share.css, spec/requests/ai_bot/shared_ai_conversations_spec.rb
Also add trivial image styling
=> FIX: expire assets when CSS changes FIX: missing translation on share page

assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js, assets/javascripts/discourse/lib/show-ai-helper.js
Also adds an extra guard around ai helper context positioning.
=> FIX: avoid error when attempting to show ai helper to anon

public/ai-share/share.css
This adds basic onebox styles
Before:
After:
=> UX: add general onebox styles

config/locales/client.en.yml, config/settings.yml, lib/ai_bot/bot.rb, lib/ai_bot/entry_point.rb, spec/lib/completions/endpoints/anthropic_spec.rb, spec/lib/completions/endpoints/endpoint_compliance.rb
it is close in performance to GPT 4 at a fraction of the cost,
nice to add it to the mix.
Also improves a test case to simulate streaming, I am hunting for
the "calls" word that is jumping into function calls and can't quite
find it.
=> FEATURE: add Claude 3 Haiku bot support

app/controllers/discourse_ai/admin/ai_personas_controller.rb, app/jobs/regular/digest_rag_upload.rb, app/jobs/regular/generate_rag_embeddings.rb, app/models/rag_document_fragment.rb, assets/javascripts/discourse/admin/models/ai-persona.js, assets/javascripts/discourse/components/ai-persona-editor.gjs, assets/javascripts/discourse/components/persona-rag-uploader.gjs, assets/javascripts/discourse/components/rag-upload-progress.gjs, assets/stylesheets/modules/ai-bot/common/ai-persona.scss, config/locales/client.en.yml, config/routes.rb, spec/jobs/regular/generate_rag_embeddings_spec.rb, spec/models/rag_document_fragment_spec.rb, test/javascripts/unit/models/ai-persona-test.js, translator.yml
=> UX: Display the indexing progress for RAG uploads

lib/completions/dialects/dialect.rb, spec/lib/completions/dialects/dialect_spec.rb
Some tools may have no params, allow that
=> FIX: tools broke on Claude with no params

assets/javascripts/discourse/components/modal/debug-ai-modal.gjs, assets/stylesheets/modules/ai-bot/common/bot-replies.scss, config/locales/client.en.yml, lib/completions/endpoints/aws_bedrock.rb, lib/completions/endpoints/base.rb, lib/completions/endpoints/cohere.rb, lib/configuration/llm_enumerator.rb, spec/lib/completions/endpoints/aws_bedrock_spec.rb
Also
- Stop caching llm list - this cause llm list in persona to be incorrect
- Add more UI to debug screen so you can properly see raw response
=> FIX: streaming broken in bedrock when chunks are not aligned

lib/ai_bot/personas/persona.rb, lib/completions/endpoints/aws_bedrock.rb, spec/lib/modules/ai_bot/personas/persona_spec.rb
- support " / ' wrapped values
- coerce integer to integer
- enforce enum at boundary
=> FIX: improve function call parsing

test/javascripts/unit/routes/discourse-ai-shared-conversation-show-route-test.js
Follow up to https://github.com/discourse/discourse-ai/pull/622#discussion_r1601199538
=> DEV: use sinon for safer stubbing

config/locales/server.en.yml, lib/ai_bot/personas/persona.rb, lib/ai_bot/tools/javascript_evaluator.rb, spec/lib/modules/ai_bot/tools/javascript_evaluator_spec.rb
This is similar to code interpreter by ChatGPT, except that it uses
JavaScript as the execution engine.
Safeguards were added to ensure memory is constrained and evaluation
times out.
=> FEATURE: JavaScript evaluation tool

app/jobs/regular/create_ai_chat_reply.rb, lib/ai_bot/playground.rb, lib/completions/prompt_messages_builder.rb, spec/lib/modules/ai_bot/playground_spec.rb
This brings the context of the current topic on screen into chat
=> FEATURE: Add support for contextualizing a DM to a bot

app/controllers/discourse_ai/admin/ai_llms_controller.rb, app/models/llm_model.rb, assets/javascripts/discourse/admin/models/ai-llm.js, assets/javascripts/discourse/components/ai-llm-editor.gjs, assets/stylesheets/modules/llms/common/ai-llms-editor.scss, config/locales/client.en.yml, config/routes.rb, lib/completions/endpoints/base.rb, lib/completions/llm.rb, spec/requests/admin/ai_llms_controller_spec.rb
=> FEATURE: Test LLM configuration

config/locales/client.en.yml, lib/ai_bot/bot.rb, lib/automation.rb, lib/completions/dialects/gemini.rb, lib/completions/endpoints/gemini.rb, lib/completions/llm.rb, lib/summarization/entry_point.rb, spec/lib/completions/dialects/gemini_spec.rb, spec/lib/completions/endpoints/gemini_spec.rb
- Geminis streaming implementation was not correct as we did not include the ssr=true param. 
- We were using gemini pro vs pro 1.5 for bot - fixed
- Added support for flash model
=> FIX: correct gemini streaming implementation 

lib/ai_bot/tools/dall_e.rb, spec/lib/modules/ai_bot/tools/dall_e_spec.rb
DallE 3 supports tall/square and wide images.
This adds support to the 3 variants.
=> FEATURE: add aspect ratio support to DallE 3

config/locales/server.en.yml, lib/ai_bot/personas/github_helper.rb, lib/ai_bot/personas/persona.rb, lib/ai_bot/tools/github_search_files.rb, lib/ai_bot/tools/read.rb, lib/ai_bot/tools/search.rb, lib/ai_bot/tools/tool.rb, spec/lib/modules/ai_bot/tools/github_search_files_spec.rb, spec/lib/modules/ai_bot/tools/read_spec.rb
1. New tool to easily find files (and default branch) in a Github repo
2. Improved read tool with clearer params and larger context
=> FEATURE: improved tooling

lib/ai_bot/bot.rb, lib/completions/dialects/cohere_tools.rb, lib/completions/dialects/command.rb, lib/completions/endpoints/cohere.rb, spec/lib/completions/endpoints/cohere_spec.rb
Add native Cohere tool support
- Introduce CohereTools class for tool translation and result processing
- Update Command dialect to integrate with CohereTools
- Modify Cohere endpoint to support passing tools and processing tool calls
- Add spec for testing tool triggering with Cohere endpoint
=> FEATURE: Add native Cohere tool support

lib/completions/anthropic_message_processor.rb, lib/completions/dialects/claude.rb, lib/completions/dialects/claude_tools.rb, lib/completions/endpoints/anthropic.rb, lib/completions/endpoints/aws_bedrock.rb, lib/completions/endpoints/base.rb, spec/lib/completions/dialects/claude_spec.rb, spec/lib/completions/endpoints/anthropic_spec.rb, spec/lib/completions/endpoints/aws_bedrock_spec.rb
This migrates us to native function calling on anthropic.
=> FEATURE: anthropic function calling

assets/javascripts/discourse/components/ai-llms-list-editor.gjs, assets/javascripts/discourse/components/ai-persona-list-editor.gjs
This core PR will change the component API a bit,
so it's easier to remove these for now and add them
back after:
https://github.com/discourse/discourse/pull/27365
=> DEV: Remove breadcrumbs for now

app/controllers/discourse_ai/admin/ai_llms_controller.rb, app/models/llm_model.rb, app/serializers/llm_model_serializer.rb, assets/javascripts/discourse/components/ai-llm-editor-form.gjs, config/locales/client.en.yml, spec/fabricators/llm_model_fabricator.rb, spec/requests/admin/ai_llms_controller_spec.rb
- Validate fields to reduce the chance of breaking features by a misconfigured model.
- Fixed a bug where the URL might get deleted during an update.
- Display a warning when a model is currently in use.
=> FIX: LlmModel validations.

assets/stylesheets/modules/ai-helper/mobile/ai-helper.scss
=> UX: add dark-light mixin for better visibility in dark themes

assets/javascripts/discourse/components/modal/diff-modal.gjs, assets/javascripts/initializers/ai-helper.js, assets/stylesheets/modules/ai-helper/common/ai-helper.scss, config/locales/client.en.yml, spec/system/ai_helper/ai_proofreading_spec.rb
Previously there was too much work proofreading text, new implementation
provides a single shortcut and easy way of proofreading text.
=> FEATURE: single click proofreading

app/controllers/discourse_ai/admin/ai_llms_controller.rb, app/models/llm_model.rb, app/serializers/llm_model_serializer.rb, assets/javascripts/discourse/components/ai-llm-editor-form.gjs, assets/stylesheets/modules/llms/common/ai-llms-editor.scss, config/locales/client.en.yml, config/locales/server.en.yml, config/settings.yml, lib/automation.rb, lib/configuration/llm_validator.rb
=> FEATURE: Initial support for seeded LLMs

spec/requests/embeddings/embeddings_controller_spec.rb
~500ms -> ~100ms
It is still not a super fast spec given search is not free, but
it is a bit faster and clearer
=> PERF: speed up spec

app/models/ai_api_audit_log.rb, config/locales/client.en.yml, lib/completions/dialects/open_ai_compatible.rb, lib/completions/endpoints/base.rb, lib/completions/endpoints/samba_nova.rb, lib/completions/llm.rb, spec/fabricators/llm_model_fabricator.rb, spec/lib/completions/endpoints/samba_nova_spec.rb
Note, at the moment the context window is quite small, it is
mainly useful as a helper backend or hyde generator
=> FEATURE: add a SambaNova LLM provider

app/controllers/discourse_ai/admin/ai_personas_controller.rb, app/jobs/regular/digest_rag_upload.rb, app/jobs/regular/generate_rag_embeddings.rb, app/models/ai_persona.rb, app/models/rag_document_fragment.rb, db/migrate/20240912052713_add_target_to_rag_document_fragment.rb, db/post_migrate/20240912055831_drop_persona_id_from_rag_document_fragments.rb, lib/ai_bot/personas/persona.rb, lib/embeddings/vector_representations/base.rb, spec/jobs/regular/digest_rag_upload_spec.rb, spec/jobs/regular/generate_rag_embeddings_spec.rb, spec/lib/modules/ai_bot/personas/persona_spec.rb, spec/models/ai_persona_spec.rb, spec/models/rag_document_fragment_spec.rb, spec/requests/admin/ai_personas_controller_spec.rb
Polymorphic RAG means that we will be able to access RAG fragments both from AiPersona and AiCustomTool
In turn this gives us support for richer RAG implementations. 
You can define a custom tool with custom rules for querying the RAG. 
So something like
- Query File1 for 3 results
- Query File10 for 20 results 
Becomes feasible in a tool. 
This allows people implementing a RAG extreme flexibility.
=> FEATURE: Make tool support polymorphic

lib/ai_bot/entry_point.rb
Followup bdf3b6268b2843f4b2ba8f8875e4d18a952ef326
I think this is the fix but not sure how to test it,
this is breaking the build
=> FIX: Remove missed AiPersona.allowed_chat

lib/completions/open_ai_message_processor.rb, spec/lib/completions/endpoints/open_ai_spec.rb
Fixes issue in Open AI provider eating newlines and spaces
=> FIX: do not strip empty string during stream processing

assets/javascripts/discourse/components/admin-report-emotion.hbs, assets/javascripts/discourse/components/admin-report-emotion.js, assets/javascripts/discourse/controllers/admin-dashboard-sentiment.js, spec/system/admin_dashboard_spec.rb
=> FEATURE: Add links to filtered emotion view on emotion dashboard table

assets/javascripts/discourse/components/ai-llms-list-editor.gjs
Followup 2f7895bb91c980d2954944b0574d44ff0d8237fb,
I forgot to commit this minor change
=> UX: Add table style for LLM list

app/jobs/scheduled/embeddings_backfill.rb
I'm trying to solve two issues here:
1. Using `find_in_batches` or `find_each` will ignore the limit because it relies on it to specify a batch size.
2. We need to individually apply the limit on each step since `rebaked` gets bigger every time we process a batch.
=> FIX: Make sure limits are updated and applied on each step

assets/javascripts/discourse/components/ai-full-page-search.gjs
Needed to customize the colors of the toggle for this state :)
=> DEV: Add no-results className to full page search toggle

assets/javascripts/discourse/components/ai-usage.gjs
There is a new Meta topic for this:
https://meta.discourse.org/t/discourse-ai-ai-usage/348677
=> UX: Update usage "Learn more..." link

config/locales/client.en.yml
This is a little longer, but this helps explain what embeddings are in addition to providing examples of where they're used.
=> UX: clarify embeddings description

config/eval-llms.yml, evals/lib/eval.rb
Adds sonnet 3.7
Adds support for temp in eval framework
=> Dev: eval improvements

lib/ai_bot/tool_runner.rb, spec/models/ai_tool_spec.rb
Previously we could only get post info
=> DEV: add API to get topic info from a custom tool

lib/completions/llm.rb
This will be useful to start experiment with non-standard features like
structured outputs.
=> DEV: Support for extra model params in LLM completions

assets/javascripts/discourse/components/ai-persona-editor.gjs
300 was too low, bumped it to 100_000
=> FIX: bump system prompt limit

assets/stylesheets/modules/ai-bot/common/ai-discobot-discoveries.scss
Some minor styling adjustments
Before
After
=> UX: wider discovery search pane, border, smaller font size

spec/system/ai_helper/ai_proofreading_spec.rb
This reverts commit e81108abb6819d36eb3c6b9f539c56eb47d34e59.
=> Revert "DEV: Add test to cover proofreading in rich editor (#1259)"

assets/javascripts/discourse/controllers/discourse-ai-bot-conversations.js, assets/javascripts/discourse/templates/discourse-ai-bot-conversations.gjs, assets/stylesheets/modules/ai-bot-conversations/common.scss
Update loading animation 
https://github.com/user-attachments/assets/f3bb6ca7-5d84-4231-8ea1-fa49fa402eae
- Add plugin outlet 
- update `updateInputValue` so that it can be used by plugins to update the input value
=> DEV: Add `ai-bot-conversations-above-input` plugin outlet and update loading animation

app/models/llm_model.rb, config/locales/client.en.yml, lib/completions/dialects/chat_gpt.rb, lib/completions/dialects/open_ai_tools.rb, lib/completions/endpoints/open_ai.rb, lib/completions/open_ai_responses_message_processor.rb, spec/lib/completions/endpoints/open_ai_responses_api_spec.rb
OpenAI ship a new API for completions called "Responses API" 
Certain models (o3-pro) require this API.
Additionally certain features are only made available to the new API. 
This allow enabling it per LLM.    
see: https://platform.openai.com/docs/api-reference/responses
=> FEATURE: optionally support OpenAI responses API

assets/stylesheets/common/ai-features.scss
| before | after |
|--|--|
| <img width="354" alt="Screenshot 2025-06-24 at 5 01 19 PM" src="https://github.com/user-attachments/assets/245c4a5a-12b3-45ce-a144-55d68f3a49f4" /> | <img width="355" alt="Screenshot 2025-06-24 at 5 02 04 PM" src="https://github.com/user-attachments/assets/2cd318a0-5a91-431b-aa04-df400ed495d5" /> |
=> UX: Align llm button in ai features
