- app/models/reviewable_a_i_chat_message.rb
- app/models/reviewable_a_i_post.rb
- app/serializers/a_i_chat_channel_serializer.rb
- app/serializers/reviewable_a_i_chat_message_serializer.rb
- app/serializers/reviewable_a_i_post_serializer.rb
- assets/javascripts/discourse/components/reviewable-aichat-message.js
- spec/lib/modules/toxicity/jobs/regular/toxicity_classify_chat_message_spec.rb
- spec/models/reviewable_a_i_chat_message_spec.rb
We cannot depend on classes defined by another plugin, there's no way to make sure they'll be loaded before we load this plugin's classes.
Additionally, this fixed an issue with the `ReviewableAIChatMessage` not showing a link to the flagged message.
> FIX: Do not inherit from classes defined by plugins

- app/controllers/discourse_ai/ai_helper/assistant_controller.rb
- assets/javascripts/discourse/components/ai-helper.hbs
- assets/javascripts/discourse/components/ai-helper.js
- assets/javascripts/discourse/components/model-accuracies.hbs
- assets/javascripts/discourse/templates/modal/composer-ai-helper.hbs
- assets/javascripts/initializers/composer-ai-helper.js
- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
- config/locales/client.en.yml
- config/locales/server.en.yml
- config/routes.rb
- config/settings.yml
- lib/discourse_ai/engine.rb
- lib/modules/ai_helper/entry_point.rb
- lib/modules/ai_helper/open_ai_prompt.rb
- lib/shared/inference/openai_completions.rb
- lib/shared/inference/openai_embeddings.rb
- plugin.rb
- spec/lib/modules/ai_helper/open_ai_prompt_spec.rb
- spec/requests/ai_helper/assistant_controller_spec.rb
- spec/support/openai_completions_inference_stubs.rb
- spec/system/ai_helper/ai_composer_helper_spec.rb
- spec/system/page_objects/modals/ai_helper.rb
This change introduces a new composer button for the group members listed in the `ai_helper_allowed_groups` site setting.
Users can use chatGPT to review, improve, or translate their posts to English.
> FEATURE: Composer AI helper

- db/fixtures/ai-helper/600_completion_prompts.rb
This makes easier to add new defaults in the feature without clashing with user created ones.
> DEV: Use negative ids for seeded prompts.

- db/migrate/20230322142028_make_dropped_value_column_nullable.rb
It's causing an issue when attempting to seed data in fresh installs. The column was dropped in a post-migration.
> FIX: Remove `null: false` from dropped column

- assets/javascripts/discourse/connectors/topic-above-suggested/related-topics.js
- assets/javascripts/discourse/templates/connectors/topic-above-suggested/related-topics.hbs
- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
- config/locales/client.en.yml
- config/locales/server.en.yml
- config/settings.yml
- lib/modules/embeddings/entry_point.rb
- lib/modules/embeddings/semantic_suggested.rb
- spec/lib/modules/embeddings/semantic_suggested_spec.rb
- spec/requests/topic_spec.rb
This is an attempt at including related above suggested for logged on users
TODO
- tests
- ensure this is zero work if feature is not enabled
- perhaps get rid of ai_embeddings_semantic_suggested_topics_anon_enabled and use a diff setting for both
- have this disable random suggested, so we don't double up when logged in
> FEATURE: attempt to include related topics above suggested

- assets/javascripts/initializers/chat-summary.js
As a result of this change the channel is now accessible through `this.args.channel` and not `this.chatChannel`.
Longer term we want a better solution here, but this should fix the issue for now.
> FIX: chat-composer is now using glimmer

- assets/javascripts/initializers/chat-summary.js
- assets/javascripts/initializers/composer-ai-helper.js
- assets/javascripts/initializers/semantic-full-page-search.js
- assets/javascripts/initializers/topic-summary.js
1. Add missing `pluginId` to `modifyClass` calls
2. Replace deprecated `site-settings:main` lookups with `service:site-settings`
3. Use "kebab-case" for initializer names
> DEV: Fix minor js issues

- app/controllers/discourse_ai/ai_bot/bot_controller.rb
- assets/javascripts/discourse/components/ai-bot-header-icon.hbs
- assets/javascripts/discourse/components/ai-bot-header-icon.js
- assets/javascripts/discourse/widgets/ai-bot-header-icon.js
- assets/javascripts/initializers/ai-bot-replies.js
- assets/stylesheets/modules/ai-bot/common/bot-replies.scss
- config/locales/client.en.yml
- config/locales/server.en.yml
- config/routes.rb
- config/settings.yml
- lib/modules/ai_bot/anthropic_bot.rb
- lib/modules/ai_bot/bot.rb
- lib/modules/ai_bot/entry_point.rb
- lib/modules/ai_bot/jobs/regular/update_ai_bot_pm_title.rb
- lib/modules/ai_bot/open_ai_bot.rb
- spec/lib/modules/ai_bot/bot_spec.rb
- spec/requests/ai_bot/bot_controller_spec.rb
This PR adds a new header icon as a shortcut to start a conversation with one of our AI Bots. After clicking and selecting one from the dropdown menu, we'll open the composer with some fields already filled (recipients and title).
If you leave the title as is, we'll queue a job after five minutes to update it using a bot suggestion.
> FEATURE: Less friction for starting a conversation with an AI bot.

- assets/javascripts/discourse/components/ai-bot-header-panel.js
- assets/javascripts/discourse/lib/ai-bot-helper.js
- assets/javascripts/discourse/widgets/ai-bot-header-panel-wrapper.js
- assets/javascripts/initializers/ai-bot-replies.js
- Remove unused 'toggleAiBotPanel' widget action
- Switch from appEvents to closure actions
- Convert widget definition to native class syntax, so that we can use `@action` decorator. (alternatively, we could have done `{ closePanel: this.hideAiBotPanel.bind(this) }` in `RenderGlimmer`
> DEV: Tweaks for drop-down implementation

- lib/modules/ai_bot/commands/search_command.rb
- spec/lib/modules/ai_bot/commands/search_command_spec.rb
Previous to this change invalid searches would break the command.
> FIX: results will be nil for invalid queries

- lib/modules/embeddings/semantic_related.rb
- lib/modules/embeddings/topic.rb
- spec/lib/modules/embeddings/semantic_related_spec.rb
This also heavily reduced log noise and ensures our exception handling is
more surgical.
> FIX: ensure we only attempt embedding once every 15 minutes

- lib/modules/ai_bot/anthropic_bot.rb
- lib/modules/ai_bot/bot.rb
- lib/modules/ai_bot/commands/command.rb
- lib/modules/ai_bot/commands/search_command.rb
- lib/modules/ai_bot/commands/summarize_command.rb
- lib/modules/ai_bot/open_ai_bot.rb
- spec/lib/modules/ai_bot/anthropic_bot_spec.rb
- spec/lib/modules/ai_bot/bot_spec.rb
- spec/lib/modules/ai_bot/commands/search_command_spec.rb
- spec/lib/modules/ai_bot/jobs/regular/create_ai_reply_spec.rb
- spec/lib/modules/ai_bot/open_ai_bot_spec.rb
This limits search results to 10 cause we were blowing the whole token
budget on search results, additionally it includes a quick exchange at
the start of a session to try and guide GPT 3.5 to follow instructions
Sadly GPT 3.5 drifts off very quickly but this does improve stuff a bit.
It also attempts to correct some issues with anthropic, though it still is
surprisingly hard to ground
> FIX: guide GPT 3.5 better

- assets/javascripts/initializers/ai-bot-replies.js
- lib/modules/ai_bot/commands/search_command.rb
- spec/lib/modules/ai_bot/jobs/regular/create_ai_reply_spec.rb
blog.start_gpt_chat -> was on my blog
This also slightly tunes the search prompt to support filtering by oldest
and try a tiny bit harder to guide GPT 3.5 which is a bit of a losing battle
> FIX: missing localization

- lib/modules/ai_bot/anthropic_bot.rb
- lib/modules/ai_bot/bot.rb
- lib/modules/ai_bot/commands/search_command.rb
- lib/modules/ai_bot/open_ai_bot.rb
- lib/shared/inference/anthropic_completions.rb
- spec/lib/modules/ai_bot/bot_spec.rb
- spec/lib/modules/ai_bot/jobs/regular/create_ai_reply_spec.rb
- spec/shared/inference/anthropic_completions_spec.rb
- spec/support/anthropic_completion_stubs.rb
- spec/support/openai_completions_inference_stubs.rb
For the time being smart commands only work consistently on GPT 4.
Avoid using any smart commands on the earlier models.
Additionally adds better error handling to Claude which sometimes streams
partial json and slightly tunes the search command.
> FEATURE: disable smart commands on Claude and GPT 3.5

- config/locales/server.en.yml
- lib/modules/ai_bot/bot.rb
- lib/modules/ai_bot/commands/image_command.rb
- lib/modules/ai_bot/commands/search_command.rb
- lib/modules/ai_bot/open_ai_bot.rb
- spec/lib/modules/ai_bot/bot_spec.rb
- spec/lib/modules/ai_bot/jobs/regular/create_ai_reply_spec.rb
- spec/lib/modules/ai_bot/open_ai_bot_spec.rb
```
prompt << build_message(bot_user.username, reply)
```
Would store a "cooked" prompt which is invalid, instead just store the raw
values which are later passed to build_message
Additionally:
1. Disable summary command which needs honing
2. Stop storing decorations (searched for X) in prompt which leads to straying
3. Ship username directly to model, avoiding "user: content" in prompts. This
was causing GPT to stray
> FIX: avoid storing corrupt prompts

- config/locales/server.en.yml
- config/settings.yml
- lib/shared/inference/openai_completions.rb
- lib/shared/inference/openai_embeddings.rb
- spec/shared/inference/openai_completions_spec.rb
- spec/shared/inference/openai_embeddings_spec.rb
The new site settings:
ai_openai_gpt35_url
ai_openai_gpt4_url
ai_openai_embeddings_url
Can be used to configure OpenAI support on Azure. If untouched we will simply
use OpenAI endpoints.
Note: Azure require 1 URL per model, OpenAI allows a single URL to serve
multiple models.
> FEATURE: Add Azure cognitive service support

- config/locales/server.en.yml
- config/settings.yml
- lib/modules/ai_bot/commands/command.rb
- lib/modules/ai_bot/commands/google_command.rb
- lib/modules/ai_bot/commands/search_command.rb
- lib/modules/ai_bot/commands/time_command.rb
- lib/modules/ai_bot/open_ai_bot.rb
- spec/lib/modules/ai_bot/bot_spec.rb
- spec/lib/modules/ai_bot/commands/search_command_spec.rb
- spec/lib/modules/ai_bot/commands/time_command_spec.rb
- spec/lib/modules/ai_bot/open_ai_bot_spec.rb
This allows admins to disable/enable GPT command integrations.
Also hones search results which were looping cause the result did not denote
the failure properly (it lost context)
> FEATURE: add ai_bot_enabled_chat commands and tune search

- lib/modules/ai_bot/open_ai_bot.rb
- spec/lib/modules/ai_bot/jobs/regular/create_ai_reply_spec.rb
Reduce maximum replies to 2500 tokens and make them even for both GPT-3.5
and 4
Account for 400+ tokens in function definitions (this was unaccounted for)
> FIX: adjust token limits to account for functions

- lib/modules/summarization/models/anthropic.rb
- lib/modules/summarization/models/base.rb
- lib/modules/summarization/models/discourse.rb
- lib/modules/summarization/models/open_ai.rb
- lib/modules/summarization/strategies/fold_content.rb
- spec/lib/modules/summarization/models/anthropic_spec.rb
- spec/lib/modules/summarization/models/discourse_spec.rb
- spec/lib/modules/summarization/models/open_ai_spec.rb
- spec/support/summarization/dummy_completion_model.rb
Single and multi-chunk summaries end up using different prompts for the last summary. This change detects when the summarized content fits in a single chunk and uses a slightly different prompt, which leads to more consistent summary formats.
This PR also moves the chunk-splitting step to the `FoldContent` strategy as preparation for implementing streamed summaries.
> REFACTOR: Cohesive narrative for single-chunk summaries.

- assets/javascripts/initializers/ai-bot-replies.js
- assets/javascripts/initializers/composer-ai-helper.js
A missing parameter on the `parseInt` function was causing unexpected UI behavior for the AI helper since it turned an allowed group ID into NaN. We should always use base10 when parsing these IDs.
> FIX: Use base 10 when gettings allowed group IDs from settings.

- lib/modules/embeddings/entry_point.rb
- lib/modules/embeddings/semantic_related.rb
- spec/lib/modules/embeddings/entry_point_spec.rb
- spec/lib/modules/embeddings/semantic_related_spec.rb
- spec/requests/topic_spec.rb
TopicQuery already provides a lot of safeguards and options for filtering topic, and enforcing permissions. It makes sense to rely on it as other plugins like discourse-assign do.
As a bonus, we now have access to the current_user while serializing these topics, so users will see things like unread posts count just like we do for the lists.
> REFACTOR: Build related topics using TopicQuery.

- lib/modules/ai_bot/commands/categories_command.rb
- lib/modules/ai_bot/commands/command.rb
- lib/modules/ai_bot/commands/google_command.rb
- lib/modules/ai_bot/commands/image_command.rb
- lib/modules/ai_bot/commands/search_command.rb
- lib/modules/ai_bot/commands/summarize_command.rb
- lib/modules/ai_bot/commands/tags_command.rb
- lib/modules/ai_bot/commands/time_command.rb
- spec/lib/modules/ai_bot/bot_spec.rb
- spec/lib/modules/ai_bot/commands/categories_command_spec.rb
- spec/lib/modules/ai_bot/commands/google_command_spec.rb
- spec/lib/modules/ai_bot/commands/search_command_spec.rb
- spec/lib/modules/ai_bot/commands/summarize_command_spec.rb
- spec/lib/modules/ai_bot/commands/tags_command_spec.rb
- spec/lib/modules/ai_bot/commands/time_command_spec.rb
The command framework had some confusing dispatching where it would dispatch
JSON blobs, this meant there was lots of parsing required in every command
The refactor handles transforming the args prior to dispatch which makes
consuming far simpler
This is also general prep to supporting some basic command framework in other
llms.
> DEV: simplify command framework

- lib/modules/ai_bot/commands/google_command.rb
- spec/lib/modules/ai_bot/commands/google_command_spec.rb
Additionally there was no truncating happening meaning you could blow token
budget easily on a single search.
This made Google search mostly useless and it would mean that after using
Google we would revert to a clean slate which is very confusing.
> FIX: Google command was including full payload

- config/locales/server.en.yml
- config/settings.yml
- lib/modules/ai_bot/commands/read_command.rb
- lib/modules/ai_bot/entry_point.rb
- lib/modules/ai_bot/open_ai_bot.rb
- spec/lib/modules/ai_bot/commands/read_command_spec.rb
This command is useful for reading a topics content. It allows us to perform
critical analysis or suggest answers.
Given 8k token limit in GPT-4 I hardcoded reading to 1500 tokens, but we can
follow up and allow larger windows on models that support more tokens.
On local testing even in this limited form this can be very useful.
> FEATURE: experimental read command for bot

- config/locales/server.en.yml
- lib/modules/ai_bot/commands/command.rb
- lib/modules/ai_bot/commands/image_command.rb
- lib/modules/ai_bot/commands/read_command.rb
- spec/lib/modules/ai_bot/commands/google_command_spec.rb
- spec/lib/modules/ai_bot/commands/image_command_spec.rb
- spec/lib/modules/ai_bot/commands/read_command_spec.rb
- FIX: refine image and read command
- Add a test for image command
> FIX: refine image and read command

- assets/javascripts/discourse/components/ai-bot-header-panel.js
- assets/javascripts/discourse/connectors/composer-after-composer-editor/composer-open.hbs
- assets/javascripts/discourse/connectors/composer-after-composer-editor/composer-open.js
- assets/javascripts/discourse/lib/ai-bot-helper.js
- assets/stylesheets/modules/ai-bot/common/bot-replies.scss
- config/locales/client.en.yml
- config/locales/server.en.yml
- config/settings.yml
- lib/modules/ai_bot/entry_point.rb
This commit introduces `ai_bot_enable_chat_warning` which can be used
to warn people prior to starting a chat with the bot.
In particular this is useful if moderators are regularly reading chat
transcripts as it sets expectations early.
By default this is disabled.
Also:
- Stops making ajax call prior to opening composer
- Hides PM title when starting a bot PM
Design can be improved but at least this is a start.
> FEATURE: optional warning attached to all AI bot conversations

- config/locales/client.en.yml
- config/settings.yml
Moving the plugin settings into a more specific category
makes them easier to find in the plugin UI and removes
them from the generic "Plugins" tab.
> DEV: Categorize plugin settings into discourse_ai

- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
This PR is a follow up to https://github.com/discourse/discourse-ai/pull/148 and ensures that the AI helper context menu is shown only if the current user is a member of one/more of the  `ai_helper_allowed_groups`
> FIX: Show AI helper only if in allowed groups

- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
This PR is another follow up to https://github.com/discourse/discourse-ai/pull/148, which adds a check to ensure the context menu is conditionally shown in PMs based on the site setting: `ai_helper_allowed_in_pm`
> FIX: Add check for PMs before showing AI helper context menu

- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
This PR fixes a bug that causes pages with small composers to crash
> FIX: Pages with small composers breaking

- lib/modules/ai_bot/anthropic_bot.rb
- lib/modules/ai_bot/bot.rb
- lib/modules/ai_bot/entry_point.rb
- lib/modules/ai_bot/jobs/regular/update_ai_bot_pm_title.rb
- lib/shared/inference/function_list.rb
- spec/lib/modules/ai_bot/jobs/regular/update_ai_bot_pm_title_spec.rb
This fixes 2 big issues:
1. No matter how hard you try, grounding anthropic title prompt
is just too hard. This works around by only looking at the last
sentence it returns and treating as title
2. Non English locales would be stuck with "generic" title, this
ensures every bot message gets a title, using a custom field to
track
Also, slightly tunes some anthropic prompts.
> FIX: automatic bot titles missing sometime

- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
In Firefox, `event.target.activeElement` does not exist, instead we need to use `event.target`, however the issue is that in all other browsers `event.target` inside `<textarea>` elements points to the HTML DOM, not a specific element. In all other browsers we need to use `event.target.activeElement` to point to the `<textarea>`
To resolve this so that works on all browsers we use `document.activeElement` and compare it with `this._dEditorInput` to see if it is the same.
In Firefox, `window.getSelection().toString()` will always result in an empty string. Due to this bug in Firefox, we instead use `selectionStart` and `selectionEnd` to identify what is selected from the `document.activeElement`'s value.
This PR has been tested on Firefox, Chromium, and Safari to ensure all functionality …
> FIX: Context menu not appearing in Firefox

- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
- spec/system/ai_helper/ai_composer_helper_spec.rb
Previously after generating with AI, the "reset" options (Undo / Try Again) will automatically be hidden after 5 seconds. This however, is annoying when you are still reading the changes.
This PR removes the timeout and only relies on clicking outside to hide the reset options
> DEV: Remove context menu timeout

- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
- spec/system/ai_helper/ai_composer_helper_spec.rb
- spec/system/page_objects/components/ai_helper_context_menu.rb
**This PR adds some actions on key press for context menus:**
- Ability to <kbd>Esc</kbd> to close context menu
- Ability to <kbd>Ctrl</kbd>/<kbd>Cmd</kbd> + <kbd>Z</kbd> to undo results
> DEV: Add keybindings

- assets/javascripts/discourse/components/modal/diff-modal.gjs
- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.hbs
- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
- config/locales/client.en.yml
- spec/system/ai_helper/ai_composer_helper_spec.rb
- spec/system/page_objects/components/ai_helper_context_menu.rb
- spec/system/page_objects/modals/diff_modal.rb
This PR adds an intermediary step to the AI Helper context menu. It adds a confirmation step where you can <kbd>View Changes</kbd> <kbd>Revert</kbd> <kbd>Apply</kbd>. If you click <kbd>View Changes</kbd> a modal is shown with the changes that are made to the text by AI.
https://github.com/discourse/discourse-ai/assets/30090424/9fa8505f-432f-439f-bb63-8d886739c02e
> DEV: Add review menu state

- package.json
- yarn.lock
This PR updates `eslint-config-discourse` so that no more linting errors appear on `.gjs` files when `<template>` tags are used.
> DEV: Update ESLint config version

- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
**This PR makes some styling improvements to the context menu such as:**
1. Makes button fill `<li>` so that full width of context menu button row is clickable
2. Uses `--shadow-card` for box-shadow instead of `--shadow-dropdown` to improve contrast when context menu is on top of toolbar area
> UX: Context menu improvements

- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
Previously the prompts would be fetched on first loading the prompt section and then cached, however, if the network was slow or the request failed it would look obvious while interacting with the context menu component.
This PR ensures the prompts are preloaded when the component is first initialized (i.e. composer is opened) so there is no delay when clicking the AI button.
> DEV: Preload prompt list on component initialization

- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
This PR resolves a UX issue when the context menu was able to overflow outside of the container:
https://github.com/discourse/discourse-ai/assets/30090424/bf073209-1167-489f-a7a5-8ea8d461c627
https://github.com/discourse/discourse-ai/assets/30090424/cf8f762a-7db3-4b07-83dd-10a9ef191720
> UX: Prevent context menu overflow outside of container

- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
- spec/system/ai_helper/ai_composer_helper_spec.rb
This PR ensures that clicking outside the context menu (especially outside the editor pane) closes the context menu. It also moves any short circuiting / checks for accidentally closing the context menu into its on `canCloseContextMenu` getter.
https://github.com/discourse/discourse-ai/assets/30090424/ca86c6a7-dc46-4661-b1a2-2acd39aaa8fd
https://github.com/discourse/discourse-ai/assets/30090424/ccaf2034-1a9d-410b-bc5e-53d75a8222c6
> UX: Clicking outside editor should close context menu

- config/locales/server.en.yml
- config/settings.yml
- lib/modules/ai_bot/anthropic_bot.rb
- lib/modules/ai_bot/bot.rb
- lib/modules/ai_bot/commands/command.rb
- lib/modules/ai_bot/commands/read_command.rb
- lib/modules/ai_bot/commands/setting_context_command.rb
- lib/modules/ai_bot/entry_point.rb
- lib/modules/ai_bot/open_ai_bot.rb
- spec/lib/modules/ai_bot/commands/search_command_spec.rb
- spec/lib/modules/ai_bot/commands/setting_context_command.rb
- spec/lib/modules/ai_bot/open_ai_bot_spec.rb
This command can be used to extract information about a discourse
site setting directly from source.
To operate it needs the rg binary in the container.
> FEATURE: add setting_context experimental command

- lib/modules/ai_bot/anthropic_bot.rb
- spec/lib/modules/ai_bot/anthropic_bot_spec.rb
Anthropic loves sending a pointless leading space with completions
this throws off the command framework.
> FIX: trim first space when getting a reply from anthropic

- assets/javascripts/discourse/connectors/after-composer-title-input/ai-title-suggester.gjs
- assets/javascripts/discourse/connectors/after-composer-title-input/suggest-titles-button.gjs
- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.hbs
- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
- config/locales/client.en.yml
- spec/system/ai_helper/ai_composer_helper_spec.rb
- spec/system/page_objects/components/ai_helper_context_menu.rb
- spec/system/page_objects/components/ai_title_suggester.rb
This PR moves the suggested title prompt to be triggered by a button right next to the title input in the composer. This is a more sensible location to access title suggestions and goes better with the general workflow when composing a topic.
https://github.com/discourse/discourse-ai/assets/30090424/3aeaf667-8c1f-457f-a991-c7412b790f41
> FEATURE: Show suggested title prompt in new location

- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
This PR updates the placement of the context menu so that it will be placed at the top of the selection **except** when near the button bar. In such cases it will be placed at the bottom of the selection. This is done to ensure that the context menu doesn't interfere with the button bar and selecting buttons on it.
https://github.com/discourse/discourse-ai/assets/30090424/4bdf990d-040d-48a2-a791-78f649aa69e8
> DEV: Dynamically set popper placement

- assets/javascripts/discourse/connectors/after-composer-title-input/ai-title-suggester.gjs
- config/locales/client.en.yml
This PR doesn't submit the request and instead gives a popup message when you try to suggest titles without content
> FIX: Show warning when trying to generate suggestions without content

- assets/javascripts/discourse/connectors/after-d-editor/composer-open.js
- assets/javascripts/discourse/connectors/composer-fields/persona-selector.hbs
- assets/javascripts/discourse/connectors/composer-fields/persona-selector.js
- assets/javascripts/initializers/ai-bot-replies.js
- assets/stylesheets/modules/ai-bot/common/bot-replies.scss
- config/locales/server.en.yml
- lib/modules/ai_bot/bot.rb
- lib/modules/ai_bot/commands/db_schema_command.rb
- lib/modules/ai_bot/entry_point.rb
- lib/modules/ai_bot/personas/artist.rb
- lib/modules/ai_bot/personas/general.rb
- lib/modules/ai_bot/personas/persona.rb
- lib/modules/ai_bot/personas/sql_helper.rb
- lib/shared/inference/function.rb
- lib/shared/inference/function_list.rb
- spec/lib/modules/ai_bot/commands/db_schema_command_spec.rb
- spec/lib/modules/ai_bot/personas/persona_spec.rb
- spec/lib/modules/ai_bot/personas/sql_helper_spec.rb
- spec/shared/inference/function_list_spec.rb
This completes a V0 of personas. Personas are ways of adjusting our bot framework
so it behaves differently based on user expectations. 
This ships with 3 personas: 
- General - which is the standard one we use today
- Artist - which is purpose built for creating pictures
- Sql Helper - which is there to help building data explorer queries
We display a picker now to help pick which persona you want and decorate the bot to print the persona
System is very much V0, we are anticipating allowing Discourse admins to create the personas they want.
> FEATURE: add initial support for personas

- assets/javascripts/initializers/ai-bot-replies.js
- config/locales/server.ar.yml
- config/locales/server.de.yml
- config/locales/server.en.yml
- config/locales/server.es.yml
- config/locales/server.fi.yml
- config/locales/server.fr.yml
- config/locales/server.he.yml
- config/locales/server.it.yml
- config/locales/server.ja.yml
- config/locales/server.nl.yml
- config/locales/server.pl_PL.yml
- config/locales/server.pt_BR.yml
- config/locales/server.ru.yml
- config/locales/server.tr_TR.yml
- config/locales/server.zh_CN.yml
- config/settings.yml
- db/migrate/20230831033812_rename_ai_helper_add_ai_pm_to_header_setting.rb
Old name was very unclear, this setting is only used for the bot
so now it follows the same convention others do
> DEV: rename ai_helper_add_ai_pm_to_header -> ai_bot_add_to_header

- config/locales/server.en.yml
- config/settings.yml
- lib/modules/ai_bot/entry_point.rb
- lib/modules/ai_bot/personas/persona.rb
- lib/modules/ai_bot/personas/settings_explorer.rb
- lib/modules/ai_bot/personas/sql_helper.rb
- spec/lib/modules/ai_bot/personas/persona_spec.rb
- spec/lib/modules/ai_bot/personas/settings_explorer_spec.rb
Also adds ai_bot_enabled_personas so admins can tweak which stock
personas are enabled.
The new persona has a full listing of all site settings and is
able to get context for each setting.
This means you can ask it to search through settings for something
relevant.
Security wise there is no access to actual configuration of settings
just to the names / description and implementation.
Previously this was part of the forum helper persona however it
just clashes too much with other behaviors, isolating it makes
it far more powerful.
> FEATURE: new site setting explorer persona

- spec/lib/modules/toxicity/entry_point_spec.rb
As message creation is being rewritten in
https://github.com/discourse/discourse/pull/22390, a new way of using the underlying service to create chat messages has been implemented in https://github.com/discourse/discourse/pull/23222.
This patch uses the new fabricator option which will prevent breaking specs from this plugin when the main PR will be merged.
> DEV: Don’t use `Chat::MessageCreator` in specs

- config/locales/server.en.yml
- lib/modules/ai_bot/anthropic_bot.rb
- lib/modules/ai_bot/commands/search_settings_command.rb
- lib/modules/ai_bot/entry_point.rb
- lib/modules/ai_bot/personas/settings_explorer.rb
- lib/shared/inference/anthropic_completions.rb
- lib/shared/inference/openai_completions.rb
- spec/lib/modules/ai_bot/commands/search_settings_command_spec.rb
- spec/lib/modules/ai_bot/personas/settings_explorer_spec.rb
- FIX: setting explorer was exceeding token budget
- In dev it is important to tell when calls are made to open ai this adds a console log to increase awareness around token usage
- PERF: stop counting tokens so often
- bug fix, commands may reach in for tokenizer
- add logging to console for anthropic calls as well
> fix settings explorer

- assets/javascripts/initializers/ai-bot-replies.js
- config/settings.yml
- spec/system/ai_bot/ai_bot_helper_spec.rb
Previous to this change we relied on client side settings to
determine if an end user has access to the ai bot.
This meant that if a user was not aware they are a member of a
group (as it is with restricted visibility ones) they would not
see the bot button.
All checking has now moved to the server side, and tests were
added to cover.
> FIX: ai_bot_allowed_groups now works with restricted visibility

- lib/modules/ai_bot/bot.rb
- spec/lib/modules/ai_bot/anthropic_bot_spec.rb
Previous to this change we would keep completing and throw away
result
> FIX: cut completion short after function call is found

- spec/system/ai_helper/ai_composer_helper_spec.rb
- spec/system/page_objects/components/ai_suggestion_dropdown.rb
This PR fixes a flaky spec for the category suggester dropdown.
Previously, the spec looked for category by its value attribute and compared the `data-name` to be the same as the suggested name. However, when the Uncategorized category is present and used, it returns `1` for `data-name`. So this spec, ensures that the fabricated category is always used rather than allowing Uncategorized to be used.
> FIX: Flaky spec

- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.hbs
This PR adds consistency by changing the AI helper toggle to use `discourse-sparkles` icon instead of FontAwesome's `magic` icon.
> UX: Change AI Helper toggle icon to sparkles

- assets/javascripts/discourse/connectors/full-page-search-below-search-header/semantic-search.js
- lib/modules/embeddings/semantic_search.rb
Also fixes a bug in the UI where we displaying a no results message before searching.
> FIX: Invalidate semantic search cache entries when hyde or embedding model changes

- spec/system/ai_helper/ai_composer_helper_spec.rb
- spec/system/page_objects/modals/ai_helper.rb
An older spec for AI Helper modal in `ai_composer_helper_spec` has been flaky lately. This PR fixes that by ensuring the content has been generated before trying to click the save button.
> FIX: Flaky spec in AI Helper modal

- assets/javascripts/discourse/components/ai-suggestion-dropdown.gjs
- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
- spec/system/ai_helper/ai_composer_helper_spec.rb
- spec/system/page_objects/components/ai_suggestion_dropdown.rb
This PR shows the suggest title button only when sufficient content is present in the composer
This PR also makes some improvements to `ai-suggestion-dropdown`'s code quality.
https://github.com/discourse/discourse-ai/assets/30090424/879e7b72-1f6c-4a09-9229-f14411bc1712
> UX: Show suggestion buttons only if sufficient content is present

- assets/javascripts/discourse/components/ai-suggestion-dropdown.gjs
- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
**This PR prevents input text from being covered by the suggestion button.** 
This PR also removes the injected site service as category data is already present via the composer service.
> UX: Prevent input text from covering suggestion button

- lib/modules/ai_bot/commands/read_command.rb
- spec/lib/modules/ai_bot/commands/read_command_spec.rb
Note, we perform permission checks on tag list against anon
to ensure we do not disclose information about private tags
to the llm which could get extracted.
> FEATURE: add tags and categories to read context

- lib/modules/ai_bot/commands/search_command.rb
- spec/lib/modules/ai_bot/commands/read_command_spec.rb
- spec/lib/modules/ai_bot/commands/search_command_spec.rb
Previous to this we just included title/body.. tags and category
structure can be very critical for decision making.
> FEATURE: include tag and category context in search

- assets/javascripts/discourse/connectors/full-page-search-below-search-header/semantic-search.hbs
I thought this wasn't neccessary and we could safely rely on the appEvent during the initial search. It only fires if #searchEnabled is true, meaning the search term is valid.
> FIX: Trigger initial semantic search.

- assets/javascripts/discourse/connectors/after-composer-category-input/ai-category-suggestion.gjs
- assets/javascripts/discourse/connectors/after-composer-tag-input/ai-tag-suggestion.gjs
- assets/javascripts/discourse/connectors/after-composer-title-input/ai-title-suggestion.gjs
- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
- assets/javascripts/discourse/lib/show-ai-helper.js
- spec/system/ai_helper/ai_composer_helper_spec.rb
The AI suggestion buttons should conditionally be rendered based on the same logic we use for the composer AI helper context menu. This PR fixes that by sharing the logic and using it across each button's `shouldRender()` method. This PR also adds some system specs so this issue does not arise again in the future.
> FIX: Conditionally render AI suggestion buttons

- config/locales/server.en.yml
- lib/modules/ai_bot/bot.rb
- lib/modules/ai_bot/commands/search_command.rb
- lib/modules/ai_bot/open_ai_bot.rb
- lib/modules/ai_bot/personas/persona.rb
- lib/shared/inference/function_list.rb
- spec/lib/modules/ai_bot/bot_spec.rb
- spec/lib/modules/ai_bot/personas/persona_spec.rb
This is a collection of small fixes
- Display "Searching for: ..." while searching instead of showing found 0 results.
- Only allow 5 commands in lang chain - 6 feels like too much
- On the 5th command stop informing the engine about functions, so it is forced to complete
- Add another 30 tokens of buffer and explain why
- Typo in command prompt
> FIX: Made bot more robust

- lib/modules/ai_bot/bot.rb
- lib/shared/inference/function_list.rb
- spec/lib/modules/ai_bot/bot_spec.rb
Previous to this change where a command was issued by the LLM it
could hallucinate a continuation eg:
```
This is what tags are
!tags
some nonsense here
```
This change introduces safeguards so `some nonsense here` does not
creep in to the prompt history, poisoning the llm results
This in effect grounds the llm a lot better and results in the llm
forgetting less about results.
The change only impacts Claude at the moment, but will also improve
stuff for llama 2 in future.
Also, this makes it significantly easier to test the bot framework
without an llm cause we avoid a whole bunch of complex stubbing
> FIX: properly truncate !command prompts

- config/locales/server.en.yml
- config/settings.yml
- lib/modules/ai_bot/entry_point.rb
- lib/modules/ai_bot/personas/creative.rb
- lib/modules/ai_bot/personas/persona.rb
- spec/lib/modules/ai_bot/personas/persona_spec.rb
This adds a new creative persona that has access to the underlying
model and no external integrations.
It allows people to use Claude/GPT models in a Discourse agnostic
way.
> FEATURE: Add creative persona

- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
- spec/system/ai_helper/ai_composer_helper_spec.rb
This PR takes care of two things for the AI helper context menu:
1. `FIX` AI Helper context menu should work in Safari macOS
2. `IMPROVE` Trigger the context menu only if selected text is greater than a minimum character limit of 3
> DEV: Improvements to AI helper context menu

- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.hbs
- spec/system/ai_helper/ai_composer_helper_spec.rb
- spec/system/page_objects/components/ai_helper_context_menu.rb
This PR uses a `disabled` state for the custom prompt button when there is no input text **instead** of hiding and showing the button. This is better because it prevents jumpiness and width changes.
> UX: Use disable/enable state for custom prompt button

- config/settings.yml
- lib/shared/inference/amazon_bedrock_inference.rb
- lib/shared/inference/anthropic_completions.rb
- plugin.rb
If a module LLM model is set to claude-2 **and** the `ai_bedrock` variables are all present we will use AWS Bedrock instead of Antrhopic own APIs.
This is quite hacky, but will allow us to test the waters with AWS Bedrock early access with every module.
This situation of "same module, completely different API" is quite a bit far from what we had in the OpenAI/Azure separation, so it's more food for thought for when we start working on the LLM abstraction layer soon this year.
> FEATURE: Allow Anthropic inference via AWS Bedrock

- lib/discourse_automation/llm_triage.rb
- lib/shared/inference/openai_completions.rb
- spec/lib/discourse_automation/llm_triage_spec.rb
- spec/shared/inference/openai_completions_spec.rb
llm_triage supported claude 2 in triage, this implements it
OpenAI rate limits frequently, this introduces some exponential
backoff (3 attempts - 3 seconds, 9 and 27)
Also reduces temp of classifiers so they have consistent behavior
> FEATURE: Claude based scanning and OpenAI retries

- config/locales/server.en.yml
- config/settings.yml
- lib/shared/inference/openai_completions.rb
- spec/shared/inference/openai_completions_spec.rb
Per: https://platform.openai.com/docs/api-reference/authentication
There is an organization option which is useful for large orgs
> For users who belong to multiple organizations, you can pass a header to specify which organization is used for an API request. Usage from these API requests will count against the specified organization's subscription quota.
> FEATURE: support OpenAI-Organization header

- assets/javascripts/discourse/components/modal/diff-modal.gjs
- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.hbs
This PR changes the behaviour of the cancel button in the diff modal. Previously the cancel button would simply close the modal. As [requested on Meta](https://meta.discourse.org/t/proofread-text-feature-view-changes-what-does-the-cancel-button-do/280715/3?u=keegan), this PR changes it so that the cancel button is replaced with a revert button, so that the confirm/revert actions can be taken directly from the modal.
> DEV: Add revert button in diff modal

- lib/modules/ai_bot/bot.rb
When the OP is the only post in the topic, we'll send a prompt without user content to the LLM, and the suggested title will make no sense.
> FIX: Include OP when building title suggestion prompt.

- .discourse-compatibility
Followup to e21405a600abb2b7e7ef0b8cc8598d16089fe117
> DEV: Fix .discourse-compatibility typo

- lib/modules/ai_bot/commands/google_command.rb
- spec/lib/modules/ai_bot/commands/google_command_spec.rb
Under certain cases, for example:
```
there is this japanese band called kirimi, tell me more about them, try searching 3 times and at least 2 times in japanese before answering.
```
Results come back with blank snippets. This adds protection so this
is allowed and code does not simply blow up.
> FIX: allow for blank fields in Google results

- assets/javascripts/discourse/connectors/after-d-editor/composer-open.hbs
- assets/javascripts/discourse/connectors/after-d-editor/composer-open.js
- assets/stylesheets/modules/ai-bot/common/bot-replies.scss
- db/fixtures/ai_bot/602_bot_users.rb
- lib/modules/ai_bot/entry_point.rb
- lib/modules/ai_bot/site_settings_extension.rb
- spec/lib/modules/ai_bot/anthropic_bot_spec.rb
- spec/lib/modules/ai_bot/bot_spec.rb
- spec/lib/modules/ai_bot/commands/command_spec.rb
- spec/lib/modules/ai_bot/commands/google_command_spec.rb
- spec/lib/modules/ai_bot/commands/image_command_spec.rb
- spec/lib/modules/ai_bot/commands/read_command_spec.rb
- spec/lib/modules/ai_bot/commands/search_command_spec.rb
- spec/lib/modules/ai_bot/commands/summarize_command_spec.rb
- spec/lib/modules/ai_bot/entry_point_spec.rb
- spec/lib/modules/ai_bot/jobs/regular/create_ai_reply_spec.rb
- spec/lib/modules/ai_bot/jobs/regular/update_ai_bot_pm_title_spec.rb
- spec/lib/modules/ai_bot/open_ai_bot_spec.rb
- spec/lib/modules/ai_bot/site_setting_extension_spec.rb
- spec/requests/ai_bot/bot_controller_spec.rb
Also fixes it so users without bot in header can send it messages.
Previous to this change we would seed all bots with database seeds.
This lead to lots of confusion for people who do not enable ai bot.
Instead:
1. We do not seed any bots **until** user enables the ai_bot_enabled setting
2. If it is disabled we will
a. If no messages were created by bot - delete it
b. Otherwise we will deactivate account
> FEATURE: defer creation of bot users

- db/fixtures/ai_helper/600_openai_completion_prompts.rb
There is no "Human" role in openai, the blank assistant is not
needed
> FIX: openai prompt was incorrect for explain

- lib/modules/ai_bot/commands/image_command.rb
- lib/shared/inference/stability_generator.rb
Previous to this change image generation did not work on multisite
There was a background thread generating the images and it was
getting site settings from the default site in the cluster
This also removes referer header which is not needed
> FIX: make stable diffusion multi site friendly

- config/locales/server.en.yml
- config/settings.yml
- lib/modules/embeddings/entry_point.rb
- lib/modules/embeddings/jobs/regular/generate_embeddings.rb
- lib/modules/embeddings/jobs/scheduled/embeddings_backfill.rb
- lib/modules/embeddings/strategies/truncation.rb
- lib/modules/embeddings/vector_representations/base.rb
- lib/tasks/modules/embeddings/database.rake
To ease the administrative burden of enabling the embeddings model, this change introduces automatic backfill when the setting is enabled. It also moves the topic visit embedding creation to a lower priority queue in sidekiq and adds an option to skip embedding computation and persistence when we match on the digest.
> FEATURE: Make embeddings turn-key

- lib/modules/ai_bot/commands/db_schema_command.rb
- lib/modules/ai_bot/personas/sql_helper.rb
- spec/lib/modules/ai_bot/commands/db_schema_command_spec.rb
This makes it harder to cut and paste
Also fine tune the prompt a bit.
> FIX: avoid semicolons at the end of queries for SQL Helper

- lib/modules/ai_bot/commands/image_command.rb
- spec/lib/modules/ai_bot/commands/image_command_spec.rb
Function calling will start hallucinating if you reshape results.
Previously we were morphing from:
`{ prompts: ["prompt 1", "prompt 2"] }`
to
`{ prompts: { prompt: "prompt 1", seed: 222}, { ... `
This meant that over a few call sequences function_call starts hallucinating an incorrect shape.
This change grounds us even on GPT-3.5
> FIX: keep parity of shape for image command

- assets/javascripts/discourse/components/ai-suggestion-dropdown.gjs
- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
**This PR makes some updates to the AI suggestion button and AI suggestion dropdown.**
In particular:
- Removes the usage of `:has()` for targeting elements when AI suggestions are showing. Although this currently works in most major browsers, it is behind a feature flag still in Firefox, so many will be unable to see the visual changes made based on `has()` until Firefox 121 where it becomes enabled by default. Till then, we will avoid the usage of `has()`
- Add a class to `.composer-fields` element called `.showing-ai-suggestions` which can be used to make changes conditional on whether the AI suggestion buttons are showing
- Adds class to `.category-input` for when AI suggestion menu is being shown so it can easily be relatively positioned.
> DEV: Add wrapping classes and remove `has()` usage

- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
This PR addresses the visual bug where the suggestion button wraps on any screen size.
Before:
After:
> UX: prevent suggestion button from wrapping

- config/locales/server.en.yml
- lib/modules/sentiment/entry_point.rb
- spec/lib/modules/sentiment/entry_point_spec.rb
This PR aims to clarify sentiment reports by replacing averages with a count of posts that have one of their values above a threshold (60), meaning we have some level of confidence they are, in fact, positive or negative.
Same thing happen with post emotions, with the difference that a post can have multiple values above it (30). Additionally, we dropped the "Neutral" axis.
We also reworded the tooltip next to each report title, and added an early return to signal we have no data available instead of displaying an empty chart.
> FIX: Changes to the sentiment reports.

- app/models/ai_persona.rb
- db/migrate/20231109011155_create_ai_personas.rb
- lib/modules/ai_bot/bot.rb
- lib/modules/ai_bot/entry_point.rb
- lib/modules/ai_bot/personas/persona.rb
- spec/lib/modules/ai_bot/personas/persona_spec.rb
- spec/models/ai_persona_spec.rb
- New AiPersona model which can store custom personas
- Persona are restricted via group security
- They can contain custom system messages
- They can support a list of commands optionally
To avoid expensive DB calls in the serializer a Multisite
friendly Hash was introduced (which can be expired on transaction commit)
This means we can safely cache the persona classes and have very low
load time impact
> FEATURE: basic infrastructure for custom personas

- assets/javascripts/discourse/components/reviewable-ai-chat-message.js
- spec/system/toxicity/reviewable_ai_chat_message_spec.rb
Trying to hydrate using the store will fail. We need to use the model create function instead.
> FIX: ChatChannel no longer inherits from RestModel.

- assets/javascripts/discourse/connectors/post-text-buttons/ai-helper-options-menu.gjs
- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
- config/locales/client.en.yml
This PR adds a copy button to the generated suggestion in the post helper. This allows you to easily copy the suggestion content to your clipboard.
https://github.com/discourse/discourse-ai/assets/30090424/21aec8c0-b695-4bd7-94fd-a409aaf4aa23
> UX: Add copy button to generated suggestion

- assets/javascripts/discourse/connectors/full-page-search-below-search-header/semantic-search.gjs
- assets/stylesheets/modules/embeddings/common/semantic-search.scss
**This PR fixes an issue where AI results are not clickable.** 
This was due to mapping the original `model.posts` object to add `generatedByAI` attribute which was overwriting the `EmberObject` with a plain JS object causing attributes such as `url` to be removed. Instead we update it to simply add the attribute to the `EmberObject`.
No specs added as specs are still `todo` for after LLM abstraction. However, I've made a personal note to include testing topic url click on spec.
**This PR also applies some smaller fixes related to AI Semantic search:**
- It removes the `background: var(--tertiary-very-low);` that is applied on all AI search results. This makes the UI look cleaner especially when there are only AI results, making the background feel unnecessarily repetitive.
- It disables …
> FIX: Un-clickable AI Results

- assets/javascripts/discourse/connectors/composer-fields/persona-selector.gjs
- plugin.rb
- spec/lib/modules/embeddings/jobs/generate_embeddings_spec.rb
- spec/lib/modules/embeddings/semantic_search_spec.rb
- spec/lib/modules/embeddings/vector_representations/all_mpnet_base_v2_spec.rb
- spec/lib/modules/embeddings/vector_representations/multilingual_e5_large_spec.rb
- spec/lib/modules/embeddings/vector_representations/text_embedding_ada_002_spec.rb
- spec/system/ai_bot/persona_spec.rb
- spec/system/embeddings/semantic_search_spec.rb
People tend to keep to 1 persona when working with the bot,
this adds local browser memory for the last persona you interacted
with so you do not need to select it over and over again.
This is per browser, not per user memory.
Also... clean up tests so they do not need to require stubs which
were breaking the build
> FEATURE: remember previously selected persona

- assets/javascripts/discourse/connectors/full-page-search-below-search-header/semantic-search.gjs
- assets/stylesheets/modules/embeddings/common/semantic-search.scss
**This PR fixes an issue where more results (page 2 and on) were not appearing on scroll.**
Previously we were using CSS to visually hide AI results from the page by default. This resulted in the end of page results never being hit when scrolling to the bottom, and thereby preventing `loadMore()` from being called to render additional results.
In this PR we update the implementation of AI results so the results are physically added and removed from the DOM when toggled, allowing for `loadMore()` to be accurately called.
_Again no specs here for now till we update the LLM abstraction._
> FIX: more results not appearing on scroll

- assets/javascripts/discourse/connectors/full-page-search-below-search-header/semantic-search.gjs
Previously, the AI HyDE search was only being performed when the search button was pressed. However, this resulted in AI results never working if you search from the regular search menu and press the advanced button. It also would not work previously if you visit a search url directly with query params such as: `/search?expanded=true&q=testing`
**This PR** checks if a search term is present before deciding to perform the HyDE search or not. If there is a query param with a search term, the AI search will be run automatically. If not, it will wait for the <kbd>:mag: Search</kbd> button to be pressed before running the AI search.
This PR also fixes some linting issues with the `semantic-search.gjs` file
https://github.com/discourse/discourse-ai/assets/30090424/8863b999-db68-4516-b453-db77085 …
> DEV: Run AI search before submit if query params present

- lib/modules/embeddings/semantic_search.rb
This PR fixes an issue where AI semantic search will return a `500` error when only filters are passed and no search term is present. We resolve this by explicitly checking for the presence of a search term and ensuring it is the minimum required length, otherwise we return an empty list.
> FIX: Error 500 from search with only filters

- lib/modules/ai_bot/anthropic_bot.rb
- lib/modules/ai_bot/bot.rb
- lib/modules/ai_bot/commands/command.rb
- lib/modules/ai_bot/open_ai_bot.rb
- lib/modules/ai_bot/personas/general.rb
- lib/shared/inference/function_list.rb
- spec/lib/modules/ai_bot/anthropic_bot_spec.rb
- spec/lib/modules/ai_bot/bot_spec.rb
- spec/lib/modules/ai_bot/jobs/regular/create_ai_reply_spec.rb
- spec/lib/modules/ai_bot/personas/persona_spec.rb
- spec/shared/inference/function_list_spec.rb
Previous to this changeset we used a custom system for tools/command
support for Anthropic.
We defined commands by using !command as a signal to execute it
Following Anthropic Claude 2.1, there is an official supported syntax (beta)
for tools execution.
eg:
```
+      <function_calls>
+      <invoke>
+      <tool_name>image</tool_name>
+      <parameters>
+      <prompts>
+      [
+      "an oil painting",
+      "a cute fluffy orange",
+      "3 apple's",
+      "a cat"
+      ]
+      </prompts>
+      </parameters>
+      </invoke>
+      </function_calls>
```
This implements the spec per Anthropic, it should be stable enough
to also work on other LLMs.
Keep in mind that OpenAI is not impacted here at all, as it has its
own custom system for function calls.
Additionally:
- Fixes the …
> FIX: implement tools framework for Anthropic

- assets/javascripts/discourse/connectors/composer-fields/persona-selector.gjs
- config/locales/server.en.yml
- lib/modules/ai_bot/commands/dall_e_command.rb
- lib/modules/ai_bot/entry_point.rb
- lib/modules/ai_bot/personas/dall_e_3.rb
- lib/modules/ai_bot/personas/persona.rb
- lib/shared/inference/openai_image_generator.rb
- plugin.rb
- spec/lib/modules/ai_bot/commands/dall_e_command_spec.rb
- spec/system/ai_bot/persona_spec.rb
This persona generates images using DALL-E-3 API and is enabled
by default
Keep in mind that we are still waiting on seeds/gen_id so we can
not retain style consistently between turns.
This will change as soon as API params are added to Open AI. 
Also: fixes a minor glitch in the persona selector
> FEATURE: DALL-E-3 persona for image generation

- assets/javascripts/discourse/connectors/after-search-result-entry/search-result-decoration.gjs
- config/locales/client.en.yml
This PR adds the `title` attribute to the sparkles icon on AI generated search results.
> A11Y: Add title attribute to sparkles icon for AI search results

- lib/completions/endpoints/base.rb
We already log the request failure when we raise the exception.
> DEV: Don't attempt to update log if completion request fails.

- app/models/completion_prompt.rb
- db/fixtures/ai_helper/603_completion_prompts.rb
- db/post_migrate/20231128151234_recreate_generate_titles_prompt.rb
- lib/completions/endpoints/base.rb
- lib/modules/ai_helper/assistant.rb
- spec/lib/modules/ai_helper/assistant_spec.rb
- spec/lib/modules/ai_helper/chat_thread_titler_spec.rb
- spec/system/ai_helper/ai_composer_helper_spec.rb
We must ensure we can isolate titles, and the models sometimes ignore the example we give them.
Additionally, anons can generate HyDE posts, so we need to check if user is nil when attempting to log requests.
> FIX: Use XML tags in generate_titles prompt.

- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
The CSS for categories was fine, but it's structured a little differently for tags... 
`.mini-tag-chooser .select-kit` needs to be `.mini-tag-chooser.select-kit` — also switched to `em`s so this scales with font-size changes. 
Before: 
After:
> FIX: adjust tag composer input to avoid wrapping

- assets/javascripts/discourse/components/ai-command-selector.js
- spec/system/ai_bot/persona_spec.rb
When moving ai-command-selector from gjs to js the underlying
behavior changed, this corrects it and adds a test case.
> FIX: command selector behavior stopped working

- assets/javascripts/discourse/connectors/user-summary-stat/sentiment.hbs
- assets/javascripts/discourse/connectors/user-summary-stat/sentiment.js
- config/locales/client.en.yml
- config/locales/server.en.yml
- config/settings.yml
- lib/sentiment/sentiment_classification.rb
- lib/tasks/modules/sentiment/backfill.rake
- plugin.rb
This introduces a new user stat in a user profile summary page.
It will show either neutral/positive/negative according to the dominant
sentiment in the user last interactions.
The user-stat widget is only rendered for staff.
> FEATURE: User sentiment on profile summary page

- lib/ai_bot/commands/read_command.rb
- lib/ai_bot/commands/search_command.rb
- lib/ai_bot/commands/summarize_command.rb
- spec/lib/modules/embeddings/semantic_search_spec.rb
- spec/lib/modules/toxicity/entry_point_spec.rb
- spec/models/reviewable_ai_post_spec.rb
- spec/serializers/ai_chat_channel_serializer_spec.rb
c.f. discourse/discourse@de983796e1b66aa2ab039a4fb6e32cec8a65a098
There will soon be additional login_required checks
for Guardian, and the intent of many checks by automated
systems is better fulfilled by using BasicUser, which
simulates a logged in TL0 forum user, rather than an
anon user.
> FIX: Use Guardian.basic_user instead of new (anon)

- lib/ai_bot/commands/read_command.rb
- lib/ai_bot/commands/search_command.rb
- lib/ai_bot/commands/summarize_command.rb
- spec/lib/modules/embeddings/semantic_search_spec.rb
- spec/lib/modules/toxicity/entry_point_spec.rb
- spec/models/reviewable_ai_post_spec.rb
- spec/serializers/ai_chat_channel_serializer_spec.rb
This reverts commit a3a1285dc5f839b7b83649113b0b2c700e0fde77.
c.f. https://github.com/discourse/discourse/pull/24742
> Revert "FIX: Use Guardian.basic_user instead of new (anon) (#332)"

- config/locales/client.en.yml
- config/locales/server.en.yml
- config/settings.yml
- lib/ai_bot/entry_point.rb
- lib/ai_bot/open_ai_bot.rb
- lib/inference/open_ai_completions.rb
- spec/shared/inference/openai_completions_spec.rb
Keep in mind:
- GPT-4 is only going to be fully released next year - so this hardcodes preview model for now
- Fixes streaming bugs which became a big problem with GPT-4 turbo
- Adds Azure endpoing for turbo as well
> FEATURE: implement GPT-4 turbo support

- assets/javascripts/initializers/ai-bot-replies.js
- config/locales/server.en.yml
- lib/ai_bot/commands/search_command.rb
- spec/lib/modules/ai_bot/commands/search_command_spec.rb
- spec/requests/admin/ai_personas_controller_spec.rb
We were limiting to 20 results unconditionally cause we had to make
sure search always fit in an 8k context window.
Models such as GPT 3.5 Turbo (16k) and GPT 4 Turbo / Claude 2.1 (over 150k)
allow us to return a lot more results.
This means we have a much richer understanding cause context is far
larger.
This also allows a persona to tweak this number, in some cases admin
may want to be conservative and save on tokens by limiting results
This also tweaks the `limit` param which GPT-4 liked to set to tell
model only to use it when it needs to (and describes default behavior)
> FEATURE: scale up result count for search depending on model

- lib/completions/endpoints/aws_bedrock.rb
- spec/lib/completions/endpoints/aws_bedrock_spec.rb
Reverts discourse/discourse-ai#352
> Revert "FIX: Recover from Bedrock returning invalid base64 payloads during streaming"

- spec/lib/modules/embeddings/entry_point_spec.rb
- spec/lib/modules/nsfw/entry_point_spec.rb
- spec/lib/modules/sentiment/entry_point_spec.rb
- spec/lib/modules/toxicity/entry_point_spec.rb
In https://github.com/discourse/discourse/pull/24740, `min_trust_to_create_topic` site setting was replaced by `create_topic_allowed_groups`. This PR replaces the former, deprecated one, with the latter.
> DEV: Replace deprecated min_trust_to_create_post

- assets/javascripts/discourse/components/ai-helper-custom-prompt.gjs
- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.hbs
- assets/javascripts/discourse/connectors/post-text-buttons/ai-helper-options-menu.gjs
- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
- lib/ai_helper/assistant.rb
This PR adds the custom prompt feature to outside composer AI post helper:
https://github.com/discourse/discourse-ai/assets/30090424/d1092354-8795-478b-b599-6aa65dea94f6
Still some issues with system specs for AI translate/explain and other suggest options, will address in separate PR.
> FEATURE: Add custom prompts to post helper options

- app/controllers/discourse_ai/ai_helper/assistant_controller.rb
- assets/javascripts/discourse/connectors/fast-edit-footer-after/ai-edit-suggestion-button.gjs
- assets/javascripts/discourse/connectors/post-text-buttons/ai-helper-options-menu.gjs
- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
- config/locales/client.en.yml
- lib/ai_helper/assistant.rb
- spec/requests/ai_helper/assistant_controller_spec.rb
- spec/system/ai_helper/ai_post_helper_spec.rb
**This PR:**
1. Adds _Proofread_ option to post AI helper menu.
2. Automatically opens `FastEdit` with proofread suggestion
3. Adds a <kbd>:sparkles: Suggest Edit</kbd> buton to `FastEdit` for triggering suggestions after clicking through <kbd>:pencil: Edit</kbd> instead of <kbd>:sparkles: Ask AI</kbd> which allows for a direct way to proofread.
The PR relies on changes in core found in the following PR: https://github.com/discourse/discourse/pull/24909
https://github.com/discourse/discourse-ai/assets/30090424/b06aeb14-a537-43f0-a165-46332dc23ee5
https://github.com/discourse/discourse-ai/assets/30090424/ddef1b3d-d83c-4685-9a6d-53423e7ed502
> FEATURE: Proofread with post AI helper

- assets/javascripts/discourse/connectors/post-text-buttons/ai-helper-options-menu.gjs
Previously, when users asked the AI to generate responses in languages like Arabic or Hebrew (RTL languages), the answer would follow whatever direction the site was set to. For example, if the site was set to LTR, an answer in an RTL language would be displayed in LTR mode, making the answer very hard to read.
This PR introduces the [dir="auto"](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir) attribute to the element containing the AI answer. This improvement makes the browser automatically detect the direction of the content and set the appropriate direction, ensuring that the AI answer aligns correctly with the language's reading direction regardless of the site's overall mode.
Before:
After:
Internal topic: t/117852/10.
> UX: Automatically detect text direction for AI generated text

- assets/javascripts/discourse/connectors/fast-edit-footer-after/ai-edit-suggestion-button.gjs
This PR hides the <kbd>:sparkles: Suggest Edit</kbd> button from the fast edit window when triggered from Ask AI -> Proofread, and instead only shows the suggest edit button if it was triggered directly from the <kbd>:pencil: Edit</kbd> button.
> UX: Hide suggest edit button in fast edit when triggering from AI

- lib/completions/endpoints/aws_bedrock.rb
Bug introduced while migrating to the new LLM service. Default max tokens to sample should be 2k, not 20. As a result, bedrock complains input is too long.
> FIX: Bedrock was complaining  input was too long

- lib/completions/dialects/chat_gpt.rb
- lib/completions/dialects/claude.rb
- lib/completions/dialects/dialect.rb
- lib/completions/dialects/gemini.rb
- lib/completions/dialects/llama2_classic.rb
- lib/completions/dialects/orca_style.rb
- lib/completions/endpoints/anthropic.rb
- lib/completions/endpoints/aws_bedrock.rb
- lib/completions/endpoints/base.rb
- lib/completions/endpoints/canned_response.rb
- lib/completions/endpoints/gemini.rb
- lib/completions/endpoints/hugging_face.rb
- lib/completions/endpoints/open_ai.rb
- lib/completions/llm.rb
- spec/lib/completions/dialects/chat_gpt_spec.rb
- spec/lib/completions/dialects/claude_spec.rb
- spec/lib/completions/dialects/gemini_spec.rb
- spec/lib/completions/dialects/llama2_classic_spec.rb
- spec/lib/completions/dialects/orca_style_spec.rb
- spec/lib/completions/endpoints/anthropic_spec.rb
- spec/lib/completions/endpoints/aws_bedrock_spec.rb
- spec/lib/completions/endpoints/endpoint_examples.rb
- spec/lib/completions/endpoints/gemini_spec.rb
- spec/lib/completions/endpoints/hugging_face_spec.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
- spec/lib/completions/llm_spec.rb
- spec/requests/ai_helper/assistant_controller_spec.rb
This PR adds tool support to available LLMs. We'll buffer tool invocations and return them instead of making users of this service parse the response.
It also adds support for conversation context in the generic prompt. It includes bot messages, user messages, and tool invocations, which we'll trim to make sure it doesn't exceed the prompt limit, then translate them to the correct dialect.
Finally, It adds some buffering when reading chunks to handle cases when streaming is extremely slow.:M
> DEV: Tool support for the LLM service.

- lib/ai_helper/assistant.rb
- lib/ai_helper/entry_point.rb
Fixes illustrate post option not appearing correctly in UI. It should also only appear in composer not in posts helper.
> FIX: Illustrate post icon and translation not appearing correctly

- lib/completions/endpoints/base.rb
- lib/inference/open_ai_completions.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
- spec/shared/inference/openai_completions_spec.rb
Previously endpoint/base would `+=` decoded_chunk to leftover
This could lead to cases where the leftover buffer had duplicate
previously processed data
Fix ensures we properly skip previously decoded data.
> FIX: under certain conditions we would get duplicate data from llm

- assets/javascripts/discourse/components/modal/thumbnail-suggestions.gjs
- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.hbs
- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
This PR fixes a bug where pressing <kbd>Ctrl</kbd> + <kbd>Z</kbd> to undo a piece of text that is written after an AI command has been done results in the text returning to how it was before the AI command took place.
This was done by leaning on `document.execCommand()` to insert text instead of dynamically setting the composer's reply property.
> FIX: Undo issue

- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
In Chromium browsers, the AI context menu is still appearing despite selected text being deleted. This is likely due to the workaround set in place for the Firefox bug (https://github.com/discourse/discourse-ai/pull/154).
In this PR we check for a selection and backspace to automatically close the context menu.
> FIX: Context menu should not appear if selected text is deleted

- lib/automation/report_context_generator.rb
- spec/lib/modules/automation/report_context_generator_spec.rb
Generally non visible topics are not that interesting, do not add
this noise to the report context
> FIX: exclude non visible topics from report context

- config/locales/client.en.yml
- discourse_automation/llm_report.rb
- lib/automation/report_runner.rb
- spec/lib/discourse_automation/llm_report_spec.rb
This makes the reporting far more flexible cause it can target a
far wider audience by pointing it at a topic in a secure category
or an existing PM
> FEATURE: allow sending AI based report to a topic

- assets/javascripts/discourse/connectors/post-text-buttons/ai-helper-options-menu.gjs
This PR moves the placement of the FloatKit menu to be positioned to `"bottom"` when <kbd>:sparkles: Ask AI</kbd> is pressed. This allows for a better UX when the streamed explain text is shown so that the menu expands vertically.
https://github.com/discourse/discourse-ai/assets/30090424/d772d02e-c3ac-453f-ae86-4f669e304908
https://github.com/discourse/discourse-ai/assets/30090424/d197e02a-cbca-4e98-996c-48a83886aca2
> UX: Menu placement bottom for AI

- assets/javascripts/discourse/connectors/full-page-search-below-search-header/semantic-search.gjs
- config/locales/client.en.yml
Sometimes when you make a search and erase the text and begin writing a new search query (before pressing search), the label changes to "Sorry, no our AI search found no matching topics". In this scenario the label is incorrect. Sometimes this label also gets stuck on mobile.
Instead, in this PR we add a new label to account for such a situation. The label instead will show here: "Press 'Search' to begin looking for new results with AI"
> FIX: Prevent no results label from showing when untrue

- app/views/list/related_topics.html.erb
Related: https://github.com/discourse/discourse-automation/pull/243
Currently we're seeing 500s when related_topics are getting rendered. We should get the topic's category rather than on the array.
```
ActionView::Template::Error (undefined method `category' for [#<Topic id ... ]
```
Patching this quickly, will add a test soon. 💥
> FIX: Get topic's category instead of array's

- assets/javascripts/discourse/lib/copy-conversation.js
Chrome and Firefox work with standard clipboardCopy, but since
we are making an ajax call Safari fails cause there is too much
delay detected.
To avoid this issue we trade in promises which are acceptable and
work in iOS.
> FIX: use async versions of clipboardCopy

- config/locales/client.en.yml
Saying "to clipboard" is wordy and obsolete. 
Shortening it to "Conversation copied" is also more consistent with the "Link copied" component.
> UX: copy change

- lib/ai_helper/assistant.rb
- spec/lib/modules/ai_helper/assistant_spec.rb
- spec/requests/ai_helper/assistant_controller_spec.rb
Following the feature https://github.com/discourse/discourse-ai/pull/367 adding post illustrations. The **Illustrate Post** option will always result in an error if stable diffusion was not enabled. This PR fixes the issue by only allowing the AI helper option to be shown if the site setting `ai_stability_api_key` is present.
> FIX: Show illustrate post only if stability API key present

- app/models/reviewable_ai_chat_message.rb
- app/serializers/reviewable_ai_chat_message_serializer.rb
- assets/javascripts/discourse/components/reviewable-ai-chat-message.hbs
- assets/javascripts/discourse/components/reviewable-ai-chat-message.js
- spec/system/toxicity/reviewable_ai_chat_message_spec.rb
After this PR if, for some reason, a flagged chat message is not found or has been hard deleted, it does not throw an error and allows the flag to be ignored from the UI
> FIX: 500 error when reviewable has a missing message

- config/locales/server.en.yml
- lib/ai_helper/painter.rb
This PR adds attribution ("_Image by Stable Diffusion XL_") to images generated by stable diffusion using the AI helper's illustrate post feature.
This is an interim solution. In the future, we will also add AI generated caption along with this as well as support for Dall E as an option.
> UX: Add proper attribution to illustrate post images

- app/controllers/discourse_ai/ai_helper/assistant_controller.rb
- app/models/completion_prompt.rb
- db/fixtures/ai_helper/603_completion_prompts.rb
- db/migrate/20240104013944_add_params_to_completion_prompt.rb
- lib/ai_helper/assistant.rb
- lib/ai_helper/painter.rb
- lib/automation/llm_triage.rb
- lib/automation/report_runner.rb
- lib/completions/dialects/chat_gpt.rb
- lib/completions/dialects/mixtral.rb
- lib/completions/endpoints/anthropic.rb
- lib/completions/endpoints/aws_bedrock.rb
- lib/completions/endpoints/base.rb
- lib/completions/endpoints/canned_response.rb
- lib/completions/endpoints/gemini.rb
- lib/completions/endpoints/hugging_face.rb
- lib/completions/endpoints/open_ai.rb
- lib/completions/endpoints/vllm.rb
- lib/completions/llm.rb
- lib/embeddings/semantic_search.rb
- lib/summarization/strategies/fold_content.rb
- spec/lib/completions/dialects/mixtral_spec.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
- spec/lib/completions/llm_spec.rb
- spec/requests/ai_helper/assistant_controller_spec.rb
This PR introduces a new function on the generic llm called #generate
This will replace the implementation of completion!
#generate introduces a new way to pass temperature, max_tokens and stop_sequences
Then LLM implementers need to implement #normalize_model_params to
ensure the generic names match the LLM specific endpoint
This also adds temperature and stop_sequences to completion_prompts
this allows for much more robust completion prompts
> FIX: AI helper not working correctly with mixtral

- assets/javascripts/initializers/ai-bot-replies.js
- config/locales/client.en.yml
- config/settings.yml
- lib/ai_bot/bot.rb
- lib/ai_bot/entry_point.rb
- lib/ai_bot/playground.rb
- lib/completions/dialects/chat_gpt.rb
- lib/completions/dialects/claude.rb
- lib/completions/dialects/dialect.rb
- lib/completions/dialects/gemini.rb
- lib/completions/dialects/llama2_classic.rb
- lib/completions/dialects/mixtral.rb
- lib/completions/dialects/orca_style.rb
- lib/completions/endpoints/base.rb
- lib/completions/endpoints/gemini.rb
- lib/completions/llm.rb
- spec/lib/completions/dialects/gemini_spec.rb
- spec/lib/completions/endpoints/gemini_spec.rb
- spec/lib/modules/ai_bot/bot_spec.rb
- spec/lib/modules/ai_bot/playground_spec.rb
It also corrects the syntax around tool support, which was wrong.
Gemini doesn't want us to include messages about previous tool invocations, so I had to shuffle around some code to send the response it generated from those invocations instead. For this, I created the "multi_turn" context, which bundles all the context involved in the interaction.
> FEATURE: AI Bot Gemini support.

- config/locales/server.en.yml
- config/settings.yml
- lib/ai_helper/assistant.rb
- lib/ai_helper/painter.rb
- spec/lib/modules/ai_helper/assistant_spec.rb
- spec/lib/modules/ai_helper/painter_spec.rb
- spec/requests/ai_helper/assistant_controller_spec.rb
This PR adds support for using `dall_e_3` as a model when using the AI helper's illustrate post feature.
It also updates the illustrate post feature to be dependant on a plugin setting: `ai_helper_illustrate_post_model` which offers three options now:
- `stable_diffusion_xl`
- `dall_e_3`
- `disabled`
By default illustrate post is `disabled`.
Currently `dall-e-3` only allows for [`n=1` images](https://platform.openai.com/docs/api-reference/images/create) to be generated, however, we can update this to be 4 images once it's supported.
> FEATURE: Add DallE support to AI helper's illustrate post

- lib/ai_bot/bot.rb
- lib/ai_bot/playground.rb
- lib/completions/dialects/gemini.rb
- spec/lib/completions/dialects/gemini_spec.rb
- spec/lib/modules/ai_bot/playground_spec.rb
- spec/lib/modules/ai_bot/tools/dall_e_spec.rb
We need to be careful adding <details> into context of conversations
it can cause LLMs to hallucinate results
> FIX: don't include <details> in context

- lib/completions/dialects/chat_gpt.rb
- spec/lib/completions/dialects/chat_gpt_spec.rb
We thought Azure's latest API version didn't have tool support yet, but I didn't understand it was complaining about a required field in the tool call message.
> FIX: Bring back Azure support.

- config/settings.yml
- lib/completions/endpoints/vllm.rb
- lib/embeddings/vector_representations/all_mpnet_base_v2.rb
- lib/embeddings/vector_representations/base.rb
- lib/embeddings/vector_representations/bge_large_en.rb
- lib/embeddings/vector_representations/multilingual_e5_large.rb
- lib/inference/hugging_face_text_embeddings.rb
- lib/nsfw/classification.rb
- lib/sentiment/sentiment_classification.rb
- lib/summarization/strategies/truncate_content.rb
- lib/toxicity/toxicity_classification.rb
This allows admins to configure services with multiple backends using DNS SRV records. This PR also adds support for shared secret auth via headers for TEI and vLLM endpoints, so they are inline with the other ones.
> FEATURE: Support for SRV records for Discourse services

- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
This PR fixes an issue with the AI composer helper where the <kbd>Revert</kbd> and <kbd>Undo</kbd> buttons were not working in Firefox.
> FIX: Revert AI action not working in Firefox

- app/views/list/related_topics.html.erb
- lib/embeddings/entry_point.rb
- spec/requests/topic_spec.rb
Followup 2636efcd1bf6eaa0a6d0d868affb9d41d49bdda2,
whenever ruby code was changed locally this would break
module loading, giving an "uninitialized constant
DiscourseAi::Embeddings::EntryPoint::SemanticRelated" error.
> DEV: Fix SemanticRelated module load error

- config/settings.yml
- spec/lib/modules/ai_bot/tools/search_spec.rb
- spec/lib/modules/embeddings/jobs/generate_embeddings_spec.rb
- spec/lib/modules/embeddings/semantic_search_spec.rb
- spec/lib/modules/embeddings/semantic_topic_query_spec.rb
- spec/support/embeddings_generation_stubs.rb
bge-large-en via https://github.com/huggingface/text-embeddings-inference has both faster inference and better recall than our previous default
> FEATURE: Move the default embeddings model to bge-large-en

- lib/embeddings/vector_representations/base.rb
Fixes a regression from 140359c which caused we to set this globally based on post count, rendering the cost of an index scan on the topics table too high and making the planner, correctly, not use the index anymore.
Hopefully https://github.com/pgvector/pgvector/issues/235 lands soon.
> FIX: Set ivfflat.probes using topic count, not post count

- assets/javascripts/discourse/connectors/full-page-search-below-search-header/semantic-search.gjs
`onAppEvent("full-page-search:trigger-search")` is triggered at minimum two times when a search is queried, sometimes three. This was causing a HyDE search request multiple times likely resulting in reaching rate limits (especially on mobile).
This PR prevents HyDE from being called multiple times for a single query by checking if a search is currently in progress before calling `performHyDESearch()`
> DEV: Prevent HyDE search from being called multiple times

- lib/completions/dialects/chat_gpt.rb
- lib/completions/dialects/claude.rb
- lib/completions/dialects/dialect.rb
- lib/completions/prompt.rb
- spec/lib/completions/dialects/chat_gpt_spec.rb
- spec/lib/completions/dialects/claude_spec.rb
- spec/lib/completions/dialects/dialect_spec.rb
- spec/lib/completions/prompt_spec.rb
When you trim a prompt we never want to have a state where there
is a "tool" reply without a corresponding tool call, it makes no
sense
Also
- GPT-4-Turbo is 128k, fix that
- Claude was not preserving username in prompt
- We were throwing away unicode usernames instead of adding to
message
> FIX: scrub invalid prompts when truncating

- lib/ai_bot/tools/summarize.rb
- lib/automation/llm_triage.rb
- lib/completions/llm.rb
We were not validating input for generate leading to 2 tests not
failing correctly despite functionality being broken.
This ensures that input is validated,and in turn fixes the broken
specs
> FIX: always ensure `#generate` gets a valid input

- assets/stylesheets/modules/ai-bot/common/bot-replies.scss
This is a minor adjustment for the ai bot that makes the loading dot start its animation instantly if it's the only content available... this makes it feel less static if it takes a little longer to start streaming a reply 
once other content is added, it falls back to the behavior of waiting 3 seconds before animation (because animating while text is streaming is a bit odd)
> UX: start progress dot animation instantly if it's the only content

- lib/automation.rb
Bug report: https://meta.discourse.org/t/gpt-3-5-turbo-is-not-working-for-ai-periodical-reports/292858
> FIX: typo in Automation::AVAILABLE_MODELS

- assets/javascripts/discourse/connectors/full-page-search-below-search-header/semantic-search.gjs
This PR changes the behaviour so that errors when contacting the API during semantic search are no longer shown in a modal to the client.
> DEV: Not necessary to show modal with errors

- app/jobs/scheduled/embeddings_backfill.rb
- lib/embeddings/semantic_related.rb
- spec/jobs/scheduled/embeddings_backfill_spec.rb
- spec/lib/modules/embeddings/semantic_related_spec.rb
1. on failure we were queuing a job to generate embeddings, it had the wrong params. This is both fixed and covered in a test.
2. backfill embedding in the order of bumped_at, so newest content is embedded first, cover with a test
3. add a safeguard for hidden site setting that only allows batches of 50k in an embedding job run
Previously old embeddings were updated in a random order, this changes it so we update in a consistent order
> FIX: improve embedding generation

- app/jobs/scheduled/embeddings_backfill.rb
The idea is to increase the frequency so we can run with smaller batch sizes.
Big batches cause problems when running backups, so it's better to have shorter but
more frequent jobs.
> DEV: Increase embeddings backfill job frequency

- lib/completions/endpoints/aws_bedrock.rb
- lib/completions/endpoints/base.rb
When bedrock rate limits it returns a 200 BUT also returns a JSON
document with the error.
Previously we had no special case here so we complained about nil
New code properly logs the problem
> DEV: improve error bedrock error messages

- assets/javascripts/discourse/connectors/after-composer-category-input/ai-category-suggestion.gjs
- assets/javascripts/discourse/connectors/after-composer-tag-input/ai-tag-suggestion.gjs
- assets/javascripts/discourse/connectors/after-composer-title-input/ai-title-suggestion.gjs
- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
- assets/javascripts/discourse/lib/show-ai-helper.js
- config/locales/server.en.yml
- config/settings.yml
- spec/system/ai_helper/ai_composer_helper_spec.rb
This PR introduces a new plugin setting: `ai_helper_enabled_features` which allows for granular control over the composer AI helper's features. Admins can now select between showing AI helper's suggestion feature, context menu feature, or both.
> DEV: Add granular control for AI composer helper features

- db/post_migrate/20240207144910_fix_llm_backed_setting_defaults.rb
Previous migration never reach the case were we needed to keep the old default (with provider) because used the string as part of the condition.
This new migraiton fixes that case.
> FIX: Explicit check for empty string in compat migration

- lib/ai_helper/chat_thread_titler.rb
- spec/lib/modules/ai_helper/chat_thread_titler_spec.rb
- Fix quote removal when multi-line
- Use XML tags for better LLM output parsing
- Use stop_sequences for faster and less wasteful LLM calls
- Adds truncation as the last line of defense
> FIX: Better AI chat thread titles

- app/controllers/discourse_ai/admin/ai_personas_controller.rb
- app/jobs/regular/create_ai_reply.rb
- app/models/ai_persona.rb
- app/serializers/localized_ai_persona_serializer.rb
- assets/javascripts/discourse/admin-discourse-ai-personas-route-map.js
- assets/javascripts/discourse/admin/adapters/ai-persona.js
- assets/javascripts/discourse/admin/models/ai-persona.js
- assets/javascripts/discourse/components/ai-llm-selector.js
- assets/javascripts/discourse/components/ai-persona-editor.gjs
- assets/stylesheets/modules/ai-bot/common/ai-persona.scss
- config/locales/client.en.yml
- config/locales/server.en.yml
- config/routes.rb
- db/migrate/20240209044519_add_user_id_mentionable_default_llm_to_ai_personas.rb
- db/migrate/20240213051213_add_limits_to_ai_persona.rb
- lib/ai_bot/bot.rb
- lib/ai_bot/entry_point.rb
- lib/ai_bot/personas/persona.rb
- lib/ai_bot/playground.rb
- lib/ai_bot/site_settings_extension.rb
- lib/ai_bot/tools/random_picker.rb
- lib/completions/llm.rb
- spec/lib/modules/ai_bot/jobs/regular/create_ai_reply_spec.rb
- spec/lib/modules/ai_bot/playground_spec.rb
- spec/lib/modules/ai_bot/tools/random_picker_spec.rb
- spec/models/ai_persona_spec.rb
- spec/requests/admin/ai_personas_controller_spec.rb
- spec/system/ai_bot/persona_spec.rb
- test/javascripts/unit/models/ai-persona-test.js
This rather large PR adds support for the following: 
1. Personas are now **optionally** mentionable, meaning that you can mention them either from public topics or PMs
1. Mentioning from PMs helps "switch" persona mid conversation, meaning if you want to look up sites setting you can invoke the site setting bot, or if you want to generate an image you can invoke dall e
2. Mentioning outside of PMs allows you to inject a bot reply in a topic trivially
2. We also add the support for max_context_posts this allow you to limit the amount of context you feed in, which can help control costs
> FEATURE: mentionable personas and random picker tool, context limits

- assets/javascripts/discourse/connectors/after-d-editor/ai-helper-context-menu.js
- assets/javascripts/discourse/connectors/post-text-buttons/ai-helper-options-menu.gjs
- assets/javascripts/discourse/lib/show-ai-helper.js
- config/settings.yml
- lib/ai_bot/entry_point.rb
Affects the following settings:
ai_toxicity_groups_bypass
ai_helper_allowed_groups
ai_helper_custom_prompts_allowed_groups
post_ai_helper_allowed_groups
This turns off client: true for these group-based settings, because there is no guarantee that the current user gets all their group memberships serialized to the client. Better to check server-side first.
> DEV: Make more group-based settings client: false

- app/controllers/discourse_ai/ai_helper/assistant_controller.rb
- spec/requests/ai_helper/assistant_controller_spec.rb
Utilizes the check for secure upload permissions from core PR
https://github.com/discourse/discourse/pull/25758 and cleans up
controller codes and spec code to reuse existing code and better
reflect reality.
> DEV: Cleanup caption endpoint and account for secure uploads

- assets/javascripts/discourse/lib/copy-conversation.js
- assets/javascripts/initializers/ai-bot-replies.js
- lib/ai_bot/personas/discourse_helper.rb
- spec/system/ai_bot/share_spec.rb
Persona users are still bots, but we were not properly accounting
for it and share icon was not showing up.
This depends on a core change that adds .topic to transformed posts
> FIX: unable to share conversations with persona user

- assets/javascripts/discourse/connectors/editor-preview/ai-image-caption-container.gjs
- assets/javascripts/initializers/ai-image-caption.js
- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
Making a few adjustments to improve the experience:
* Loading container the same width as textarea to avoid jump when content loads
* Set textarea height based on content, and scroll to top... this avoids situations where someone might have to scroll back up within the caption to see the top of the text. CSS will still cap the max height/width to avoid edge cases. 
* Disable the caption button when the request starts, not after the data has been fetched 
* `pointer-events: none` disables hover and active states, so no need for those in CSS
> UX: minor adjustments for image caption size, behavior

- lib/completions/dialects/gemini.rb
- spec/lib/completions/dialects/dialect_context.rb
- spec/lib/completions/dialects/gemini_spec.rb
We need to inject blank model answers after tool calls if absent
otherwise model will reject it.
> FIX: image generation in gemini was broken

- db/fixtures/ai_helper/603_completion_prompts.rb
- lib/ai_helper/assistant.rb
- spec/lib/modules/ai_helper/assistant_spec.rb
This attempts some prompt engineering to coerce AI helper to answer
in the appropriate language.
Note mileage will vary, in testing GPT-4 produces the best results
GPT-3.5 can return OKish results.
> FEATURE: AI helper support in non English languages

- lib/embeddings/vector_representations/gemini.rb
https://meta.discourse.org/t/net-httpbadresponse-errors-on-gemini-embeddings/296952?u=falco
> FIX: Lower truncation size for Gemini Embeddings

- assets/javascripts/initializers/ai-image-caption.js
This PR fixes an issue where the call to the composer service for image captions was breaking `discourse-shared-edits`.
This PR moves the service call just before its used on `mobileView` (mobile shared edits is still functional)
**This should provide an immediate fix, however, I will continue to dig into why this was happening and can have a follow up PR with any additional fixes necessary.**
> FIX: Composer service call breaking shared edits

- app/jobs/regular/update_ai_bot_pm_title.rb
- app/models/ai_persona.rb
- lib/ai_bot/bot.rb
- lib/ai_bot/playground.rb
- lib/ai_bot/tools/summarize.rb
- lib/ai_bot/tools/tool.rb
- lib/ai_helper/assistant.rb
- spec/lib/modules/ai_bot/playground_spec.rb
- Fixes bug where OpenAI could not describe images
- Fixes bug where mentionable personas could not be mentioned unless overarching bot was enabled
- Improves internal design of playground and bot to allow better for non "bot" users
- Allow PMs directly to persona users (previously bot user would also have to be in PM)
- Simplify internal code
- Drops feature of low_cost model which is better implemented as a tool param
> DEV: improve internal design of ai persona and bug fix

- lib/completions/endpoints/open_ai.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
Previous to this fix if a tool call ever streamed a SPACE alone,
we would eat it and ignore it, breaking params
Also fixes some tests to ensure they are actually called :)
> FIX: support spaces within arguments for Open AI

- assets/javascripts/initializers/ai-bot-replies.js
- lib/ai_bot/entry_point.rb
- spec/lib/modules/ai_bot/entry_point_spec.rb
previous to this fix we did not consider personas a bot in the
front end
> FIX: stream messages when directly PMing a persona

- spec/system/page_objects/components/ai_caption_popup.rb
In https://github.com/discourse/discourse/pull/25990, I disable these buttons unless they're hovered to avoid accidentally interacting with them. 
So this test will need an update to include hover before click.
> DEV: update caption test for core interaction change

- lib/ai_bot/bot.rb
- lib/ai_bot/personas/persona.rb
- lib/ai_bot/playground.rb
- lib/ai_bot/tools/google.rb
- lib/completions/dialects/dialect.rb
- lib/completions/endpoints/base.rb
- lib/completions/endpoints/open_ai.rb
- lib/completions/prompt.rb
- spec/lib/completions/endpoints/endpoint_compliance.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
- spec/lib/completions/llm_spec.rb
- spec/lib/modules/ai_bot/personas/persona_spec.rb
- spec/lib/modules/ai_bot/playground_spec.rb
Prior to this change we had a hard limit of 1 tool call per llm
round trip. This meant you could not google multiple things at
once or perform searches across two tools.
Also:
- Hint when Google stops working
- Log topic_id / post_id when performing completions
> FIX: support multiple tool calls

- assets/javascripts/discourse/connectors/post-text-buttons/ai-helper-options-menu.gjs
This PR improves the post AI helper's positioning. Previously, we updated the positioning to be a `"bottom"` placement for the menu so that it improves the way the streaming menu grows (https://github.com/discourse/discourse-ai/pull/378). However, that made it applied for the entire menu, so when you select a large passage of text, the menu is moved to the bottom and isn't intuitive. The PR updates the logic so the bottom placement is only added after the Explain feature is triggered.
> UX: Improve Post AI Helper positioning

- lib/ai_bot/playground.rb
- spec/lib/modules/ai_bot/playground_spec.rb
We need to ensure that under no circumstances feedback loops between
bots will emerge cause this can eat up a lot of tokens
> FIX: avoid all bot feedback loops

- config/locales/server.en.yml
- config/settings.yml
- lib/ai_bot/entry_point.rb
- lib/ai_bot/personas/github_helper.rb
- lib/ai_bot/personas/persona.rb
- lib/ai_bot/playground.rb
- lib/ai_bot/tools/github_file_content.rb
- lib/ai_bot/tools/github_pull_request_diff.rb
- lib/ai_bot/tools/github_search_code.rb
- lib/ai_bot/tools/tool.rb
- lib/completions/dialects/dialect.rb
- lib/completions/endpoints/anthropic_messages.rb
- lib/completions/endpoints/base.rb
- lib/completions/endpoints/gemini.rb
- lib/completions/endpoints/open_ai.rb
- lib/completions/prompt.rb
- spec/lib/completions/endpoints/anthropic_messages_spec.rb
- spec/lib/completions/endpoints/endpoint_compliance.rb
- spec/lib/completions/endpoints/gemini_spec.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
- spec/lib/modules/ai_bot/personas/persona_spec.rb
- spec/lib/modules/ai_bot/playground_spec.rb
- spec/lib/modules/ai_bot/tools/github_file_content_spec.rb
- spec/lib/modules/ai_bot/tools/github_pull_request_diff_spec.rb
- spec/lib/modules/ai_bot/tools/github_search_code_spec.rb
This PR introduces a new AI Bot persona called 'GitHub Helper' which is specialized in assisting with GitHub-related tasks and questions. It includes the following key changes:
- Adds translations and settings for the GitHub Helper persona
- Implements the GitHub Helper persona class with its system prompt and available tools
- Adds three new AI Bot tools for GitHub interactions:
- github_file_content: Retrieves content of files from a GitHub repository 
- github_pull_request_diff: Retrieves the diff for a GitHub pull request
- github_search_code: Searches for code in a GitHub repository
- Updates the AI Bot dialects to support the new GitHub tools
- Adds specs to test the new GitHub tools functionality
With these changes, users will be able to interact with an AI assistant that can help …
> FEATURE: Add GitHub Helper AI Bot persona and tools

- assets/javascripts/discourse/components/ai-persona-editor.gjs
- lib/ai_bot/tools/tool.rb
1. Fix input fields in AI persona editor and make GitHub tool authentication optional
2. AI persona editor improvements and tool GitHub access token check
This pull request makes a few improvements:
- Adds `lang="en"` to number input fields in the AI persona editor to prevent localization issues 
- Adds `step="any"` to allow fractional values for temperature and top_p settings
- Makes GitHub tool authentication contingent on `ai_bot_github_access_token` site setting being present
see: https://meta.discourse.org/t/ai-bot-personas-don-t-accept-decimals-for-temperature-top-p/298243/7
> FIX: Improve AI persona editor inputs and optional GitHub auth

- lib/tasks/modules/sentiment/backfill.rake
- spec/tasks/backfill_spec.rb
The query included soft-deleted topics, causing errors when doing `post.topic`. The `Trashable` module default scope wasn't included by default.
> FIX: Filter soft-deleted topics when backfilling sentiment

- assets/javascripts/initializers/ai-bot-replies.js
- lib/ai_bot/entry_point.rb
- lib/guardian_extensions.rb
- spec/system/ai_bot/ai_share_conversation_spec.rb
- ai_persona_name can be null vs undefined leading to button showing up where it should not
- do not allow sharing of conversations where user is sending PMs to self
> FIX: don't show share conversation incorrectly

- config/settings.yml
- lib/tokenizer/basic_tokenizer.rb
- lib/tokenizer/open_ai_tokenizer.rb
- spec/shared/tokenizer_spec.rb
Our fast track code broke when strings had characters who are longer in tokens than in UTF-8.
Follow-up to #509 with tests added
> FIX: Handle unicode on tokenizer

- app/views/discourse_ai/ai_bot/shared_ai_conversations/show.html.erb
- Adds a nonce to both script tags
- Removes the `onload=` inline script, and moves the tags to the end of the `<body>` instead. This provides the same UX (page will load and render, then hljs will be applied when ready)
> FIX: Syntax highlighting for shared-ai conversions with CSP enabled

- app/views/discourse_ai/ai_bot/shared_ai_conversations/show.html.erb
- config/locales/server.en.yml
Previously, the title of the shared AI page would be the title of the PM. When shared somewhere else (e.g. another Discourse site, or social media platform), this can make it look like an authoritative article published by the forum owner.
This commit adds an `- AI Conversation` suffix to the page title.
This serves a few purposes:
1. Increases awareness of discourse-ai's bot feature
2. Bring external sharing in line with the internal-onebox for this feature, which already has a clear 'AI conversation' label
3. Makes it clearer that these pages are not an authoritative source, and are not necessarily endorsed by the forum owner
This is especially important in situations where the og:description is not displayed (e.g. in Discourse inline oneboxes)
> UX: Add title suffix to shared AI pages

- config/locales/client.en.yml
- discourse_automation/llm_report.rb
- lib/automation/report_runner.rb
- spec/lib/modules/automation/report_runner_spec.rb
Previously we needed to do this by hand, unfortunately this uses up
too many tokens and is very hard to discover.
New option means that we can trivially disable notifications without
needing any prompt engineering.
> FEATURE: allow suppression of notifications from report generation

- lib/ai_bot/playground.rb
- lib/automation/report_runner.rb
- lib/summarization/entry_point.rb
- spec/lib/modules/ai_bot/playground_spec.rb
- spec/lib/modules/automation/report_runner_spec.rb
- Stop replying as bot, when human replies to another human
- Reply as correct persona when replying directly to a persona
Also, implements Claude 3 models in summarization
> FEATURE: friendlier reply behavior in bot PMs

- lib/automation/report_runner.rb
- lib/summarization/models/anthropic.rb
- spec/lib/modules/automation/report_runner_spec.rb
We were only suppressing non mentions, ones that become spans.
@sam in the test was not resolving to a mention cause the user
did not exist.
depends on: https://github.com/discourse/discourse/pull/26253
For tests to pass.
> FIX: mention suppression was not working right

- lib/automation/report_runner.rb
- lib/summarization/strategies/fold_content.rb
Prompt was steering incorrectly into the wrong language.
New prompt attempts to be more concise and clear and provides
better guidance about size of summary and how to format it.
> FIX: prompt engineering for summary prompt

- lib/automation.rb
- lib/automation/llm_triage.rb
- lib/automation/report_runner.rb
report runner and llm triage used different paths to figure out
underlying model name, unify so we use the same path.
fixes claude 3 based models on llm triage
> FIX: unify automation model translation

- discourse_automation/llm_triage.rb
- spec/lib/discourse_automation/llm_triage_spec.rb
The "Triage posts using AI" automation allows admins to set a "Reply User" to represent the generated response.
When the "Reply User" is not a bot and creates a reply, the automation will be triggered again. This causes an infinite conversation from the reply_user to the reply_user.
This PR ignores posts from the "Reply User"
Here's an idea of what the full automation looks like (no change):
> FIX: Avoid replying to the reply user for llm_triage automation

- config/locales/server.en.yml
- lib/ai_bot/personas/persona.rb
- lib/ai_bot/personas/researcher.rb
- lib/ai_bot/tools/github_file_content.rb
- lib/ai_bot/tools/github_pull_request_diff.rb
- lib/ai_bot/tools/github_search_code.rb
- lib/ai_bot/tools/tool.rb
- lib/ai_bot/tools/web_browser.rb
- spec/lib/modules/ai_bot/personas/researcher_spec.rb
- spec/lib/modules/ai_bot/tools/web_browser_spec.rb
This pull request makes several improvements and additions to the GitHub-related tools and personas in the `discourse-ai` repository:
1. It adds the `WebBrowser` tool to the  `Researcher` persona, allowing the AI to visit web pages, retrieve HTML content, extract the main content, and convert it to plain text.
2. It updates the `GithubFileContent`, `GithubPullRequestDiff`, and `GithubSearchCode` tools to handle HTTP responses more robustly (introducing size limits). 
3. It refactors the `send_http_request` method in the `Tool` class to follow redirects when specified, and to read the response body in chunks to avoid memory issues with large responses. (only for WebBrowser)
4. It updates the system prompt for the `Researcher` persona to provide more detailed guidance on when to use Google …
> FEATURE: web browsing tool

- admin/assets/javascripts/discourse/routes/admin-plugins-show-discourse-ai-ai-personas-new.js
- app/controllers/discourse_ai/admin/ai_personas_controller.rb
- app/jobs/regular/digest_rag_upload.rb
- app/jobs/regular/generate_rag_embeddings.rb
- app/models/ai_persona.rb
- app/models/post_custom_prompt.rb
- app/models/rag_document_fragment.rb
- app/serializers/localized_ai_persona_serializer.rb
- assets/javascripts/discourse/admin/models/ai-persona.js
- assets/javascripts/discourse/components/ai-persona-editor.gjs
- assets/javascripts/discourse/components/persona-rag-uploader.gjs
- assets/stylesheets/modules/ai-bot/common/ai-persona.scss
- config/locales/client.en.yml
- config/routes.rb
- db/migrate/20240309034752_create_rag_document_fragment_table.rb
- db/migrate/20240313165121_embedding_tables_for_rag_uploads.rb
- lib/ai_bot/entry_point.rb
- lib/ai_bot/personas/persona.rb
- lib/embeddings/strategies/truncation.rb
- lib/embeddings/vector_representations/base.rb
- lib/inference/hugging_face_text_embeddings.rb
- plugin.rb
- spec/fabricators/rag_document_fragment_fabricator.rb
- spec/jobs/regular/digest_rag_upload_spec.rb
- spec/jobs/regular/generate_rag_embeddings_spec.rb
- spec/lib/modules/ai_bot/personas/persona_spec.rb
- spec/models/rag_document_fragment_spec.rb
- spec/requests/admin/ai_personas_controller_spec.rb
- test/javascripts/unit/models/ai-persona-test.js
This PR lets you associate uploads to an AI persona, which we'll split and generate embeddings from. When building the system prompt to get a bot reply, we'll do a similarity search followed by a re-ranking (if available). This will let us find the most relevant fragments from the body of knowledge you associated with the persona, resulting in better, more informed responses.
For now, we'll only allow plain-text files, but this will change in the future.
> FEATURE: AI Bot RAG support.

- app/jobs/regular/digest_rag_upload.rb
- app/jobs/regular/generate_rag_embeddings.rb
- app/models/rag_document_fragment.rb
- db/migrate/20240404000838_add_metadata_to_rag_document_frament.rb
- lib/ai_bot/personas/persona.rb
- plugin.rb
- spec/fixtures/rag/doc_with_metadata.txt
- spec/fixtures/rag/parsed_doc_with_metadata.txt
- spec/jobs/regular/digest_rag_upload_spec.rb
You may include non indexed metadata in the RAG document by using
[[metadata ....]]
This information is attached to all the text below and provided to
the retriever.
This allows for RAG to operate within a rich amount of contexts
without getting lost
Also:
- re-implemented chunking algorithm so it streams
- moved indexing to background low priority queue
> FEATURE: Add metadata support for RAG

- public/ai-share/share.css
Adds some more missing element styles...
Before:
After:
> UX: adjust AI share styles for images and quotes

- lib/completions/dialects/chat_gpt.rb
- lib/completions/endpoints/open_ai.rb
- lib/summarization/entry_point.rb
Open AI just released gpt-4-turbo (with vision)
This change stops using the old preview model and swaps with the
officially released gpt-4-turbo
To come is an implementation of vision.
> FEATURE: remove gpt-4-turbo-0125 preview swap with gpt-4-turbo

- config/settings.yml
- db/migrate/20240410170000_add_embeddings_tablesfor_bge_m3.rb
- lib/embeddings/vector_representations/base.rb
- lib/embeddings/vector_representations/bge_m3.rb
- lib/tasks/modules/embeddings/database.rake
- lib/tokenizer/bge_m3_tokenizer.rb
- spec/shared/tokenizer_spec.rb
- tokenizers/README.md
BAAI/bge-m3 is an interesting model, that is multilingual and with a context size of 8192. Even with a 16x larger context, it's only 4x slower to compute it's embeddings on the worst case scenario.
Also includes a minor refactor of the rake task, including setting model and concurrency levels when running the backfill task.
> FEATURE: Add BGE-M3 embeddings support

- app/models/ai_api_audit_log.rb
- config/locales/client.en.yml
- config/locales/server.en.yml
- config/settings.yml
- lib/ai_bot/bot.rb
- lib/ai_bot/entry_point.rb
- lib/completions/dialects/command.rb
- lib/completions/dialects/dialect.rb
- lib/completions/endpoints/base.rb
- lib/completions/endpoints/cohere.rb
- spec/lib/completions/endpoints/cohere_spec.rb
- Added Cohere Command models (Command, Command Light, Command R, Command R Plus) to the available model list
- Added a new site setting `ai_cohere_api_key` for configuring the Cohere API key
- Implemented a new `DiscourseAi::Completions::Endpoints::Cohere` class to handle interactions with the Cohere API, including:
- Translating request parameters to the Cohere API format
- Parsing Cohere API responses 
- Supporting streaming and non-streaming completions
- Supporting "tools" which allow the model to call back to discourse to lookup additional information
- Implemented a new `DiscourseAi::Completions::Dialects::Command` class to translate between the generic Discourse AI prompt format and the Cohere Command format
- Added specs covering the new Cohere endpoint and dialect classes
- …
> FEATURE: Cohere Command R support

- app/controllers/discourse_ai/ai_bot/shared_ai_conversations_controller.rb
- app/jobs/regular/shared_conversation_adjust_upload_security.rb
- app/models/shared_ai_conversation.rb
- plugin.rb
- spec/jobs/shared_conversation_adjust_upload_security_spec.rb
- spec/requests/ai_bot/shared_ai_conversations_spec.rb
This commit uses a new plugin modifier introduced in https://github.com/discourse/discourse/pull/26508
to mark all uploads as _not_ secure in shared PM AI conversations.
This is so images created by the AI bot (or uploaded by the user)
do not end up as broken URLs because of the security requirements
around them.
This relies on the TopicUploadSecurityManager in core as well,
which is fired when an AI conversation is shared or deleted.
**Relies on the core PR mentioned above to be merged first.**
> FIX: Secure/unsecure uploads when sharing AI conversations

- lib/completions/dialects/dialect.rb
- spec/lib/completions/dialects/dialect_spec.rb
Just having the word JSON can confuse models when we expect them
to deal solely in XML
Instead provide an example of how string arrays should be returned
Technically the tool framework supports int arrays and more, but
our current implementation only does string arrays.
Also tune the prompt construction not to give any tips about arrays
if none exist
> FIX: never mention the word JSON in tool preamble

- lib/ai_bot/tools/github_pull_request_diff.rb
- lib/completions/dialects/llama2_classic.rb
- spec/lib/completions/dialects/llama2_classic_spec.rb
- spec/lib/completions/dialects/mixtral_spec.rb
- spec/lib/completions/dialects/orca_style_spec.rb
- spec/lib/modules/ai_bot/tools/github_pull_request_diff_spec.rb
Oh no we were chucking out the first file in a PR diff due to a
logic bug
> FIX: throwing away first file in diff

- lib/completions/dialects/chat_gpt.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
Recent release of GPT-4 turbo adds vision support, this adds
the pipeline for sending images to Open AI.
> FEATURE: GPT-4 turbo vision support

- admin/assets/javascripts/discourse/routes/admin-plugins-show-discourse-ai-ai-personas-new.js
- app/controllers/discourse_ai/admin/ai_personas_controller.rb
- app/jobs/regular/digest_rag_upload.rb
- app/jobs/regular/generate_rag_embeddings.rb
- app/models/ai_persona.rb
- app/serializers/localized_ai_persona_serializer.rb
- assets/javascripts/discourse/admin/models/ai-persona.js
- assets/javascripts/discourse/components/ai-persona-editor.gjs
- assets/stylesheets/modules/ai-bot/common/ai-persona.scss
- config/locales/client.en.yml
- db/migrate/20240409035951_add_rag_params_to_ai_persona.rb
- lib/ai_bot/entry_point.rb
- lib/ai_bot/personas/persona.rb
- lib/tokenizer/basic_tokenizer.rb
- lib/tokenizer/open_ai_tokenizer.rb
- spec/fixtures/rag/doc_with_metadata.txt
- spec/fixtures/rag/parsed_doc_with_metadata.txt
- spec/jobs/regular/digest_rag_upload_spec.rb
- spec/lib/modules/ai_bot/personas/persona_spec.rb
- spec/models/ai_persona_spec.rb
- spec/models/rag_document_fragment_spec.rb
- spec/requests/admin/ai_personas_controller_spec.rb
- test/javascripts/unit/models/ai-persona-test.js
- change chunking to be token based vs char based (which is more accurate)
- allow control over overlap / tokens per chunk and conversation snippets inserted
- UI to control new settings
> FEATURE: allow tuning of RAG generation

- lib/embeddings/entry_point.rb
- spec/requests/topic_spec.rb
This is necessary when "lazy load categories" feature is enabled to make sure the categories are rendered for all related topics.
> FIX: Load categories for related topics

- app/controllers/discourse_ai/ai_bot/bot_controller.rb
- app/models/ai_api_audit_log.rb
- app/models/ai_persona.rb
- assets/javascripts/discourse/admin/models/ai-persona.js
- assets/javascripts/discourse/components/ai-persona-editor.gjs
- assets/javascripts/discourse/components/modal/debug-ai-modal.gjs
- assets/javascripts/discourse/components/persona-rag-uploader.gjs
- assets/javascripts/initializers/ai-bot-replies.js
- assets/stylesheets/modules/ai-bot/common/bot-replies.scss
- config/locales/client.en.yml
- config/locales/server.en.yml
- config/routes.rb
- config/settings.yml
- lib/ai_bot/bot.rb
- lib/ai_bot/entry_point.rb
- lib/ai_bot/tools/discourse_meta_search.rb
- lib/guardian_extensions.rb
- spec/lib/modules/ai_bot/entry_point_spec.rb
- spec/requests/ai_bot/bot_controller_spec.rb
- test/javascripts/unit/models/ai-persona-test.js
This commit introduces the ability for specified user groups to access AI debugging tools, creates the modal presentation for AI interactions, and performs various code cleanups. 
1. **Bot Debugging and Tracking:**
- Addition of `ai_bot_debugging_allowed_groups` setting to allow specified user groups to access debugging tools.
- Introduction of routes to display debug info for posts and adjustments for stopping bot streaming. (streaming was not working when you created an AI user for a persona)
- New backend methods to facilitate debugging capabilities, `show_debug_info` which fetches debug data related to AI interactions.
2. **UI Enhancements and Adjustments:**
- Updates to SCSS files to modify the modal presentation for AI-related interfaces.
- Changes within JavaScript components to …
> FEATURE: Enhance AI debugging capabilities and improve interface adjustments

- config/locales/client.en.yml
- config/settings.yml
- lib/ai_bot/bot.rb
- lib/ai_bot/entry_point.rb
- lib/automation.rb
- lib/completions/dialects/gemini.rb
- lib/completions/endpoints/aws_bedrock.rb
- lib/completions/endpoints/gemini.rb
- lib/completions/llm.rb
- lib/summarization/entry_point.rb
- Updated AI Bot to only support Gemini 1.5 (used to support 1.0) - 1.0 was removed cause it is not appropriate for Bot usage
- Summaries and automation can now lean on Gemini 1.5 pro
- Amazon added support for Claude 3 Opus, added internal support for it on bedrock
> FEATURE: Gemini 1.5 pro support and Claude Opus bedrock support

- lib/completions/endpoints/base.rb
- lib/completions/endpoints/gemini.rb
- lib/completions/endpoints/open_ai.rb
- lib/completions/function_call_normalizer.rb
- spec/lib/completions/endpoints/endpoint_compliance.rb
- spec/lib/completions/function_call_normalizer_spec.rb
For quite a few weeks now, some times, when running function calls
on Anthropic we would get a "stray" - "calls" line.
This has been enormously frustrating!
I have been unable to find the source of the bug so instead decoupled
the implementation and create a very clear "function call normalizer"
This new class is extensively tested and guards against the type of
edge cases we saw pre-normalizer.
This also simplifies the implementation of "endpoint" which no longer
needs to handle all this complex logic.
> FIX: more robust function call support

- config/settings.yml
- lib/ai_bot/bot.rb
- lib/ai_bot/personas/persona.rb
- lib/ai_bot/tools/image.rb
- lib/ai_helper/painter.rb
- lib/inference/stability_generator.rb
- spec/shared/inference/stability_generator_spec.rb
- Adds support for sd3 and sd3 turbo models - this requires new endpoints
- Adds a hack to normalize arrays in the tool calls
- Removes some leftover code 
- Adds support for aspect ratio as well so you can generate wide or tall images
> FEATURE: Stable diffusion 3 support

- lib/automation/report_context_generator.rb
- spec/lib/modules/automation/report_runner_spec.rb
This allows you to exclude trees of categories in a simple way
It also means you can no longer exclude "just the parent" but
this is a fair compromise.
> FIX: when excluding categories also exclude children

- lib/automation/report_context_generator.rb
- spec/lib/modules/automation/report_runner_spec.rb
We were forgetting about the NULL parent_category_id handling in
our check for sub categories
> FIX: many missing topics when categories excluded

- app/controllers/discourse_ai/admin/ai_personas_controller.rb
- app/jobs/regular/digest_rag_upload.rb
- assets/javascripts/discourse/components/ai-persona-editor.gjs
- assets/javascripts/discourse/components/persona-rag-uploader.gjs
- assets/javascripts/discourse/components/rag-upload-progress.gjs
Updating the editing model's rag_uploads in the editor component broke multi-file uploading. Instead, we'll keep the uploads in the uploader and update the model when we finish.
This PR also fast-tracks the initial update so we can show feedback to the user quickly, and allows uploading MD files.
Bug reported on https://meta.discourse.org/t/discourse-ai-persona-upload-support/304049/11
> FIX: RAG uploader must support multi-file indexing.

- app/controllers/discourse_ai/admin/ai_personas_controller.rb
- app/models/ai_persona.rb
- app/serializers/localized_ai_persona_serializer.rb
- assets/javascripts/discourse/admin/models/ai-persona.js
- assets/javascripts/discourse/components/ai-persona-editor.gjs
- assets/javascripts/discourse/components/persona-rag-uploader.gjs
- config/locales/client.en.yml
- db/migrate/20240429065155_add_consolidated_question_llm_to_ai_persona.rb
- lib/ai_bot/bot.rb
- lib/ai_bot/personas/persona.rb
- lib/ai_bot/question_consolidator.rb
- lib/completions/endpoints/fake.rb
- spec/lib/modules/ai_bot/personas/persona_spec.rb
- spec/lib/modules/ai_bot/question_consolidator_spec.rb
- test/javascripts/unit/models/ai-persona-test.js
This commit introduces a new feature for AI Personas called the "Question Consolidator LLM". The purpose of the Question Consolidator is to consolidate a user's latest question into a self-contained, context-rich question before querying the vector database for relevant fragments. This helps improve the quality and relevance of the retrieved fragments.
Previous to this change we used the last 10 interactions, this is not ideal cause the RAG would "lock on" to an answer. 
EG:
- User: how many cars are there in europe
- Model: detailed answer about cars in europe including the term car and vehicle many times
- User: Nice, what about trains are there in the US
In the above example "trains" and "US" becomes very low signal given there are pages and pages talking about cars and europe. This …
> FEATURE: Add Question Consolidator for robust Upload support in Personas

- public/ai-share/share.css
This prevents content from overflowing and breaking the layout, and constrains all images to be no wider than 100% of the content container. 
Before:
After:
> UX: prevent social share content from overflowing container

- lib/ai_bot/personas/discourse_helper.rb
- lib/completions/endpoints/open_ai.rb
- lib/completions/llm.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
- spec/lib/completions/llm_spec.rb
A recent change meant that llm instance got cached internally, repeat calls
to inference would cache data in Endpoint object leading model to
failures.
Both Gemini and Open AI expect a clean endpoint object cause they
set data.
This amends internals to make sure llm.generate will always operate
on clean objects
> FIX: call after tool calls failing on OpenAI / Gemini

- spec/lib/modules/toxicity/entry_point_spec.rb
Also makes this spec to use the `update_message!` helper.
> DEV: updates spec following changes in chat

- lib/embeddings/semantic_search.rb
This will be used by another plugin, so making this public before we build a proper interface for it.
> DEV: Mark hypothetical_post_from method public

- lib/ai_bot/playground.rb
- lib/completions/prompt_messages_builder.rb
- spec/lib/modules/ai_bot/playground_spec.rb
When the bot is @mentioned, we need to be a lot more careful
about constructing context otherwise bot gets ultra confused.
This changes multiple things:
1. We were omitting all thread first messages (fixed)
2. Include thread title (if available) in context
3. Construct context in a clearer way separating user request from data
> FIX: context repairs for @mentioned bot

- assets/javascripts/discourse/components/ai-persona-command-option-editor.gjs
- config/locales/server.en.yml
- lib/ai_bot/tools/search.rb
- lib/ai_bot/tools/tool.rb
- spec/lib/modules/ai_bot/tools/search_spec.rb
- spec/requests/admin/ai_personas_controller_spec.rb
This optional feature allows search to be performed in the context
of the user that executed it.
By default we do not allow this behavior cause it means llm gets
access to potentially secure data.
> FEATURE: search command now support searching in context of user

- app/controllers/discourse_ai/embeddings/embeddings_controller.rb
These should be preloaded when "lazy load categories" is enabled.
> FIX: Load categories for AI search results

- app/models/ai_api_audit_log.rb
- config/locales/client.en.yml
- config/locales/client.pl_PL.yml
- config/locales/server.en.yml
- config/settings.yml
- db/migrate/20240514001334_add_feature_name_to_ai_api_audit_log.rb
- db/post_migrate/20240119152348_explicit_provider_backwards_compat.rb
- lib/ai_bot/bot.rb
- lib/ai_bot/entry_point.rb
- lib/ai_bot/question_consolidator.rb
- lib/ai_bot/tools/summarize.rb
- lib/ai_helper/assistant.rb
- lib/ai_helper/chat_thread_titler.rb
- lib/ai_helper/painter.rb
- lib/automation.rb
- lib/automation/llm_triage.rb
- lib/automation/report_runner.rb
- lib/completions/dialects/chat_gpt.rb
- lib/completions/endpoints/base.rb
- lib/completions/endpoints/canned_response.rb
- lib/completions/endpoints/fake.rb
- lib/completions/endpoints/open_ai.rb
- lib/completions/llm.rb
- lib/configuration/llm_validator.rb
- lib/embeddings/semantic_search.rb
- lib/summarization/entry_point.rb
- lib/summarization/strategies/fold_content.rb
- spec/lib/completions/endpoints/anthropic_spec.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
- Introduce new support for GPT4o (automation / bot / summary / helper)
- Properly account for token counts on OpenAI models
- Track feature that was used when generating AI completions
> FEATURE: GPT4o support and better auditing

- config/settings.yml
- discourse_automation/llm_triage.rb
- a post can be triage a maximum of twice a minute
- system can run a total of 40 triages a minute
Low defaults were picked to safeguard against any possible loops
> FEATURE: safeguard to avoid over triage

- admin/assets/javascripts/discourse/templates/admin-plugins/show/discourse-ai-personas/new.hbs
- assets/javascripts/discourse/components/ai-llms-list-editor.gjs
- assets/javascripts/discourse/components/ai-persona-list-editor.gjs
This commit uses the new DBreadcrumbsItem and DBreadcrumbsContainer
from core to show a path back to the admin plugins list.
> FEATURE: Use DBreadcrumbsItem in admin UI

- assets/stylesheets/modules/ai-bot/common/bot-replies.scss
When triggering a PM from new-message route, we still had the UI
for "this is an official warning"
This removes that UI from bot messages, which is all clutter.
> UX: suppress "this is a warning"

- app/controllers/discourse_ai/ai_bot/shared_ai_conversations_controller.rb
- config/locales/server.en.yml
I am enabling `config.i18n.raise_on_missing_translations` in core. This revealed a couple of broken translations in the plugin. This PR fixes that.
> FIX: Amend incorrect translation keys

- app/controllers/discourse_ai/admin/ai_llms_controller.rb
- assets/javascripts/discourse/components/ai-llm-editor.gjs
- config/locales/client.en.yml
- config/locales/server.en.yml
- config/routes.rb
- lib/configuration/llm_validator.rb
- spec/requests/admin/ai_llms_controller_spec.rb
This change allows us to delete custom models. It checks if there is no module using them.
It also fixes a bug where the after-create transition wasn't working. While this prevents a model from being saved multiple times, endpoint validations are still needed (will be added in a separate PR).:
> FEATURE: Allow deleting custom LLMs.

- assets/javascripts/discourse/connectors/user-preferences-nav/ai-preferences.gjs
- lib/ai_helper/entry_point.rb
This PR moves the logic that checks whether a user in the allowed groups to use auto image captions to the server side. This is necessary because we don't serialize all of a user's groups to the client, so it can lead to issues if we handle it on the client side.
> FIX: Move image caption group check logic to server side

- app/controllers/discourse_ai/ai_helper/assistant_controller.rb
- config/settings.yml
- lib/ai_helper/assistant.rb
- lib/completions/llm.rb
- lib/configuration/llm_vision_enumerator.rb
- spec/requests/ai_helper/assistant_controller_spec.rb
Previoulsy on GPT-4-vision was supported, change introduces support
for Google/Anthropic and new OpenAI models
Additionally this makes vision work properly in dev environments
cause we send the encoded payload via prompt vs sending urls
> FEATURE: add support for all vision models

- lib/completions/endpoints/open_ai.rb
> FIX: include_usage is not available in the Azure API.

- app/controllers/discourse_ai/ai_bot/shared_ai_conversations_controller.rb
- config/locales/server.en.yml
- spec/requests/ai_bot/shared_ai_conversations_spec.rb
Initial implementation allowed internet wide sharing of
AI conversations, on sites that require login.
This feature can be an anti feature for private sites cause they
can not share conversations internally.
For now we are removing support for public sharing on login required
sites, if the community need the feature we can consider adding a
setting.
> FEATURE: restrict public sharing on login required sites

- admin/assets/javascripts/discourse/templates/admin-plugins/show/discourse-ai-personas/new.hbs
Followup to 06137ac7066d35606ed54104a06e53535cf6f08c
> FIX: Remove doubled up breadcrumb in persona UI

- config/locales/server.en.yml
- config/settings.yml
- lib/completions/dialects/claude.rb
- lib/completions/dialects/claude_tools.rb
- lib/completions/dialects/xml_tools.rb
- lib/completions/endpoints/anthropic.rb
- lib/completions/endpoints/aws_bedrock.rb
- lib/completions/endpoints/base.rb
- lib/completions/xml_tag_stripper.rb
- spec/lib/completions/dialects/claude_spec.rb
- spec/lib/completions/endpoints/anthropic_spec.rb
- spec/lib/completions/endpoints/aws_bedrock_spec.rb
- spec/lib/completions/xml_tag_stripper_spec.rb
Native tools do not work well on Opus.
Chain of Thought prompting means it consumes enormous amounts of
tokens and has poor latency.
This commit introduce and XML stripper to remove various chain of
thought XML islands from anthropic prompts when tools are involved.
This mean Opus native tools is now functions (albeit slowly)
From local testing XML just works better now.
Also fixes enum support in Anthropic native tools
> FIX: switch off native tools on Anthropic Claude Opus

- db/migrate/20240609061418_tool_details_and_command_removal.rb
In some case we may be deploying migrations, seeding and then
running post migrations, we need this to work so we give up
on this small window of protection
> FIX: do not mark column read only so certain deployments work

- public/ai-share/share.css
> UX: improve appearance of attributed quote when sharing

- lib/ai_bot/bot.rb
- spec/lib/modules/ai_bot/playground_spec.rb
We were missing logic to handle custom_html from tools
This also fixes image generation in chat
> FIX: Dall E / Artist broken when tool_details is disabled

- lib/ai_bot/personas/sql_helper.rb
- lib/ai_bot/tools/search.rb
- lib/completions/xml_tag_stripper.rb
- spec/lib/completions/xml_tag_stripper_spec.rb
- spec/lib/modules/ai_bot/tools/search_spec.rb
- Display filtered search correctly, so it is not confusing
- When XML stripping, if a chunk was `<` it would crash
- SQL Helper improved to be better aware of Data Explorer
> FIX: display search correctly, bug when stripping XML

- app/controllers/discourse_ai/admin/ai_llms_controller.rb
- app/models/llm_model.rb
- assets/javascripts/discourse/components/ai-llms-list-editor.gjs
- config/locales/client.en.yml
- config/locales/server.en.yml
- db/post_migrate/20240603143158_seed_oss_models.rb
- lib/ai_bot/tools/read.rb
- lib/ai_bot/tools/tool.rb
- spec/lib/modules/ai_bot/tools/read_spec.rb
- spec/system/ai_bot/persona_spec.rb
Previously read tool only had access to public topics, this allows
access to all topics user has access to, if admin opts for the option
Also fixes VLLM migration
> FEATURE: allow access to private topics if tool permits

- app/serializers/llm_model_serializer.rb
- assets/javascripts/discourse/components/ai-llm-editor.gjs
- assets/stylesheets/modules/llms/common/ai-llms-editor.scss
- config/locales/client.en.yml
API Key value is secret by default, and we include a link to the AI bot user.
> UX: QoL impromevements to the admin LLM models page.

- app/controllers/discourse_ai/admin/ai_llms_controller.rb
- db/post_migrate/20240619193057_choose_llm_model_setting_migration.rb
- lib/completions/llm.rb
- lib/configuration/llm_dependency_validator.rb
- lib/configuration/llm_enumerator.rb
- lib/configuration/llm_validator.rb
- spec/jobs/regular/stream_post_helper_spec.rb
- spec/lib/modules/ai_bot/tools/search_spec.rb
- spec/lib/modules/ai_helper/assistant_spec.rb
- spec/lib/modules/ai_helper/chat_thread_titler_spec.rb
- spec/lib/modules/ai_helper/entry_point_spec.rb
- spec/lib/modules/ai_helper/painter_spec.rb
- spec/lib/modules/embeddings/semantic_search_spec.rb
- spec/plugin_helper.rb
- spec/plugin_spec.rb
- spec/requests/admin/ai_llms_controller_spec.rb
- spec/requests/ai_helper/assistant_controller_spec.rb
- spec/system/ai_helper/ai_composer_helper_spec.rb
- spec/system/ai_helper/ai_image_caption_spec.rb
- spec/system/ai_helper/ai_post_helper_spec.rb
- spec/system/ai_helper/ai_split_topic_suggestion_spec.rb
We no longer support the "provider:model" format in the "ai_helper_model" and "ai_embeddings_semantic_search_hyde_model" settings. We'll migrate existing values and work with our new data-driven LLM configs from now on.
> DEV: Transition "Select model" settings to only use LlmModels

- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
This hides the image caption button on non-touch devices (desktop) until the image is hovered. 
In https://github.com/discourse/discourse/commit/0a99407bfb363a28ae1a419cc5e4c16346b784f8 we made the image controls always visible (not just on hover), and the caption button can kind of get in the way. So this helps hide it until needed since it's a little large. 
Before (button obscures image always): 
After (button appears on control or image hover):
> UX: show image caption button on image hover

- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
This should improve the layout of the composer helper buttons.
Before:
After:
> UX: improve composer suggestion button layout

- app/controllers/discourse_ai/admin/ai_llms_controller.rb
- app/models/llm_model.rb
- assets/javascripts/discourse/components/ai-llm-editor-form.gjs
- assets/javascripts/discourse/components/ai-llm-editor.gjs
- assets/javascripts/discourse/components/ai-llms-list-editor.gjs
- config/locales/client.en.yml
- lib/completions/endpoints/anthropic.rb
- lib/completions/endpoints/aws_bedrock.rb
- lib/completions/llm.rb
- spec/system/llms/ai_llm_spec.rb
Previous to this users needed to look up complicated settings
when setting up models.
This introduces and extensible preset system with Google/OpenAI/Anthropic
presets.
This will cover all the most common LLMs, we can always add more as
we go.
Additionally:
- Proper support for Anthropic Claude Sonnet 3.5
- Stop blurring api keys when navigating away - this made it very complex to reuse keys
> FEATURE: LLM presets for model creation

- app/models/llm_model.rb
- lib/completions/endpoints/gemini.rb
- spec/lib/completions/endpoints/gemini_spec.rb
- spec/system/llms/ai_llm_spec.rb
This meant that if you toggle ai user early it surprisingly did
not work.
Also remove safety settings from gemini, it is overly cautious
> FIX: when creating an llm we were not creating user

- app/controllers/discourse_ai/admin/ai_llms_controller.rb
- app/models/llm_model.rb
- app/serializers/llm_model_serializer.rb
- assets/javascripts/discourse/admin/models/ai-llm.js
- assets/javascripts/discourse/components/ai-llm-editor-form.gjs
- config/locales/client.en.yml
- db/migrate/20240624135356_llm_model_custom_params.rb
- db/post_migrate/20240624202602_add_provider_specific_params_to_llm_models.rb
- lib/completions/endpoints/aws_bedrock.rb
- lib/completions/endpoints/open_ai.rb
- spec/requests/admin/ai_llms_controller_spec.rb
Previously, we stored request parameters like the OpenAI organization and Bedrock's access key and region as site settings. This change stores them in the `llm_models` table instead, letting us drop more settings while also becoming more flexible.
> FEATURE: Store provider-specific parameters.

- app/controllers/discourse_ai/admin/ai_llms_controller.rb
- app/models/llm_model.rb
- spec/requests/admin/ai_llms_controller_spec.rb
Having this as a callback prevents deploys of sites with a vLLM SRV configured and pending migrations. Additionally, this fixes a bug where we didn't delete/deactivate the companion user after deleting an LLM.
> FIX: Move the bot user toggling to the controller.

- lib/ai_bot/tools/tool.rb
- spec/lib/modules/ai_bot/tools/tool_spec.rb
Previous to this change, on truncation we could return invalid
UTF-8 strings to caller
This also allows tools to read up to 20 megs vs the old 4 megs.
> FIX: never provide tools with invalid UTF-8 strings

- lib/ai_helper/assistant.rb
- spec/requests/ai_helper/assistant_controller_spec.rb
This fixed a regression introduced in #646 where we started sending schemaless URLs for our LLaVa service, which doesn't handle it well.
Moving to base64 encoded images solves:
- The service needing to download images Now the service running LLaVa doesn't need internet access
- Secure uploads compat Every image is treated the same, less branching for secure uploads
- Image Size problems Discourse is now responsible for ensure a max size for images
- Troublesome dev env Previously to this commit you would need a dev env that was internet acessible to use llava image captions
> FIX: Use base64 encoded images in AI Image Caption via LLaVa

- admin/assets/javascripts/discourse/routes/admin-plugins-show-discourse-ai-tools-new.js
- admin/assets/javascripts/discourse/routes/admin-plugins-show-discourse-ai-tools-show.js
- admin/assets/javascripts/discourse/routes/admin-plugins-show-discourse-ai-tools.js
- app/controllers/discourse_ai/admin/ai_tools_controller.rb
- app/models/ai_tool.rb
- assets/javascripts/discourse/admin/adapters/ai-tool.js
- assets/javascripts/discourse/admin/models/ai-tool.js
- assets/javascripts/discourse/components/ai-tool-editor.gjs
- assets/javascripts/discourse/components/ai-tool-list-editor.gjs
- assets/javascripts/discourse/components/ai-tool-parameter-editor.gjs
- assets/javascripts/discourse/components/modal/ai-tool-test-modal.gjs
- assets/javascripts/discourse/lib/utilities.js
- config/locales/client.en.yml
Follow up to b863ddc94bf03e1868845e10ba744bef1f68841d
Ruby:
* Validate `summary` (the column is `not null`)
* Fix `name` validation (the column has `max_length` 100)
* Fix table annotations
* Accept missing `parameter` attributes (`required, `enum`, `enum_values`)
JS:
* Use native classes
* Don't use ember's array extensions
* Add explicit service injections
* Correct class names
* Use `||=` operator
* Use `store` service to create records
* Remove unused service injections
* Extract consts
* Group actions together
* Use `async`/`await`
* Use `withEventValue`
* Sort html attributes
* Use DButtons `@label` arg
* Use `input` elements instead of Ember's `Input` component (same w/ textarea)
* Remove `btn-default` class (automatically applied by DButton)
* Don't mix `I18n.t` and `i18n` in the …
> DEV: Clean up after #677

- assets/javascripts/discourse/lib/utilities.js
- lib/automation/report_context_generator.rb
- spec/lib/modules/automation/report_runner_spec.rb
- test/javascripts/unit/lib/utilities-test.js
2 small fixes
1. The info button was not properly working post refactor
2. Suppress any secured tags from report input
> FIX: info not working, not suppressing hidden tags from report

- app/models/ai_summary.rb
- db/migrate/20240704020102_reset_identity_on_ai_summary.rb
This PR
1. Repairs the identity on the summary table, we migrated data without resetting it.
2. Adds an index into ai_summary table to match expected retrieval pattern
> FIX: repair id sequence identity on summary table

- assets/javascripts/discourse/lib/ai-streamer.js
The issue is that when cooking a post, the `<details>` are always "closed". So when morphing, it would automatically removes the "`open`" state.
This changes ensures we never more the "`open`" attribute on `<details>` tags by using the `beforeAttributeUpdated` callback (the same way we do in [core](https://github.com/discourse/discourse/blob/32c8bcc3af88158d74d5c33563f407f00b0e6fa8/app/assets/javascripts/discourse/app/components/d-editor.js#L514-L517)).
While it works when streaming, the `<details>` resets once it's done, leading to a sub-par user-experience 😢 
Haven't yet found an easy way to fix this issue 🤔 
---
No tests since 1) it's pretty hard to test streaming / morphing and 2) we already use a `FakeStreamUpdater` in tests which bypasses all of that 🤷‍♂️
Here's a recording of how …
> FIX: don't reset open state on details tag when morphing

- lib/ai_helper/assistant.rb
- spec/lib/modules/ai_helper/assistant_spec.rb
The latest AI plugin encounters an error when using the editor AI assistant's translation feature if the site setting or user custom language is set to Simplified Chinese (zh_CN).
I noticed a similar issue being reported on meta: [NoMethodError after upgrade](https://meta.discourse.org/t/nomethoderror-after-upgrade/315073).
The error originates from:
https://github.com/discourse/discourse-ai/blob/d555f18c6fadd4676d70ddd44f0bf63f2a8e8228/lib/ai_helper/assistant.rb#L32
The cause of the problem is that Simplified Chinese is coded as "zh_CN" in the site settings, but the key in LocaleSiteSetting is "zh", leading to a mismatch.
This PR fixes the issue by copying the approach used in Discourse core:
https://github.com/discourse/discourse/blob/bb0daa33cd93eeffb230689d1daacd737f61b2e7/app/models/l …
> Fix: AiHelper malfunction when site's locale is Simplified Chinese

- app/models/llm_model.rb
- db/fixtures/602_srv_backed_llm_model.rb
- db/post_migrate/20240708193243_fix_vllm_model_name.rb
- plugin.rb
- spec/models/llm_model_spec.rb
* Seeding the SRV-backed model should happen inside an initializer.
* Keep the model up to date when the hidden setting changes.
* Use the correct Mixtral model name and fix previous data migration.
* URL validation should trigger only when we attempt to update it.
[Context](https://meta.discourse.org/t/updating-ai-plugin-fails/315346)
> FIX: Flaky SRV-backed model seeding.

- db/fixtures/ai_helper/603_completion_prompts.rb
Changes the title generator prompt to avoid clickbait-y
titles and also try to avoid AI's favourite title format,
which is "Some Thing: Other Thing"
Leaving the chat thread title generator for now, that's
not as important, the bizarre titles add to the experience there.
> DEV: Tweak topic title generator prompt

- db/fixtures/ai_helper/603_completion_prompts.rb
Followup 8d4a67fbe22f78d5907a9979f9954abebf068483
The prompt worked better, but it took the instructions
about never using lowercase a little too literally,
it wasn't using it for things like LLM or Discourse,
also it was almost always framing the title as questions
so now I asked it for a mix of questions and statements
because that's less ambiguous.
> DEV: More topic title prompt tweaks

- lib/completions/dialects/dialect.rb
- spec/lib/completions/dialects/dialect_spec.rb
Using RAG fragments can lead to considerably big system messages, which becomes problematic when models have a smaller context window.
Before this change, we only look at the rest of the conversation to make sure we don't surpass the limit, which could lead to two unwanted scenarios when having large system messages:
All other messages are excluded due to size.
The system message already exceeds the limit.
As a result, I'm putting a hard-limit of 60% of available tokens. We don't want to aggresively truncate because if rag fragments are included, the system message contains a lot of context to improve the model response, but we also want to make room for the recent messages in the conversation.
> FIX: Limit system message size to 60% of available tokens.

- app/controllers/discourse_ai/admin/ai_tools_controller.rb
- assets/javascripts/discourse/admin/models/ai-tool.js
- assets/javascripts/discourse/components/ai-tool-editor.gjs
- assets/javascripts/discourse/components/ai-tool-parameter-editor.gjs
- config/locales/client.en.yml
- lib/completions/dialects/open_ai_tools.rb
- spec/requests/admin/ai_tools_controller_spec.rb
Enums didn't work as expected because we the dialect couldn't translate them correctly. It doesn't understand what "enum_values" is.
> FIX: Make sure custom tool enums follow json-schema.

- assets/javascripts/discourse/connectors/topic-map-expanded-after/ai-summary-box.gjs
- assets/stylesheets/modules/summarization/common/ai-summary.scss
This PR aims to better integrate the topic summarization UI with the new topic map.
- It uses the `DMenu` component that renders a floating menu on desktop and a modal on mobile.
- Adds a new button to regenerate the summary instead of reusing the "Summarize" one.
- Removes unused variables, some code refactoring, and includes small style fixes.
Complementary PR: https://github.com/discourse/discourse/pull/28053
<div align="center">
</div>
> UX: Use `DMenu` for topic summarization

- db/migrate/20240726164937_fix_ai_summaries_sequence.rb
Previous attempt at 3815360 could fail due to a race introduced in 1b0ba91 where summaries are migrated to core in a post_migrate erroneously.
> FIX: Properly fix ai_summaries table sequence

- app/controllers/discourse_ai/admin/ai_llms_controller.rb
- app/controllers/discourse_ai/admin/ai_personas_controller.rb
render_json_error expects a AR model not a serializer, using a
serializer eats up the error message
> FIX: properly pass errors to client

- config/settings.yml
Every week someone gets confused because this isn't enabled, so let's enable it by default when the module is enabled.
> FEATURE: Make emotion analysis enabled by default

- assets/javascripts/discourse/connectors/topic-map-expanded-after/ai-summary-box.gjs
- assets/stylesheets/modules/summarization/desktop/ai-summary.scss
- config/locales/client.en.yml
- plugin.rb
This commit:
* positions the topic summary on desktop fixed to the right hand side
* increases the max-width and uses the same value for default width, avoiding jumpyness
* introduces a sticky header + close button
> UX: summary fixed positioning

- lib/ai_bot/playground.rb
Somehow it's possible to have a nil `post.reply_to_post` with a non-nil `post.reply_to_post_number`.
> FIX: Handle nil reply_to_post in AI Bot event handler

- admin/assets/javascripts/discourse/routes/admin-plugins-show-discourse-ai-llms-new.js
- app/models/llm_model.rb
- assets/javascripts/discourse/components/ai-llm-editor-form.gjs
- config/locales/server.en.yml
- db/migrate/20240807150605_add_default_to_provider_params.rb
- lib/completions/endpoints/aws_bedrock.rb
- spec/requests/admin/ai_llms_controller_spec.rb
Creating a new model, either manually or from presets, doesn't initialize the `provider_params` object, meaning their custom params won't persist.
Additionally, this change adds some validations for Bedrock params, which are mandatory, and a clear message when a completion fails because we cannot build the URL.
> FIX: Correctly save provider-specific params for new models.

- lib/completions/endpoints/gemini.rb
- spec/lib/completions/endpoints/gemini_spec.rb
Gemini experimental model requires tool_config.
Previously defaults would apply.
This corrects prompts containing multiple tools on gemini.
> FIX: gemini 0801 tool calls

- app/controllers/discourse_ai/summarization/summary_controller.rb
- app/jobs/regular/stream_topic_ai_summary.rb
- app/services/discourse_ai/topic_summarization.rb
- assets/javascripts/discourse/connectors/topic-map-expanded-after/ai-summary-box.gjs
- spec/requests/summarization/summary_controller_spec.rb
- spec/services/discourse_ai/topic_summarization_spec.rb
When navigating between topic we were not correctly resetting
internal state for summarization. This leads to a situation where
incorrect summaries can be displayed to users and wrong summaries
can be displayed.
Additionally our controller for grabbing summaries was always
streaming results via message bus, which could be delayed when
sidekiq is overloaded. We now will return the cached summary
right away if it is available direct from REST endpoint.
> FIX: more robust summary implementation

- config/locales/server.en.yml
- discourse_automation/llm_triage.rb
- lib/automation/llm_triage.rb
- spec/lib/modules/automation/llm_triage_spec.rb
The score will contain the LLM result, and make sure the flag isn't displayed when a minimum score threshold is present.
> FIX: Triage-flagged posts didn't have a score.

- assets/javascripts/discourse/connectors/topic-map-expanded-after/ai-summary-box.gjs
- assets/stylesheets/modules/summarization/desktop/ai-summary.scss
- test/javascripts/acceptance/topic-summary-test.js
**This PR fixes an issue where the summary breaks when you click on a link inside the summary.**
---
**Additionally, this PR also sneaks in a small UX fix:**
_Before_
_After_
> FIX: Clicking on summary links breaks summary

- config/locales/server.en.yml
- config/settings.yml
- lib/guardian_extensions.rb
- spec/lib/guardian_extensions_spec.rb
New `ai_pm_summarization_allowed_groups` can be used to allow
visibility of the summarization feature on PMs.
This can be useful on forums where a lot of communication happens
inside PMs.
> FEATURE: Allow specific groups access to summary feature on PMs

- admin/assets/javascripts/discourse/routes/admin-plugins-show-discourse-ai-llms-show.js
- app/controllers/discourse_ai/admin/ai_llms_controller.rb
- app/models/llm_model.rb
- assets/javascripts/discourse/components/ai-llm-editor-form.gjs
- assets/stylesheets/modules/llms/common/ai-llms-editor.scss
- config/locales/client.en.yml
- config/locales/server.en.yml
- discourse_automation/llm_triage.rb
- lib/automation/llm_triage.rb
- lib/completions/dialects/open_ai_compatible.rb
- spec/lib/completions/dialects/open_ai_compatible_spec.rb
- spec/requests/admin/ai_llms_controller_spec.rb
This change adds support for OSS models without support for system messages. LlmTriage's system message field is no longer mandatory. We now send the post contents in a separate user message.
> FEATURE: LLM Triage support for systemless models.

- assets/javascripts/discourse/components/ai-tool-editor.gjs
`withEventValue` is not needed here, because the `onChange` event comes from ace, not a normal DOM event. But even with that fix, it seems AceEditor doesn't yet work well with the DDAU pattern. On every keypress, the editor re-renders and puts the cursor back at the beginning.
For now, this commit removes the `@onChange` hook, so we go back to relying on the two-way binding of `@content`.
Followup to a5a39dd2ee5a71365cd349cabc1f34e261235d24
> FIX: Tool editing code editor resetting on every keypress

- lib/ai_helper/assistant.rb
- lib/completions/dialects/open_ai_compatible.rb
- lib/completions/prompt.rb
- spec/lib/completions/dialects/open_ai_compatible_spec.rb
Only affects models hosted via HF or vLLM.
Reported on meta: https://meta.discourse.org/t/captioning-goes-nuts/323079
> FIX: Malformed message in systemless + inline img scenario

- assets/javascripts/discourse/components/ai-tool-editor.gjs
AceEditor is now a glimmer component (see: https://github.com/discourse/discourse/pull/28492) and it follows the "data down, actions up" pattern.
> DEV: Update ace-editor usage

- config/locales/client.en.yml
- discourse_automation/llm_triage.rb
- spec/lib/discourse_automation/llm_triage_spec.rb
- spec/lib/modules/automation/llm_triage_spec.rb
Reverts discourse/discourse-ai#775
We think it's best to add it as a trigger field in the `automation` plugin instead.
> Revert "FEATURE: Triage rule can skip posts created via email"

- app/controllers/discourse_ai/embeddings/embeddings_controller.rb
- lib/embeddings/semantic_search.rb
- spec/requests/embeddings/embeddings_controller_spec.rb
This allows callers of embedding based search to bypass hyde.
Hyde will expand the search term using an LLM, but if an LLM is
performing the search we can skip this expansion.
It also introduced some tests for the controller which we did not have
> FEATURE: allow embedding based search without hyde

- assets/javascripts/discourse/admin/models/ai-tool.js
- assets/javascripts/discourse/components/ai-tool-editor.gjs
- assets/javascripts/discourse/components/ai-tool-parameter-editor.gjs
- lib/ai_bot/tools/search_settings.rb
- spec/lib/modules/ai_bot/tools/search_settings_spec.rb
- spec/system/ai_bot/tool_spec.rb
This improves the site setting search so it performs a somewhat
fuzzy match.
Previously it did not handle seperators such as "space" and a
term such as "min_post_length" would not find "min_first_post_length"
A more liberal search algorithm makes it easier to the AI to
navigate settings.
> FEATURE: improve site setting search

- config/locales/client.en.yml
- lib/embeddings/entry_point.rb
- spec/requests/embeddings/embeddings_controller_spec.rb
The new API scope allows restricting access to semantic search
only.
> FEATURE: API scope for semantic search

- app/jobs/scheduled/embeddings_backfill.rb
- lib/embeddings/semantic_search.rb
- lib/embeddings/vector_representations/base.rb
- spec/jobs/scheduled/embeddings_backfill_spec.rb
Embedding backfill contains logic for searching for old content
change and then backfilling.
Unfortunately it was excluding all topics that had embedding
unconditionally, leading to no backfill ever happening.
This change adds a test and ensures we backfill.
> FIX: we were never reindexing old content

- assets/javascripts/initializers/ai-bot-replies.js
the default share arrow looks kind of like reply 
before:
after:
> UX: replace "share" with "share-alt" icon

- app/controllers/discourse_ai/embeddings/embeddings_controller.rb
- spec/requests/embeddings/embeddings_controller_spec.rb
Fixes 
```
NoMethodError (undefined method `downcase' for nil)
```
> FIX: coerce value before downcasing the hyde param

- lib/configuration/llm_validator.rb
- spec/configuration/llm_validator_spec.rb
Fixes:
```
NameError (undefined local variable or method `parent_module_name' for an instance of DiscourseAi::Configuration::LlmValidator)
```
> FIX: Correctly display errors when parent module needs to be disabled first

- lib/ai_helper/chat_thread_titler.rb
- spec/lib/modules/ai_helper/chat_thread_titler_spec.rb
Fixes:
```
Job exception: undefined method `split' for nil
```
> FIX: Bail earlier when a chat thread has no messages

- assets/javascripts/discourse/connectors/topic-map-expanded-after/ai-summary-box.gjs
- spec/system/summarization/topic_summarization_spec.rb
Make sure the summary box is in the DOM before attempting to display a cached summary.:
> FIX: Display cached summaries with our new streamer.

- app/controllers/discourse_ai/embeddings/embeddings_controller.rb
- spec/requests/embeddings/embeddings_controller_spec.rb
Embedding search is rate limited due to potentially expensive
hyde operation (which require LLM access).
Embedding generally is very cheap compared to it. (usually 100x cheaper)
This raises the limit to 100 per minute for embedding searches,
while keeping the old 4 per minute for HyDE powered search.
> FEATURE: disable rate limiting when skipping hyde

- assets/javascripts/discourse/components/ai-helper-options-list.gjs
With the recent composer AI helper change (https://github.com/discourse/discourse-ai/commit/9cd14b0003700d89e1a499b9e28924ef8e1443de), we accidentally hardcoded the keyboard shortcut string for proofreading. 
This PR updates that by using platform specific keys:
i.e. <kbd>⌘</kbd><kbd>⌥</kbd><kbd>P</kbd> (macOS) / <kbd>ctrl</kbd><kbd>alt</kbd><kbd>p</kbd> (Windows)
> FIX: Keyboard shortcut should be platform specific

- assets/javascripts/discourse/components/ai-composer-helper-menu.gjs
- assets/javascripts/initializers/ai-helper.js
- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
- config/locales/client.en.yml
This PR updates the error toast message location for the composer AI helper. Previously, when trying to invoke the Proofread feature or AI composer helper feature when there's no content in the composer, the toast is displayed at its default location (top right of screen). This is too far away to notice.
The new location will now be updated to right within the composer where the actual dropdown occurs. This should help teach the user what the right expected usage of the tool would be.
A few other small changes in this PR:
- We update the string so that it is shorter for the new location so that it doesn't wrap.
- Since the proofread shortcut also triggers the toast error, but it immediately invokes a modal instead, we use `scss` to position the Toast in a better location on the composer. …
> UX: Improve toast message location

- app/models/completion_prompt.rb
This provider column was removed 10 months ago in this PR https://github.com/discourse/discourse-ai/pull/312, there is no usage of this attribute in our codebase, so there is no potential danger to remove this ignored column.
> DEV: remove ignore column syntax for the removed provider column in completion prompt model

- admin/assets/javascripts/discourse/routes/admin-plugins-show-discourse-ai-llms-new.js
- admin/assets/javascripts/discourse/templates/admin-plugins/show/discourse-ai-llms/new.hbs
- app/controllers/discourse_ai/admin/ai_llms_controller.rb
- app/serializers/llm_model_serializer.rb
- assets/javascripts/discourse/components/ai-llm-editor-form.gjs
- assets/javascripts/discourse/components/ai-llm-editor.gjs
- assets/javascripts/discourse/components/ai-llms-list-editor.gjs
- assets/stylesheets/modules/llms/common/ai-llms-editor.scss
- config/locales/client.en.yml
- spec/requests/admin/ai_llms_controller_spec.rb
- spec/system/llms/ai_llm_spec.rb
This updates the layout and styles of /admin/plugins/discourse-ai/ai-llms
These updates simplify the process a bit by showing the templates initially, and allows for more space to include details like the model description. 
**Before**:
**After**:
> UX: move templates to main LLM config tab, restyle

- app/controllers/discourse_ai/admin/ai_personas_controller.rb
- app/controllers/discourse_ai/admin/ai_tools_controller.rb
- app/controllers/discourse_ai/admin/rag_document_fragments_controller.rb
- app/jobs/regular/digest_rag_upload.rb
- app/models/ai_tool.rb
- app/models/rag_document_fragment.rb
- app/serializers/ai_custom_tool_serializer.rb
- assets/javascripts/discourse/admin/models/ai-tool.js
- assets/javascripts/discourse/components/ai-persona-editor.gjs
- assets/javascripts/discourse/components/ai-tool-editor.gjs
- assets/javascripts/discourse/components/rag-options.gjs
- assets/javascripts/discourse/components/rag-upload-progress.gjs
- assets/javascripts/discourse/components/rag-uploader.gjs
- assets/stylesheets/modules/ai-bot/common/ai-persona.scss
- config/locales/client.en.yml
- config/routes.rb
- db/migrate/20240913054440_add_rag_columns_to_ai_tools.rb
- lib/ai_bot/tool_runner.rb
- spec/jobs/regular/generate_rag_embeddings_spec.rb
- spec/models/ai_tool_spec.rb
- spec/requests/admin/ai_personas_controller_spec.rb
- spec/requests/admin/rag_document_fragments_controller_spec.rb
This allows custom tools access to uploads and sophisticated searches using embedding.
It introduces: 
1. A shared front end for listing and uploading files (shared with personas)
2. Backend implementation of `index.search` function within a custom tool.
Custom tools now may search through uploaded files 
```
function invoke(params) {
return index.search(params.query)
}
```
This means that RAG implementers now may preload tools with knowledge and have high fidelity over
the search. 
The search function support 
1. specifying max results
2. specifying a subset of files to search (from uploads) 
Also 
- Improved documentation for tools (when creating a tool a preamble explains all the functionality)
- uploads were a bit finicky, fixed an edge case where the UI would not show them as updated
> FEATURE: RAG search within tools

- lib/completions/dialects/dialect.rb
- lib/completions/dialects/ollama.rb
- lib/completions/endpoints/ollama.rb
- spec/fabricators/llm_model_fabricator.rb
- spec/lib/completions/dialects/ollama_spec.rb
- spec/lib/completions/endpoints/ollama_spec.rb
This allows our users to add the Ollama provider and use it to serve our AI bot (completion/dialect). 
In this PR, we introduce:
1.  DiscourseAi::Completions::Dialects::Ollama which would help us translate by utilizing Completions::Endpoint::Ollama
2. Correct extract_completion_from and partials_from in Endpoints::Ollama
Also
1. Add tests for Endpoints::Ollama
2. Introduce ollama_model fabricator
Demo
AI Bot
API logs
AI configurations
> DEV: Add Ollama provider

- assets/javascripts/initializers/ai-bot-replies.js
- config/locales/client.en.yml
"Share" doesn't make a lot of sense here because you're copying the message contents on click, especially considering we have a share feature now.
Before:
After:
> UX: update icon and text for copying message

- assets/javascripts/discourse/components/ai-llms-list-editor.gjs
Relies on https://github.com/discourse/discourse/pull/28477,
uses AdminSectionLandingWrapper and AdminSectionLandingItem
for the section items on the LLM page which are used to create
a new LLM config from a template.
> DEV: Use section landing components for LLMs templates

- config/locales/client.en.yml
- config/locales/server.en.yml
- discourse_automation/llm_triage.rb
- lib/automation.rb
- lib/automation/llm_triage.rb
- spec/lib/modules/automation/llm_triage_spec.rb
Previous to this change we could flag, but there was no way
to hide content.
We had the option to hide topics, but this is not desirable for
a spam reply.
New option allows triage to hide a post if it is a reply, if the
post happens to be the first post on the topic, the topic will
be hidden.
> FEATURE: allow llm triage to automatically hide posts

- app/controllers/discourse_ai/admin/ai_personas_controller.rb
- app/models/ai_persona.rb
- assets/javascripts/discourse/admin/models/ai-persona.js
- assets/javascripts/discourse/components/ai-persona-editor.gjs
- assets/javascripts/discourse/components/ai-tool-selector.js
- config/locales/client.en.yml
- lib/ai_bot/bot.rb
- lib/ai_bot/personas/persona.rb
- lib/completions/dialects/dialect.rb
- lib/completions/endpoints/open_ai.rb
- lib/completions/llm.rb
- lib/completions/prompt.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
- spec/lib/modules/ai_bot/playground_spec.rb
- spec/requests/admin/ai_personas_controller_spec.rb
- spec/system/admin_ai_persona_spec.rb
- test/javascripts/unit/models/ai-persona-test.js
Sometimes we need to force LLMs to use tools, for example in RAG
like use cases we may want to force an unconditional search.
The new framework allows you backend to force tool usage.
This implements both front and and back end support.
Initial support is only written for OpenAI models, however follow up commits will backfill support to other providers.
> FEATURE: allows forced LLM tool use

- assets/stylesheets/modules/llms/common/ai-llms-editor.scss
In this core commit https://github.com/discourse/discourse/pull/29149 we
are changing the subheader title to H2 and making the size smaller,
this style override is no longer needed.
> UX: Remove AdminPageSubheader style override

- spec/plugin_helper.rb
The primary key is usually a bigint column, but the foreign key columns usually are of integer type. This can lead to issues when joining these columns due to mismatched types and different value ranges.
In a recent core change, all bigint sequences will start at a very high value in the test environment to surface this type of errors. The same change also added a temporary API that changes the column type to bigint in order to allow for the tests to run.
The plugin API is only temporary and it is important for these plugins to migrate their columns to bigint to avoid issues in the future.
> DEV: Fix mismatched column types in tests

- app/controllers/discourse_ai/admin/ai_personas_controller.rb
- app/models/ai_persona.rb
- app/serializers/localized_ai_persona_serializer.rb
- assets/javascripts/discourse/admin/models/ai-persona.js
- assets/javascripts/discourse/components/ai-forced-tool-strategy-selector.gjs
- assets/javascripts/discourse/components/ai-persona-editor.gjs
- config/locales/client.en.yml
- db/migrate/20241009230724_add_forced_tool_count_to_ai_personas.rb
- lib/ai_bot/bot.rb
- lib/ai_bot/personas/persona.rb
- spec/lib/modules/ai_bot/playground_spec.rb
- spec/requests/admin/ai_personas_controller_spec.rb
- spec/system/admin_ai_persona_spec.rb
- test/javascripts/unit/models/ai-persona-test.js
This introduces another configuration that allows operators to
limit the amount of interactions with forced tool usage.
Forced tools are very handy in initial llm interactions, but as
conversation progresses they can hinder by slowing down stuff
and adding confusion.
> FEATURE: allow persona to only force tool calls on limited replies

- spec/lib/modules/ai_bot/playground_spec.rb
This patch will allow upcoming changes to services (https://github.com/discourse/discourse/pull/29129) without breaking the `discourse-ai` specs.
> DEV: Use `ChatSDK.create` instead of service in specs

- lib/ai_helper/entry_point.rb
This ensures the icon added in 62ba2fa4d7a0a51008a070f3079f485c61bc8694 is included in the subset
> DEV: ensure far-copy icon is included in subset

- lib/summarization/fold_content.rb
- lib/summarization/strategies/hot_topic_gists.rb
Not addidng tests because we don't test against a real model.
> UX: Avoid introductory phrases and summarize topics without replies

- admin/assets/javascripts/discourse/routes/admin-plugins-show-discourse-ai-personas-new.js
- app/controllers/discourse_ai/admin/ai_llms_controller.rb
- app/serializers/llm_model_serializer.rb
- assets/javascripts/discourse/components/ai-llm-editor-form.gjs
- assets/javascripts/discourse/components/ai-llms-list-editor.gjs
- assets/javascripts/discourse/components/ai-persona-editor.gjs
- assets/javascripts/discourse/connectors/composer-fields/persona-llm-selector.gjs
- assets/stylesheets/modules/llms/common/ai-llms-editor.scss
- config/locales/client.en.yml
- lib/configuration/llm_enumerator.rb
- lib/configuration/llm_validator.rb
- spec/requests/admin/ai_llms_controller_spec.rb
- spec/system/llms/ai_llm_spec.rb
Also, properly set LLM when swapping persona and ensure PM
recipients are properly updated
New UI is: 
And: 
This means you can operate with 100% tethered personas and the LLM selector is not required.
Cleans up UI so it is clearer
> FEATURE: improve visibility of AI usage in LLM page

- app/models/ai_api_audit_log.rb
- config/locales/client.en.yml
- db/migrate/20241023033955_add_feature_context_to_ai_api_log.rb
- discourse_automation/llm_report.rb
- discourse_automation/llm_triage.rb
- lib/automation/llm_triage.rb
- lib/automation/report_runner.rb
- lib/completions/endpoints/base.rb
- lib/completions/endpoints/canned_response.rb
- lib/completions/endpoints/fake.rb
- lib/completions/endpoints/open_ai.rb
- lib/completions/llm.rb
- spec/lib/completions/llm_spec.rb
- spec/lib/discourse_automation/llm_triage_spec.rb
A new feature_context json column was added to ai_api_audit_logs
This allows us to store rich json like context on any LLM request
made.
This new field now stores automation id and name.
Additionally allows llm_triage to specify maximum number of tokens
This means that you can limit the cost of llm triage by scanning only
first N tokens of a post.
> FEATURE: better logging for automation reports

- config/locales/server.en.yml
- lib/ai_bot/tools/google.rb
- spec/lib/modules/ai_bot/tools/google_spec.rb
This allows to simply scope search results to specific domains, so you can filter to results for example.com using `site:example.com`
> FEATURE: allow scoping of google tool queries

- lib/ai_helper/assistant.rb
- spec/requests/ai_helper/assistant_controller_spec.rb
After testing Llama 3.2 for AI Caption is can be quite chatty and go for multiple paragraphs.
> FIX: Basic cleanup of AI Caption to remove line breaks and pipes

- assets/stylesheets/modules/summarization/common/ai-summary.scss
This ensures that erroneous short gists will still occupy a full row in the topic list... avoiding something like:
This also: 
* limits text width to 70 characters, which is on the high end of the general rule of thumb for optimal line length (45-75 characters) 
* reduces mobile gist width to better match limited topic title width
> UX: minor gist optimizations for readability

- app/models/llm_model.rb
- assets/javascripts/discourse/connectors/composer-fields/persona-llm-selector.gjs
- config/locales/client.en.yml
- config/locales/server.en.yml
- config/settings.yml
- lib/ai_bot/entry_point.rb
- lib/completions/dialects/claude.rb
- lib/completions/endpoints/anthropic.rb
- lib/completions/endpoints/aws_bedrock.rb
- lib/completions/endpoints/gemini.rb
- lib/embeddings/semantic_search.rb
- spec/lib/completions/dialects/claude_spec.rb
- spec/lib/completions/endpoints/anthropic_spec.rb
- spec/lib/completions/endpoints/aws_bedrock_spec.rb
- spec/lib/modules/ai_bot/tools/search_spec.rb
- spec/system/ai_bot/ai_bot_helper_spec.rb
This fixes a few issues:
1. When search was not finding any semantic results we would break the tool
2. Gemini / Anthropic models did not implement forced tools previously despite it being an API option
3. Mechanics around displaying llm selector were not right. If you disabled LLM selector server side persona PM did not work correctly.
4. Disabling native tools for anthropic model moved out of a site setting. This deliberately does not migrate cause this feature is really rare to need now, people who had it set probably did not need it.
5. Updates anthropic model names to latest release
> FIX: Llm selector / forced tools / search tool

- app/controllers/discourse_ai/admin/ai_tools_controller.rb
- assets/javascripts/discourse/components/ai-tool-editor.gjs
- assets/javascripts/discourse/components/modal/ai-tool-test-modal.gjs
- config/routes.rb
- lib/ai_bot/tool_runner.rb
- lib/embeddings/vector_representations/base.rb
- spec/requests/admin/ai_tools_controller_spec.rb
- spec/system/ai_bot/tool_spec.rb
This changeset contains 4 fixes:
1. We were allowing running tests on unsaved tools,
this is problematic cause uploads are not yet associated or indexed
leading to confusing results. We now only show the test button when
tool is saved.
2. We were not properly scoping rag document fragements, this
meant that personas and ai tools could get results from other
unrelated tools, just to be filtered out later
3. index.search showed options as "optional" but implementation
required the second option
4. When testing tools searching through document fragments was
not working at all cause we did not properly load the tool
> FIX: testing tool was not showing rag results

- app/controllers/discourse_ai/summarization/chat_summary_controller.rb
- lib/summarization/fold_content.rb
- lib/summarization/strategies/base.rb
- lib/summarization/strategies/chat_messages.rb
- lib/summarization/strategies/hot_topic_gists.rb
- lib/summarization/strategies/topic_summary.rb
- lib/tokenizer/basic_tokenizer.rb
- lib/tokenizer/open_ai_tokenizer.rb
- spec/lib/modules/summarization/fold_content_spec.rb
- spec/lib/modules/summarization/strategies/hot_topic_gists_spec.rb
- spec/lib/modules/summarization/strategies/topic_summary_spec.rb
- spec/shared/tokenizer_spec.rb
We hit a snag with our hot topic gist strategy: the regex we used to split the content didn't work, so we cannot send the original post separately. This was important for letting the model focus on what's new in the topic.
The algorithm doesn’t give us full control over how prompts are written, and figuring out how to format the content isn't straightforward. This means we're having to use more complicated workarounds, like regex.
To tackle this, I'm suggesting we simplify the approach a bit. Let's focus on summarizing as much as we can upfront, then gradually add new content until there's nothing left to summarize.
Also, the "extend" part is mostly for models with small context windows, which shouldn't pose a problem 99% of the time with the content volume we're dealing with.
> FIX/REFACTOR: FoldContent revamp

- assets/javascripts/discourse/components/ai-gist-disclosure.gjs
It appears that the `discovery.custom` route may not (always?) have attributes set, which can cause an error here.
> DEV: Check for presence of currentRoute.attributes

- db/migrate/20241025135522_alter_ai_ids_to_bigint.rb
- spec/plugin_helper.rb
The primary key is usually a bigint column, but the foreign key columns are usually of integer type. This can lead to issues when joining these columns due to mismatched types and different value ranges.
This was using a temporary plugin / test API to make tests pass, but it is safe to alter "ai_document_fragment_embeddings" and "rag_document_fragments" tables because they usually have less than 1M rows and migration is going to be fast.
Depending on the size of the community, "classification_results" table may have more than 1M rows and the migration will lock the table for a longer time. However, classification runs in background jobs and they will be automatically retried if they fail due to the lock, which makes it acceptable.
> DEV: Fix mismatched column types

- lib/summarization/fold_content.rb
- lib/summarization/strategies/base.rb
- lib/summarization/strategies/hot_topic_gists.rb
We want to tell these two features apart.
> DEV: Use different feature_names for summarization strategies

- app/controllers/discourse_ai/admin/ai_personas_controller.rb
- lib/ai_bot/playground.rb
- lib/ai_bot/response_http_streamer.rb
- spec/requests/admin/ai_personas_controller_spec.rb
The custom field "discourse_ai_bypass_ai_reply" was added so
we can signal the post created hook to bypass replying even
if it thinks it should.
Otherwise there are cases where we double answer user questions
leading to much confusion.
This also slightly refactors code making the controller smaller
> FIX: ensure replies are never double streamed

- public/ai-share/share.css
This makes things a little more reasonable for small images 
Before:
After:
> UX: in share, use native image dimensions and hide filename

- app/models/ai_tool.rb
- lib/ai_bot/tool_runner.rb
- lib/ai_bot/tools/tool.rb
- lib/completions/anthropic_message_processor.rb
- lib/completions/endpoints/gemini.rb
- lib/completions/endpoints/open_ai.rb
- spec/lib/completions/endpoints/anthropic_spec.rb
- spec/lib/completions/endpoints/gemini_spec.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
- spec/models/ai_tool_spec.rb
Fixes encoding of params on LLM function calls. 
Previously we would improperly return results if a function parameter returned an HTML tag.
Additionally adds some missing HTTP verbs to tool calls.
> FIX: encode parameters returned from LLMs correctly 

- lib/completions/anthropic_message_processor.rb
- lib/completions/endpoints/gemini.rb
- lib/completions/endpoints/open_ai.rb
(in cases of arrays escapeHTML will not work)
> FIX: we must properly encode objects prior to escaping

- app/controllers/discourse_ai/admin/ai_personas_controller.rb
- lib/ai_bot/personas/persona.rb
- lib/ai_bot/playground.rb
- lib/ai_bot/response_http_streamer.rb
- lib/completions/endpoints/fake.rb
- spec/requests/admin/ai_personas_controller_spec.rb
Allow specifying "custom_instructions" which are added to the system prompt when conversing with a presona via streaming api.
> FEATURE: support custom instructions for persona streaming

- assets/javascripts/discourse/components/rag-uploader.gjs
Specifying `type` when using `UppyUpload` will be required as of https://github.com/discourse/discourse/pull/29600.
> FIX: Specify type for Rag upload

- assets/javascripts/initializers/related-topics.gjs
- assets/stylesheets/modules/embeddings/common/semantic-related-topics.scss
This adds the sparkles icon to semantic related topics for anon visitors... 
Before:
After:
I also slightly scaled down the icon in the nav-pills for logged-in visitors:
Before:
After:
> UX: add sparkle icon to related topics for anons

- assets/javascripts/discourse/components/ai-topic-gist.gjs
- assets/stylesheets/modules/summarization/common/ai-summary.scss
Since we've made gists longer, they feel harder to read with the small font size — this increases the font size of gists and the surrounding elements when gists are enabled on the topic list. 
Before:
After: 
Before:
After:
> UX: increase gist size, and adjust surrounding elements to accommodate

- assets/javascripts/discourse/components/post-menu/ai-cancel-streaming-button.gjs
- assets/javascripts/discourse/components/post-menu/ai-debug-button.gjs
- assets/javascripts/discourse/components/post-menu/ai-share-button.gjs
- assets/javascripts/discourse/lib/ai-bot-helper.js
- assets/javascripts/initializers/ai-bot-replies.js
- spec/system/ai_bot/share_spec.rb
Requires https://github.com/discourse/discourse/pull/28670
> DEV: Added compatibility with the Glimmer Post Menu

- lib/ai_bot/bot.rb
- lib/ai_bot/playground.rb
- lib/completions/anthropic_message_processor.rb
- lib/completions/endpoints/anthropic.rb
- lib/completions/endpoints/base.rb
- lib/completions/endpoints/canned_response.rb
- lib/completions/endpoints/fake.rb
- lib/completions/endpoints/open_ai.rb
- lib/completions/json_streaming_parser.rb
- lib/completions/llm.rb
- lib/completions/open_ai_message_processor.rb
- lib/completions/tool_call.rb
- lib/completions/tool_call_progress_tracker.rb
- spec/lib/completions/endpoints/anthropic_spec.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
- spec/lib/modules/ai_bot/personas/persona_spec.rb
- spec/requests/ai_helper/assistant_controller_spec.rb
Implement streaming tool call implementation for Anthropic and Open AI. 
When calling:
```
llm.generate(..., partial_tool_calls: true) do ...
```
Partials may contain `ToolCall` instances with `partial: true`, These tool calls are partially populated with json partially parsed. 
So for example when performing a search you may get:
ToolCall(..., {search: "hello" })
ToolCall(..., {search: "hello world" })
The library used to parse json is:
https://github.com/dgraham/json-stream
We use a fork cause we need access to the internal buffer.
This prepares internals to perform partial tool calls, but does not implement it yet.
> FEATURE: partial tool call support for OpenAI and Anthropic

- app/models/ai_api_audit_log.rb
- app/models/llm_model.rb
- config/locales/client.en.yml
- lib/completions/dialects/dialect.rb
- lib/completions/dialects/mistral.rb
- lib/completions/endpoints/aws_bedrock.rb
- lib/completions/endpoints/base.rb
- lib/completions/endpoints/mistral.rb
- lib/completions/llm.rb
- spec/fabricators/llm_model_fabricator.rb
- spec/lib/completions/dialects/mistral_spec.rb
- spec/lib/completions/endpoints/aws_bedrock_spec.rb
Adds support for mistral models (pixtral and mistral large now have presets) 
Also corrects token accounting in AWS bedrock models
> FEATURE: Add support for Mistral models

- app/controllers/discourse_ai/ai_bot/artifacts_controller.rb
- spec/requests/ai_bot/artifacts_controller_spec.rb
The intent was always to bypass CSP we have no choice with an artifact system and it is sandboxed
> FIX: properly bypass CSP for artifacts

- app/controllers/discourse_ai/ai_bot/artifacts_controller.rb
- spec/requests/ai_bot/artifacts_controller_spec.rb
It's important that artifacts are never given 'same origin' access to the forum domain, so that they cannot access cookies, or make authenticated HTTP requests. So even when visiting the URL directly, we need to wrap them in a sandboxed iframe.
> FIX: Ensure artifacts are sandboxed, even when visited directly

- lib/summarization/entry_point.rb
The topic query is used differently, and we can't assume the modifier will always receive an AR relation. Let's scope it to `Discourse#filters` instead of most lists.
> FIX: Reduce scope of topic gists inclusion.

- lib/summarization/entry_point.rb
- spec/lib/modules/summarization/entry_point_spec.rb
We use `includes` instead of `joins` because we want to eager-load summaries, avoiding an extra query when summarizing. However, Rails will complain unless you explicitly inform them you plan to use that inside a `WHERE` clause.
> FIX: Instruct AR that we want to use ai_summaries for filtering.

- assets/javascripts/discourse/components/admin-report-emotion.hbs
- assets/javascripts/discourse/components/admin-report-emotion.js
- assets/javascripts/discourse/controllers/admin-dashboard-sentiment.js
- lib/sentiment/emotion_dashboard_report.rb
- Fixes missing filters for the main graph
- Fixes previous 30 days trend in emotion table
Also moves links to individual cells in emotion table, so admins can
drill down to the specific time period on their reports.
> FIX: Misc fixes for sentiment in the admin dashboard

- assets/javascripts/discourse/components/ai-topic-gist.gjs
- lib/guardian_extensions.rb
- spec/lib/guardian_extensions_spec.rb
Also allow "Everyone" in ai_hot_topic_gists_allowed_groups
> FIX: gists are not html safe

- app/controllers/discourse_ai/ai_bot/artifacts_controller.rb
- app/models/ai_artifact.rb
- assets/javascripts/discourse/components/ai-artifact.gjs
- config/locales/server.en.yml
- public/ai-share/share.css
Also remove uneeded sandboxing give this is all handled by
artifacts directly
> UX: improve artifact styling add direct share link

- app/controllers/discourse_ai/ai_bot/artifacts_controller.rb
- app/views/discourse_ai/ai_bot/shared_ai_conversations/show.html.erb
- config/locales/server.en.yml
- lib/ai_bot/tools/create_artifact.rb
- spec/lib/modules/ai_bot/tools/create_artifact_spec.rb
- spec/requests/ai_bot/artifacts_controller_spec.rb
1. Keep source in a "details" block after rendered so it does
not overwhelm users
2. Ensure artifacts are never indexed by robots
3. Cache break our CSS that changed recently
> DEV: improve artifact presentation

- assets/javascripts/discourse/components/ai-topic-gist.gjs
- assets/stylesheets/modules/summarization/common/ai-gists.scss
This makes the summaries occupy the full width, so short category names won't wrap after them 
before:
after:
> UX: ensure gists occupy full row

- assets/stylesheets/modules/summarization/common/ai-gists.scss
> UX: force long words to break in topic list gists

- lib/sentiment/emotion_filter_order.rb
The `if` clause, that is only there because of unit testing, was too broad and broke functionality.
> FIX: Properly capture period for /filter emotion ordering

- app/controllers/discourse_ai/ai_bot/shared_ai_conversations_controller.rb
- app/helpers/discourse_ai/ai_bot/shared_ai_conversations_helper.rb
- app/views/discourse_ai/ai_bot/shared_ai_conversations/show.html.erb
- config/routes.rb
- plugin.rb
- spec/requests/ai_bot/shared_ai_conversations_controller_spec.rb
CDNs can be configured to strip query params in Discourse
hosting. This is generally safe, but in this case we had
no way of busting the cache using the path.
New design properly caches and properly breaks busts the
cache if asset changes so we don't need to worry about versions
> FIX: automatically bust cache for share ai assets

- lib/summarization/entry_point.rb
- spec/lib/modules/summarization/entry_point_spec.rb
Topics with a summary that is not a gist are currently excluded from the topic list. This PR temporarily removes the bug while we investigate.
> FIX: disables temporarily ai_summaries filtering

- lib/summarization/entry_point.rb
- spec/lib/modules/summarization/entry_point_spec.rb
The `topic_query_create_list_topics` modifier we append was always meant to avoid an N+1 situation when serializing gists. However, I tried to be too smart and only preload these, which resulted in some topics with *only* regular summaries getting removed from the list. This issue became apparent now we are adding gists to other lists besides hot.
Let's simplify the preloading, which still solves the N+1 issue, and let the serializer get the needed summary.
> FIX: Unnecessary complex preloading accidentally filters some topics.

- app/models/completion_prompt.rb
- db/fixtures/ai_helper/603_completion_prompts.rb
- spec/lib/modules/ai_helper/assistant_spec.rb
- spec/plugin_spec.rb
To allow https://github.com/discourse/discourse-translator/pull/181 to work, we're adding a `detect_text_locale` prompt which will return locales like "en", "de", "en-GB", "pt-PT".
> FEATURE: Add locale detection prompt from translator

- lib/ai_bot/entry_point.rb
This icon is not part of the core set. Previously, d-ai was relying on other installed plugins (e.g. data-explorer) to include the icon
> FIX: Correctly register 'info' icon

- lib/embeddings/vector_representations/all_mpnet_base_v2.rb
- lib/embeddings/vector_representations/base.rb
- lib/embeddings/vector_representations/bge_large_en.rb
- lib/embeddings/vector_representations/bge_m3.rb
- lib/embeddings/vector_representations/gemini.rb
- lib/embeddings/vector_representations/multilingual_e5_large.rb
- lib/embeddings/vector_representations/text_embedding_3_large.rb
- lib/embeddings/vector_representations/text_embedding_3_small.rb
- lib/embeddings/vector_representations/text_embedding_ada_002.rb
- lib/inference/cloudflare_workers_ai.rb
- lib/inference/discourse_classifier.rb
- lib/inference/gemini_embeddings.rb
- lib/inference/hugging_face_text_embeddings.rb
- lib/inference/open_ai_embeddings.rb
- lib/nsfw/classification.rb
- lib/toxicity/toxicity_classification.rb
- spec/shared/inference/openai_embeddings_spec.rb
Two changes worth mentioning:
1. `.instance` returns a fully configured embedding endpoint ready to use. 
2. All endpoints respond to the same method and have the same signature - `perform!(text)`. It's no longer a class method.
This makes it easier to reuse them when generating embeddings in bulk.
> REFACTOR: Tidy-up embedding endpoints config.

- config/locales/server.en.yml
- lib/ai_bot/playground.rb
- lib/automation.rb
- lib/automation/llm_triage.rb
- spec/lib/modules/ai_bot/playground_spec.rb
- spec/lib/modules/automation/llm_triage_spec.rb
This PR contains 2 features: 
1. The ability to @mention an LLM after a conversation started, this allows you to switch LLMs mid stream
2. The ability to automatically silence a user that was triaged as a spammer
> FEATURE: LLM mentions and auto silence

- spec/lib/modules/ai_bot/personas/persona_spec.rb
This spec fails inconsistently with:
-fragment-n14
+You are a helpful Discourse assistant.
+You _understand_ and **generate** Discourse Markdown.
+You live in a Discourse Forum Message.
+
+You live in the forum with the URL: http://test.localhost
+The title of your site: test site title
+The description is: test site description
+The participants in this conversation are: joe, jane
+The date now is: 2024-11-25 20:23:02 UTC, much has changed since you were trained.
+
+You were trained on OLD data, lean on search to get up to date information about this forum
+When searching try to SIMPLIFY search terms
+Discourse search joins all terms with AND. Reduce and simplify terms to find more results.<guidance>
+The following texts will give you additional guidance for your response.
+We included …
> DEV: skip flakey spec

- app/jobs/scheduled/embeddings_backfill.rb
- lib/embeddings/vector_representations/base.rb
- lib/embeddings/vector_representations/multilingual_e5_large.rb
- spec/lib/modules/embeddings/vector_representations/vector_rep_shared_examples.rb
We are adding a new method for generating and storing embeddings in bulk, which relies on `Concurrent::Promises::Future`. Generating an embedding consists of three steps:
- Prepare text
- HTTP call to retrieve the vector
- Save to DB.
Second one is independently executed on whatever thread the pool gives us.
We are bringing a custom thread pool instead of the global executor since we want control over how many threads we spawn to limit concurrency. We also avoid firing thousands of HTTP requests when working with large batches.
Ran benchmarks locally with the following script:
```ruby
def benchmark_embeddings
ActiveRecord::Base.logger.level = 1 # or Logger::INFO
truncation = DiscourseAi::Embeddings::Strategies::Truncation.new
vector_rep = …
```
> DEV: Backfill embeddings concurrently.

- config/locales/client.en.yml
- discourse_automation/llm_triage.rb
- spec/lib/discourse_automation/llm_triage_spec.rb
Usually people do not want to scan personal messages. Sometimes
they may. In that case they can enable triage on personal messages.
> FEATURE: Skip PM scanning in LLM triage by default

- lib/ai_helper/assistant.rb
With the recent changes to allow Discourse AI in the translator plugin (https://github.com/discourse/discourse-ai/pull/946), `detect_text_locale` was needed as a `CompletionPrompt`. However, it is leaking into composer/post helper menus. This PR ensures we don't not show it in those menus.
> DEV: Prevent `detect_text_locale` from appearing in menus

- assets/javascripts/initializers/related-topics.gjs
See https://meta.discourse.org/t/related-topics-missing-after-rereading-a-topic-with-more-than-20-posts/306147/6
> FIX: Keep related topics data cached when a user scrolls up

- app/jobs/regular/post_sentiment_analysis.rb
- lib/inference/hugging_face_text_embeddings.rb
- lib/sentiment/post_classification.rb
- lib/tasks/modules/sentiment/backfill.rake
- spec/lib/modules/sentiment/post_classification_spec.rb
This change adds a simpler class for sentiment classification, replacing the soon-to-be removed `Classificator` hierarchy. Additionally, it adds a method for classifying concurrently, speeding up the backfill rake task.
> REFACTOR: Simplify sentiment classification

- admin/assets/javascripts/discourse/routes/admin-plugins-show-discourse-ai-usage.js
- admin/assets/javascripts/discourse/templates/admin-plugins/show/discourse-ai-usage.hbs
- app/controllers/discourse_ai/admin/ai_usage_controller.rb
- app/models/ai_api_audit_log.rb
- app/serializers/ai_usage_serializer.rb
- assets/javascripts/discourse/admin-discourse-ai-plugin-route-map.js
- assets/javascripts/discourse/components/ai-usage.gjs
- assets/javascripts/initializers/admin-plugin-configuration-nav.js
- assets/stylesheets/modules/llms/common/usage.scss
- config/locales/client.en.yml
- config/routes.rb
- db/migrate/20241128010221_add_cached_tokens_to_ai_api_audit_log.rb
- lib/ai_bot/bot.rb
- lib/ai_bot/playground.rb
- lib/completions/endpoints/open_ai.rb
- lib/completions/open_ai_message_processor.rb
- lib/completions/report.rb
- plugin.rb
- spec/fixtures/bot/openai_artifact_call.txt
- spec/lib/completions/endpoints/open_ai_spec.rb
- spec/lib/modules/ai_bot/playground_spec.rb
- spec/requests/admin/ai_usage_controller_spec.rb
Provides a new usage page for AI so admins can easily tell what AI features / models and users are consuming tokens on the forum.
> FEATURE: AI Usage page

- lib/ai_helper/semantic_categorizer.rb
- lib/embeddings/vector_representations/base.rb
- spec/lib/modules/ai_helper/semantic_categorizer_spec.rb
- spec/lib/modules/embeddings/vector_representations/vector_rep_shared_examples.rb
The logic here is that users do not particularly care about
topics in the category so we can exclude them from tag
and category suggestions
> FEATURE: exclude muted categories from category suggester

- db/migrate/20241129190708_fix_classification_data.rb
- lib/sentiment/post_classification.rb
- spec/lib/modules/sentiment/post_classification_spec.rb
We were storing the classification result in a slightly different format:
```ruby
[{"label"=>"positive", "score"=>0.830914}, {"label"=>"neutral", "score"=>0.16409673}, {"label"=>"negative", "score"=>0.0049892818}]
```
when it should be:
```ruby
{"neutral"=>0.52367204, "negative"=>0.014189002, "positive"=>0.46213892}
```
> FIX: Transform Sentiment classification before saving

- config/locales/client.en.yml
The description of the automatic captions dialog prompt included "Would you like to enable automatic auto captions on image uploads." I removed the second "auto" at the suggestion of translators.
> changed "automatic auto" to "auto" in client.en.yml

- app/jobs/scheduled/summaries_backfill.rb
- config/settings.yml
- spec/jobs/scheduled/summaries_backfill_spec.rb
- spec/lib/modules/summarization/entry_point_spec.rb
- makes visible to everyone by default
- backfills gists before full summaries
- adds configurable max age setting to backfill job
> FEATURE: Adjustments to gist summaries

- app/controllers/discourse_ai/ai_bot/artifacts_controller.rb
- app/models/ai_artifact.rb
- app/models/ai_artifact_version.rb
- app/models/shared_ai_conversation.rb
- assets/javascripts/discourse/components/ai-artifact.gjs
- assets/javascripts/initializers/ai-artifacts.gjs
- assets/javascripts/lib/discourse-markdown/ai-tags.js
- config/locales/server.en.yml
- config/routes.rb
- db/migrate/20241130003808_add_artifact_versions.rb
- lib/ai_bot/personas/persona.rb
- lib/ai_bot/personas/web_artifact_creator.rb
- lib/ai_bot/tool_runner.rb
- lib/ai_bot/tools/create_artifact.rb
- lib/ai_bot/tools/update_artifact.rb
- lib/summarization/strategies/topic_summary.rb
- lib/utils/diff_utils.rb
- lib/utils/dns_srv.rb
- spec/lib/modules/ai_bot/tools/update_artifact_spec.rb
- spec/lib/utils/diff_utils_spec.rb
- spec/requests/ai_bot/artifacts_controller_spec.rb
Add support for versioned artifacts with improved diff handling
* Add versioned artifacts support allowing artifacts to be updated and tracked
- New `ai_artifact_versions` table to store version history
- Support for updating artifacts through a new `UpdateArtifact` tool
- Add version-aware artifact rendering in posts
- Include change descriptions for version tracking
* Enhance artifact rendering and security
- Add support for module-type scripts and external JS dependencies
- Expand CSP to allow trusted CDN sources (unpkg, cdnjs, jsdelivr, googleapis)
- Improve JavaScript handling in artifacts
* Implement robust diff handling system (this is dormant but ready to use once LLMs catch up)
- Add new DiffUtils module for applying changes to artifacts
- Support for unified diff format with …
> FEATURE: allow artifacts to be updated

- assets/javascripts/discourse/components/suggestion-menus/ai-tag-suggester.gjs
- lib/ai_helper/semantic_categorizer.rb
- spec/system/ai_helper/ai_composer_helper_spec.rb
This PR fixes an issue where the tag suggester for edit title topic area was suggesting tags that are already assigned on a post. It also updates the amount of suggested tags to 7 so that there is still a decent amount of tags suggested when tags are already assigned.
> FIX: Tag suggester is suggesting already assigned tags

- config/locales/server.en.yml
translators gave feedback that the phrase "contact this model" is confusing. changed it to "use this model".
> changed "contact this model to "use this model"  server.en.yml

- app/models/completion_prompt.rb
- spec/models/completion_prompt_spec.rb
For a while now we have not been sending the examples to AI
helper, which can lead to inconsistent results.
Note: this also means that in non English we did not send
English results, so this may end up reducing performance
That said first thing we need to do is fix the regression.
> FIX: regression, no longer sending examples to AI helper

- assets/javascripts/discourse/components/modal/ai-summary-modal.gjs
- assets/javascripts/discourse/connectors/topic-map-expanded-after/ai-summary-trigger.gjs
- assets/stylesheets/modules/summarization/common/ai-gists.scss
- assets/stylesheets/modules/summarization/common/ai-summary.scss
- assets/stylesheets/modules/summarization/desktop/ai-summary.scss
- assets/stylesheets/modules/summarization/mobile/ai-summary.scss
- plugin.rb
- spec/system/page_objects/components/ai_summary_box.rb
- spec/system/summarization/topic_summarization_spec.rb
- test/javascripts/acceptance/topic-summary-test.js
This doesn't change the appearance much, but gets us some functionality for free that we don't get with DMenu, like a header and being able to keep the summary open along with infinite scroll within topics. 
Before:
After:
> UX: move topic summary from DMenu to DModal

- assets/javascripts/discourse/components/ai-llm-editor-form.gjs
This PR updates deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.
> DEV: Update deprecated Font Awesome icon names

- assets/javascripts/discourse/components/suggestion-menus/ai-category-suggester.gjs
- assets/javascripts/discourse/components/suggestion-menus/ai-tag-suggester.gjs
- assets/javascripts/discourse/components/suggestion-menus/ai-title-suggester.gjs
- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
Along with this core PR https://github.com/discourse/discourse/pull/30109 this improves the layout of AI buttons in the inline title editing and composer
Before:
After:
> UX: improve layout of inline title editing buttons

- assets/javascripts/discourse/components/ai-topic-gist.gjs
`esacpedExceprt !== escapedExcerpt` 🤦🏻‍♂️
> FIX: typo in topic gist for escapedExcerpt

- app/models/reviewable_ai_chat_message.rb
- app/models/reviewable_ai_post.rb
- assets/javascripts/discourse/components/ai-helper-loading.gjs
- assets/javascripts/discourse/components/ai-llm-editor-form.gjs
- assets/javascripts/discourse/components/ai-persona-editor.gjs
- assets/javascripts/discourse/components/ai-post-helper-menu.gjs
- assets/javascripts/discourse/components/ai-tool-editor.gjs
- assets/javascripts/discourse/components/ai-tool-parameter-editor.gjs
- assets/javascripts/discourse/components/modal/ai-summary-modal.gjs
- assets/javascripts/discourse/components/modal/share-full-topic-modal.gjs
- assets/javascripts/discourse/components/rag-options.gjs
- assets/javascripts/discourse/components/rag-uploader.gjs
This PR updates more deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.
> DEV: Update more deprecated Font Awesome icon names

- lib/completions/dialects/chat_gpt.rb
- lib/completions/dialects/claude.rb
- lib/completions/dialects/command.rb
- lib/completions/dialects/dialect.rb
- lib/completions/dialects/fake.rb
- lib/completions/dialects/gemini.rb
- lib/completions/dialects/mistral.rb
- lib/completions/dialects/nova.rb
- lib/completions/dialects/nova_tools.rb
- lib/completions/dialects/ollama.rb
- lib/completions/dialects/open_ai_compatible.rb
- lib/completions/endpoints/aws_bedrock.rb
- lib/completions/llm.rb
- lib/completions/nova_message_processor.rb
- spec/fabricators/llm_model_fabricator.rb
- spec/lib/completions/dialects/claude_spec.rb
- spec/lib/completions/dialects/nova_spec.rb
- spec/lib/completions/endpoints/aws_bedrock_spec.rb
- spec/lib/completions/endpoints/nova_spec.rb
Refactor dialect selection and add Nova API support
* Change dialect selection to use `llm_model` object instead of just provider name
* Add support for Amazon Bedrock's Nova API with native tools
* Implement Nova-specific message processing and formatting
* Update specs for Nova and AWS Bedrock endpoints
* Enhance AWS Bedrock support to handle Nova models
* Fix Gemini beta API detection logic
> FEATURE: Amazon Nova support via bedrock

- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
> UX: ensure composer popup is always above AI icons

- app/models/ai_api_audit_log.rb
- app/models/llm_model.rb
- assets/javascripts/discourse/components/ai-artifact.gjs
- assets/stylesheets/modules/ai-bot/common/ai-artifact.scss
- config/locales/client.en.yml
- config/locales/server.en.yml
- lib/ai_bot/playground.rb
- lib/completions/dialects/chat_gpt.rb
- lib/completions/endpoints/base.rb
- lib/completions/endpoints/open_router.rb
- lib/completions/llm.rb
- lib/summarization/strategies/hot_topic_gists.rb
- lib/summarization/strategies/topic_summary.rb
- spec/fabricators/llm_model_fabricator.rb
- spec/lib/completions/endpoints/open_router_spec.rb
This new implementation supports picking quantization and provider pref
Also:
- Improve logging for summary generation
- Improve error message when contacting LLMs fails
> FEATURE: first class support for OpenRouter

- app/controllers/discourse_ai/admin/ai_usage_controller.rb
- assets/javascripts/discourse/components/ai-usage.gjs
- assets/stylesheets/modules/llms/common/usage.scss
- config/locales/client.en.yml
- config/routes.rb
- lib/completions/report.rb
- spec/requests/admin/ai_usage_controller_spec.rb
This commit makes several UX improvements along with code cleanup
for the new AI usage page:
* Ensure all text uses I18n
* Change from <button> usage to <DButton>
* Use <AdminConfigAreaCard> in place of custom card styles
* Format numbers nicely using our number format helper,
show full values on hover using title attr
* Add empty data placeholders in each card
* Move the users list below the per feature/per model cards,
and split it into 2 columns when there are > 25 users
* Add subheader for usage page with "Learn more..." link
Also, it improves the load experience of the page. Previously
we loaded all the report data up front on the server when the
admin visited this usage route which caused a white screen
in some cases and could take quite long.
Now, we show loading spinners for the …
> UX: Improve rough edges of AI usage page

- lib/ai_moderation/spam_scanner.rb
- spec/requests/admin/ai_spam_controller_spec.rb
When a post is trashed we should still be allowed to scan it
post.topic will be nil for a trashed topic even if post is trashed
> FIX: allow scanning of trashed posts and deleted users for test

- assets/javascripts/discourse/components/ai-spam.gjs
- assets/javascripts/discourse/components/ai-usage.gjs
- assets/stylesheets/modules/llms/common/spam.scss
- assets/stylesheets/modules/llms/common/usage.scss
- config/locales/client.en.yml
For the Spam and Usage tabs in AI:
> UX: Use new DStatTiles reusable component from core

- assets/javascripts/discourse/connectors/full-page-search-below-search-header/semantic-search.gjs
- assets/stylesheets/modules/embeddings/common/semantic-search.scss
- config/locales/client.en.yml
- lib/embeddings/entry_point.rb
- plugin.rb
This PR adds an "unavailable" state for the AI semantic search toggle. Currently the AI toggle disappears when the sort by is anything but `Relevance` which makes the UI confusing for users looking for AI results. This should help!
Note there are no specs for this feature. I'm not sure what the LLM extraction mentioned here _is_, so I didn't touch it.
https://github.com/discourse/discourse-ai/blob/534b0df391ad6d1ae54c6674453aec5a6c69203f/spec/system/embeddings/semantic_search_spec.rb#L42-L48
No UI change for regular ol' searching
But when a different sort order is selected, we now have an unavailable state with a tooltip explaining
> FEATURE: Unavailable state for semantic search when sort is not Relevant

- app/serializers/ai_spam_serializer.rb
- assets/javascripts/discourse/components/ai-spam.gjs
- lib/ai_moderation/entry_point.rb
- lib/ai_moderation/spam_report.rb
- spec/requests/admin/reviewable_controller_spec.rb
- Add `spam_score_type` to `AiSpamSerializer` for better integration with reviewables.
- Introduce a custom filter for detecting AI spam false negatives in moderation workflows.
- Refactor spam report generation to improve identification of false negatives.
- Add tests to verify the custom filter and its behavior.
- Introduce links for all spam counts in report
> FEATURE: link correctly to filters to assist in debugging spam

- assets/javascripts/discourse/components/ai-llms-list-editor.gjs
- assets/javascripts/discourse/components/ai-persona-list-editor.gjs
- assets/javascripts/discourse/components/ai-spam.gjs
- assets/javascripts/discourse/components/ai-tool-list-editor.gjs
- assets/javascripts/discourse/components/ai-usage.gjs
- spec/system/admin_ai_persona_spec.rb
- spec/system/ai_bot/tool_spec.rb
- spec/system/llms/ai_llm_spec.rb
Previously was AdminPageSubheader until https://github.com/discourse/discourse/pull/30146
> DEV: Change to use DPageSubheader

- assets/javascripts/discourse/components/ai-llms-list-editor.gjs
- assets/stylesheets/modules/llms/common/ai-llms-editor.scss
The heading w/ description feels like it should be a level above the tables here.
I also adjusted the tables themselves, they're not clickable so they shouldn't highlight on hover... and the left/right padding has been removed to better align with content above/below
Before:
After:
> UX: minor improvements to LLM page and admin tables

- lib/ai_bot/response_http_streamer.rb
Previous version was prone to the bug:
https://github.com/ruby-concurrency/concurrent-ruby/issues/1075
This is particularly bad cause we could have a DB connection
attached to the thread and we never clear it up, so after N hours
this could start exhibiting weird connection issues.
> FIX: properly spin down unused streamer threads

- lib/inference/cloudflare_workers_ai.rb
- spec/lib/inference/cloudflare_workers_ai_spec.rb
> FIX: Cloudflare Workers AI embeddings

- assets/javascripts/discourse/components/ai-llms-list-editor.gjs
- assets/stylesheets/modules/llms/common/ai-llms-editor.scss
- config/locales/client.en.yml
- spec/system/llms/ai_llm_spec.rb
This adds a description for the CDCK preseeded LLMs so we can see the model, and also adds a disabled edit button with a tooltip explanation. 
Before:
After:
> UX: disabled preseeded edit button, add description

- lib/configuration/llm_enumerator.rb
- spec/requests/admin/ai_spam_controller_spec.rb
The `allowed_seeded_llms` array which is a map of a list type setting (`ai_spam_detection_model_allowed_seeded_models_map`) includes only a string of LLM IDs and not the `custom` prefix. However, our check in the LLM enumerator was comparing against it with the prefix, thus causing seeded LLMs to never be shown.
> FIX: Custom prefix causing allowed seeded LLMs not to be shown

- lib/configuration/llm_enumerator.rb
- spec/configuration/llm_enumerator_spec.rb
This PR fixes an issue where LLM enumerator would error out when `SiteSetting.ai_spam_detection = true` but there was no `AiModerationSetting.spam` present.
Typically, we add an `LlmDependencyValidator` for the setting itself, however, since Spam is unique in that it has it's model set in `AiModerationSetting` instead of a `SiteSetting`, we'll add a simple check here to prevent erroring out.
This PR also adds a missing test for the `LlmEnumerator`
> FIX: Prevent LLM enumerator from erroring when spam enabled

- config/locales/server.en.yml
- lib/ai_moderation/spam_scanner.rb
- spec/lib/modules/ai_moderation/spam_scanner_spec.rb
Previously reason was blank for silencing user
> FIX: keep track of silence reason when spam detection flags user

- config/locales/server.en.yml
- db/fixtures/ai_helper/603_completion_prompts.rb
- lib/ai_helper/assistant.rb
- lib/ai_helper/date_formatter.rb
- spec/lib/modules/ai_helper/assistant_spec.rb
- spec/lib/modules/ai_helper/date_formatter_spec.rb
- spec/plugin_spec.rb
This feature allows conversion of human typed in dates and times
to smart "Discourse" timezone friendly dates.
> FEATURE: smart date support for AI helper

- assets/javascripts/discourse/components/ai-full-page-search.gjs
- assets/javascripts/discourse/connectors/full-page-search-below-search-header/ai-full-page-search.gjs
- assets/stylesheets/modules/embeddings/common/semantic-search.scss
- config/locales/client.en.yml
This PR adds the tooltip when AI search is enabled with a valid sort order as well as when disabled.
It also makes the tooltip icon a little smaller, and moderizes the use of `I18n.t -> i18n` to avoid double imports.
> UX: Full page search -- always show tooltip & add msg

- assets/javascripts/discourse/components/ai-full-page-search.gjs
This PR adds appEvents triggers when Ai search results are toggled.
> DEV: Add appEvents trigger when Ai search results toggled

- app/controllers/discourse_ai/ai_bot/artifacts_controller.rb
- app/models/llm_model.rb
- config/locales/client.en.yml
- lib/completions/endpoints/base.rb
- lib/completions/endpoints/open_ai.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
When sharing artifacts on mobile we had no viewport tag so
text would be TINY
> FIX: add viewport so artifacts render correctly on mobile

- db/migrate/20241230153300_new_embeddings_tables.rb
- db/post_migrate/20250113171444_drop_old_embedding_tables.rb
- lib/embeddings/schema.rb
`model_id` will become the ID of an AR model when configurable embeddings land.
> DEV: Embedding tables' model_id has to be a bigint

- db/post_migrate/20250114184356_drop_old_embedding_tables2.rb
Tables were already dropped on some sites. We need to check there's something left to migrate.
> FIX: Missing table check in post_migration

- lib/ai_moderation/spam_scanner.rb
- spec/lib/modules/ai_moderation/spam_scanner_spec.rb
When enabling spam scanner it there may be old unscanned posts
this can create a risky situation where spam scanner operates
on legit posts during false positives
To keep this a lot safer we no longer try to hide old stuff by
the spammers.
> FIX: only hide posts detected explicitly as spam

- app/jobs/regular/fast_track_topic_gist.rb
- app/jobs/scheduled/summaries_backfill.rb
- app/models/ai_summary.rb
- app/serializers/ai_topic_summary_serializer.rb
- db/migrate/20250115173456_add_highest_target_number_to_ai_summary.rb
- db/post_migrate/20250115181147_drop_ai_summaries_content_range.rb
- lib/summarization/fold_content.rb
- lib/summarization/strategies/chat_messages.rb
- lib/summarization/strategies/hot_topic_gists.rb
- lib/summarization/strategies/topic_summary.rb
- spec/fabricators/ai_summary_fabricator.rb
- spec/jobs/scheduled/summaries_backfill_spec.rb
- spec/lib/guardian_extensions_spec.rb
- spec/requests/summarization/summary_controller_spec.rb
- spec/services/discourse_ai/topic_summarization_spec.rb
- spec/system/summarization/topic_summarization_spec.rb
To quickly select backfill candidates without comparing SHAs, we compare the last summarized post to the topic's highest_post_number. However, hiding or deleting a post and adding a small action will update this column, causing the job to stall and re-generate the same summary repeatedly until someone posts a regular reply. On top of this, this is not always true for topics with `best_replies`, as this last reply isn't necessarily included.
Since this is not evident at first glance and each summarization strategy picks its targets differently, I'm opting to simplify the backfill logic and how we track potential candidates.
The first step is dropping `content_range`, which serves no purpose and it's there because summary caching was supposed to work differently at the beginning. So …
> FIX: Make summaries backfill job more resilient.

- app/models/ai_summary.rb
- db/migrate/20250115173456_add_highest_target_number_to_ai_summary.rb
We'll later copy the correct value from content_range. 1 should be the min highest post number a topic has.
> FIX: Set default for existing summaries' new column.

- app/models/reviewable_ai_chat_message.rb
- app/models/reviewable_ai_post.rb
- assets/javascripts/discourse/components/ai-llm-quota-editor.gjs
- assets/javascripts/initializers/ai-bot-replies.js
Noticed "share-alt" come into the site logs, and checked this repo for deprecated icon names with that suffix. Also looked at args to `icon`, this should complete the FA6 icon upgrade for this plugin 😅 .
For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.
> DEV: update more deprecated icon names

- lib/ai_moderation/spam_scanner.rb
- spec/lib/modules/ai_moderation/spam_scanner_spec.rb
This adds registration and last known IP information and email to scanning context.
This provides another hint for spam scanner about possible malicious users.
For example registered in India, replying from Australia or
email is clearly a throwaway email address.
> FEATURE: Add user location info to spam scanner context

- app/controllers/discourse_ai/admin/ai_embeddings_controller.rb
- app/models/embedding_definition.rb
- app/serializers/ai_embedding_definition_serializer.rb
- assets/javascripts/discourse/admin/models/ai-embedding.js
- assets/javascripts/discourse/components/ai-embedding-editor.gjs
- config/locales/client.en.yml
- db/migrate/20250121162520_configurable_embeddings_prefixes.rb
- lib/embeddings/strategies/truncation.rb
- spec/lib/modules/embeddings/strategies/truncation_spec.rb
- spec/requests/admin/ai_embeddings_controller_spec.rb
- spec/system/embeddings/ai_embedding_definition_spec.rb
Additionally, we add a prefix for embedding generation.
Both are stored in the definitions table.
> FIX: Restore the accidentally deleted query prefix.

- app/models/embedding_definition.rb
- spec/lib/modules/embeddings/vector_spec.rb
- spec/requests/embeddings/embeddings_controller_spec.rb
API ref: https://platform.openai.com/docs/api-reference/embeddings/create#embeddings-create-dimensions
Meta report: https://meta.discourse.org/t/openais-text-embedding-ada-002-error-embedding-dimensions/348244
> FIX: Open AI embedding shortening is only available for some models

- db/migrate/20250110114305_embedding_config_data_migration.rb
Fix embedding config migration
Fix "can't quote Array" error by converting provider_params to json string before saving to database. 
This fixes the setup of OpenAI text embeddings.
> FIX: convert provider_params hash to json before db insert

- app/controllers/discourse_ai/admin/ai_embeddings_controller.rb
- app/models/embedding_definition.rb
- app/serializers/ai_embedding_definition_serializer.rb
- assets/javascripts/discourse/admin/models/ai-embedding.js
- assets/javascripts/discourse/components/ai-embedding-editor.gjs
- assets/stylesheets/modules/embeddings/common/ai-embedding-editor.scss
- config/locales/client.en.yml
- db/migrate/20250122131007_matryoshka_dimensions_support.rb
- spec/lib/modules/embeddings/vector_spec.rb
- spec/requests/admin/ai_embeddings_controller_spec.rb
We have a flag to signal we are shortening the embeddings of a model. Only used in Open AI's text-embedding-3-*, but we plan to use it for other services.
> FEATURE: Formalize support for matryoshka dimensions.

- app/models/ai_api_audit_log.rb
- db/migrate/20250122003035_add_duration_to_ai_api_log.rb
- lib/completions/endpoints/base.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
Tracks duration_msec (milliseconds) for all AI LLM completions. 
This assists in debugging performance issues with LLMs
> FEATURE: track duration of AI calls

- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
Followup to https://github.com/discourse/discourse-ai/pull/1064
That commits adds a higher z-index due to core changes, we no longer need an iPad-specific z-index.
> UX: Fix composer helper z-index

- assets/javascripts/initializers/admin-plugin-configuration-nav.js
Embeddings as the tab you land on when visiting the AI plugin admin page didn't make much sense... this treats usage as a dashboard for it instead
Before:
After:
> UX: set usage as first AI admin tab instead of embeddings

- db/migrate/20250125162658_fix_broken_open_ai_embeddings_config.rb
- db/migrate/20250127145305_clean_unused_embedding_search_indexes.rb
- spec/db/migrate/20250125162658_fix_broken_open_ai_embeddings_config_spec.rb
- spec/db/migrate/20250127145305_clean_unused_embedding_search_indexes_spec.rb
This change fixes two different problems.
First, we add a data migration to migrate the configuration of sites using Open AI's embedding model. There was a window between the embedding config changes and #1087, where sites could end up in a broken state due to an unconfigured selected model setting, as reported on https://meta.discourse.org/t/-/348964
The second fix drops pre-seeded search indexes of the models we didn't migrate and corrects the ones where the dimensions don't match. Since the index uses the model ID, new embedding configs could use one of these ones even when the dimensions no longer match.
> FIX:  Open AI embeddings config migration & Seeded indexes cleanup

- assets/javascripts/discourse/connectors/topic-map-expanded-after/ai-summary-trigger.gjs
The summarize button shown above uses the default button styling, but is missing the `btn-default` class, making it inconsistent in themes
> DEV: add missing class to summarize button

- assets/javascripts/initializers/admin-reports.js
Introduced in https://github.com/discourse/discourse/pull/31011
> DEV: Use new core plugin API to register report mode

- app/models/llm_model.rb
- assets/javascripts/discourse/components/ai-llm-editor-form.gjs
- config/locales/client.en.yml
- lib/completions/dialects/chat_gpt.rb
- lib/completions/endpoints/open_ai.rb
- lib/completions/llm.rb
1. Adds o3-mini presets
2. Adds support for reasoning effort
3. properly use "developer" messages for reasoning models
> FEATURE: o3-mini support

- assets/javascripts/discourse/connectors/composer-fields/persona-llm-selector.gjs
- lib/completions/endpoints/base.rb
Reasoning models such as o3 mini require a much longer timeout, bump timeout from 1 to 6 minutes.
Reasoning models can be configured multiple times as llms, model_name is not unique, do not base selectors on model name, use id instead
> FEATURE: improve o3-mini support

- lib/ai_bot/tools/update_artifact.rb
- lib/utils/diff_utils/simple_diff.rb
- spec/lib/utils/diff_utils/simple_diff_spec.rb
(this is needed for very simple diffs and HTML)
> FIX: need to be able to search replace within lines

- assets/javascripts/discourse/components/ai-llm-editor-form.gjs
This change has been forgotten in https://github.com/discourse/discourse-ai/commit/40e996b174332030762b29c4fb80557aa9c9151c
> UX: include none false for provider params

- app/jobs/scheduled/summaries_backfill.rb
- lib/summarization/fold_content.rb
- lib/summarization/strategies/chat_messages.rb
- lib/summarization/strategies/hot_topic_gists.rb
- lib/summarization/strategies/topic_summary.rb
- spec/jobs/scheduled/summaries_backfill_spec.rb
- spec/lib/modules/summarization/fold_content_spec.rb
Before this change, a summary was only outdated when new content appeared, for topics with "best replies", when the query returned different results. The intent behind this change is to detect when a summary is outdated as a result of an edit.
Additionally, we are changing the backfill candidates query to compare "ai_summary_backfill_topic_max_age_days" against "last_posted_at" instead of "created_at", to catch long-lived, active topics. This was discussed here: https://meta.discourse.org/t/ai-summarization-backfill-is-stuck-keeps-regenerating-the-same-topic/347088/14?u=roman_rizzi
> FEATURE: Changes to summaries' outdated logic.

- app/models/ai_spam_log.rb
- db/migrate/20250211021037_add_error_to_ai_spam_log.rb
- lib/ai_moderation/spam_scanner.rb
- lib/automation/llm_triage.rb
- spec/lib/modules/ai_moderation/spam_scanner_spec.rb
- spec/lib/modules/automation/llm_triage_spec.rb
Currently in core re-flagging something that is already flagged as spam
is not supported, long term we may want to support this but in the meantime
we should not be silencing/hiding if the PostActionCreator fails
when flagging things as spam.
> FIX: Check post action creator result when flagging spam

- app/jobs/scheduled/embeddings_backfill.rb
When you already have embeddings for a model stored and change models,
our backfill script was failing to backfill the newly configured model.
Regression introduced most likely in 1686a8a
> FIX: Embeddings backfill job compat when transitioning models

- assets/javascripts/discourse/lib/ai-bot-helper.js
Very small change to draft key to assign proper draft title and icon within core drafts list and dropdown menu. The draft key for each PM with AI Bot will now be unique, allowing multiple drafts.
I've also removed the now redundant `skipDraftCheck` from the multiple drafts work carried out in core.
Internal ref: /t/120592
> FIX: update draft key for new PM with AI bot

- assets/javascripts/discourse/components/ai-llm-editor-form.gjs
- spec/system/llms/ai_llm_spec.rb
Prior to this commit, editing the provider wouldn't recompute the provider params. It would also not correctly recompute the "canEditURL" property.
To make possible this commit has:
- made a fix in core: https://github.com/discourse/discourse/pull/31329
- ensures the provider params are recomputed when provider is changed
- made the check on `canEditURL` based on form state and not initial model value
Tests have been added to confirm the expected behavior.
> FIX: correctly handle provider edit

- evals/lib/eval.rb
- lib/completions/anthropic_message_processor.rb
Also fixes anthropic with no params, streaming calls
> DEV: eval support for tool calls

- spec/lib/utils/pdf_to_text_spec.rb
CI=1 is not set on our internal build system,
we need to fix that but for now let's unblock the build
> DEV: Skip PDF tests

- README.md
- app/models/ai_artifact_version.rb
- evals/lib/eval.rb
- evals/lib/runner.rb
- lib/ai_bot/artifact_update_strategies/diff.rb
- lib/utils/diff_utils/simple_diff.rb
- spec/fabricators/ai_artifact_fabricator.rb
- spec/lib/modules/ai_bot/artifact_update_strategies/diff_spec.rb
- spec/lib/modules/ai_bot/tools/update_artifact_spec.rb
- spec/lib/utils/diff_utils/simple_diff_spec.rb
- Add non-contiguous search/replace support using ... syntax
- Add judge support for evaluating LLM outputs with ratings
- Improve error handling and reporting in eval runner
- Add full section replacement support without search blocks
- Add fabricators and specs for artifact diffing
- Track failed searches to improve debugging
- Add JS syntax validation for artifact versions in eval system
- Update prompt documentation with clear guidelines
> DEV: improve artifact editing and eval system

- lib/completions/endpoints/open_ai.rb
- lib/completions/endpoints/open_router.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
max_tokens is now deprecated per API
> FIX: use max_completion_tokens for open ai models

- lib/ai_helper/semantic_categorizer.rb
- lib/embeddings/schema.rb
- spec/system/ai_helper/ai_composer_helper_spec.rb
- spec/system/ai_helper/ai_split_topic_suggestion_spec.rb
From [pgvector/pgvector](https://github.com/pgvector/pgvector) README
> With approximate indexes, filtering is applied after the index is scanned. If a condition matches 10% of rows, with HNSW and the default hnsw.ef_search of 40, only 4 rows will match on average. For more rows, increase hnsw.ef_search.
> 
> Starting with 0.8.0, you can enable [iterative index scans](https://github.com/pgvector/pgvector#iterative-index-scans), which will automatically scan more of the index when needed.
Since we are stuck on 0.7.0 we are going the first option for now.
> FIX: Add workaround to pgvector HNSW search limitations

- app/controllers/discourse_ai/sentiment/sentiment_controller.rb
- app/serializers/ai_sentiment_post_serializer.rb
- assets/javascripts/discourse/components/admin-report-sentiment-analysis.gjs
- assets/stylesheets/modules/sentiment/common/dashboard.scss
- config/locales/client.en.yml
- lib/sentiment/sentiment_analysis_report.rb
- spec/requests/sentiment/sentiment_controller_spec.rb
> [!NOTE]
> This update includes a series of small follow-up updates to the new Sentiment Analysis report added in https://github.com/discourse/discourse-ai/pull/1109.
> DEV: Sentiment analysis report follow-up updates

- .gitignore
- README.md
- config/eval-llms.yml
- evals/lib/llm.rb
Eval configs were hard-coded in `DiscourseAi::Evals::Llm`. This PR moves them into a config file.
Evaluators can now also define their own config locally with `config/eval-llms.local.yml`, and will have the choice to define the `api_key` attribute, or `api_key_env` if an env var is preferred.
Example file:
```
llms:
discourse_llm:
display_name: Qwen/Qwen2.5-32B-Instruct
name: Qwen/Qwen2.5-32B-Instruct
tokenizer: DiscourseAi::Tokenizer::OpenAiTokenizer
api_key: <FILL IN KEY HERE>
provider: open_router
url: <FILL IN URL HERE>
max_prompt_tokens: 128000
vision_enabled: false
```
> DEV: Extract configs to a yml file and allow local config

- assets/javascripts/discourse/components/ai-llm-editor-form.gjs
- lib/completions/dialects/chat_gpt.rb
- spec/system/llms/ai_llm_spec.rb
1. Legacy reasoning models (o1-preview / o1-mini) do not support developer or system messages, do not use them.
2. LLM editor form not showing all provider params due to missing remap
> FIX: legacy reasoning models not working, missing provider params

- app/models/llm_model.rb
- assets/javascripts/discourse/components/ai-llm-editor-form.gjs
- config/locales/client.en.yml
- lib/completions/endpoints/anthropic.rb
- lib/completions/endpoints/aws_bedrock.rb
- lib/completions/endpoints/open_ai.rb
- lib/completions/llm.rb
- spec/lib/completions/endpoints/anthropic_spec.rb
- spec/lib/completions/endpoints/aws_bedrock_spec.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
- spec/system/llms/ai_llm_spec.rb
- Adds support for Sonnet 3.7 with reasoning on bedrock and anthropic
- Fixes regression where provider params were not populated
Note. reasoning tokens are hardcoded to minimum of 100 maximum of 65536
> FEATURE: full support for Sonnet 3.7

- assets/javascripts/initializers/admin-plugin-configuration-nav.js
- config/locales/client.en.yml
This will be used in the new admin search UI
> UX: Add description to configuration nav

- assets/javascripts/discourse/templates/admin-dashboard-sentiment.hbs
- assets/javascripts/initializers/ai-sentiment-admin-nav.js
- config/locales/client.en.yml
- plugin.rb
Adds these links to make the sentiment pages easier to access
I've added an anchor to the sentiment dashboard because otherwise the hosted site plugin can push it below the visible area, which makes the link appear to be broken
> UX: add links to sentiment to admin sidebar

- assets/javascripts/discourse/connectors/composer-fields/persona-llm-selector.gjs
- config/locales/client.en.yml
- config/locales/server.en.yml
- discourse_automation/llm_report.rb
- discourse_automation/llm_triage.rb
- lib/ai_bot/artifact_update_strategies/diff.rb
- lib/ai_bot/bot.rb
- lib/ai_bot/playground.rb
- lib/ai_bot/tools/github_pull_request_diff.rb
- lib/automation/llm_triage.rb
- lib/automation/report_runner.rb
- lib/completions/anthropic_message_processor.rb
- lib/completions/dialects/claude.rb
- lib/completions/dialects/claude_tools.rb
- lib/completions/endpoints/anthropic.rb
- lib/completions/endpoints/aws_bedrock.rb
- lib/completions/endpoints/base.rb
- lib/completions/endpoints/canned_response.rb
- lib/completions/endpoints/fake.rb
- lib/completions/endpoints/open_ai.rb
- lib/completions/llm.rb
- lib/completions/prompt.rb
- lib/completions/prompt_messages_builder.rb
- lib/completions/thinking.rb
- spec/lib/completions/anthropic_message_processor_spec.rb
- spec/lib/completions/endpoints/anthropic_spec.rb
- spec/lib/discourse_automation/llm_triage_spec.rb
- spec/lib/modules/ai_bot/artifact_update_strategies/diff_spec.rb
- spec/lib/modules/ai_bot/playground_spec.rb
- spec/lib/modules/ai_bot/tools/github_pull_request_diff_spec.rb
This PR adds support for "thinking tokens" - a feature that exposes the model's reasoning process before providing the final response. Key improvements include:
- Add a new Thinking class to handle thinking content from LLMs
- Modify endpoints (Claude, AWS Bedrock) to handle thinking output
- Update AI bot to display thinking in collapsible details section
- Fix SEARCH/REPLACE blocks to support empty replacement strings
- Allow configurable temperature in triage and report automations
- Various bug fixes and improvements to diff parsing
> FEATURE: implement thinking token support

- app/services/problem_check/ai_llm_status.rb
- config/locales/server.en.yml
- spec/services/problem_check/ai_llm_status_spec.rb
Better to construct the URL in Ruby and pass it to `I18n`, so we don't have to mess with the translations if the URL changes.
**Screenshot:**
> DEV: Use full URL for problem check message

- config/locales/client.en.yml
- config/locales/server.en.yml
- discourse_automation/llm_persona_triage.rb
- discourse_automation/llm_tool_triage.rb
- lib/ai_bot/playground.rb
- lib/ai_bot/tool_runner.rb
- lib/automation.rb
- lib/automation/llm_persona_triage.rb
- lib/automation/llm_tool_triage.rb
- lib/completions/prompt.rb
- lib/completions/prompt_messages_builder.rb
- plugin.rb
- spec/lib/completions/prompt_messages_builder_spec.rb
- spec/lib/discourse_automation/llm_persona_triage_spec.rb
- spec/lib/discourse_automation/llm_tool_triage_spec.rb
- spec/lib/modules/ai_bot/playground_spec.rb
- spec/models/ai_tool_spec.rb
- Allows automated responses to posts using AI personas
- Configurable to respond as regular posts or whispers
- Adds context-aware formatting for topics and private messages
- Provides special handling for topic metadata (title, category, tags)
- Enables custom AI tools to process and respond to posts
- Tools can analyze post content and invoke personas when needed
- Zero-parameter tools can be used for automated workflows
- Not enabled in production yet
- Added new scriptable registration in discourse_automation/ directory
- Created core implementation in lib/automation/ modules
- Enhanced PromptMessagesBuilder with topic-style formatting
- Added helper methods for persona and tool selection in UI
- Extended AI Bot functionality to support whisper responses
- Added rate limiting to …
> FEATURE: automation triage using ai tool or persona

- config/locales/client.en.yml
- discourse_automation/llm_triage.rb
- lib/ai_bot/playground.rb
- lib/automation.rb
- lib/automation/llm_persona_triage.rb
- lib/automation/llm_triage.rb
- lib/completions/endpoints/aws_bedrock.rb
- spec/lib/discourse_automation/llm_triage_spec.rb
This PR enhances the LLM triage automation with several important improvements:
- Add ability to use AI personas for automated replies instead of canned replies
- Add support for whisper responses
- Refactor LLM persona reply functionality into a reusable method
- Add new settings to configure response behavior in automations
- Improve error handling and logging
- Fix handling of personal messages in the triage flow
- Add comprehensive test coverage for new features
- Make personas configurable with more flexible requirements
This allows for more dynamic and context-aware responses in automated workflows, with better control over visibility and attribution.
> FEATURE: Add persona-based replies and whisper support to LLM triage

- lib/ai_moderation/entry_point.rb
When spam scanner is enabled and code is reloaded, developer experience this error:
```
NameError at /posts
===================
uninitialized constant DiscourseAi::AiModeration::EntryPoint::SpamScanner
> To access an interactive console with this error, point your browser to: /__better_errors
plugins/discourse-ai/lib/ai_moderation/entry_point.rb, line 7
```
It is because when we call `SpamScanner` it is searched within parent `DiscourseAi::AiModeration::EntryPoint` namespace.
We can help a bit Zeitwerk by calling SpamScanner more explicitly.
> DEV: fix Zeitwerk issue with SpamScanner class

- lib/summarization/strategies/topic_summary.rb
- spec/lib/modules/summarization/strategies/topic_summary_spec.rb
This PR lets Ai summarization to utilize name instead of username when `enable_names` is enabled and `prioritize_username_in_ux` is disabled.
> DEV: Ai summary utilizing name instead of username

- app/models/llm_model.rb
- config/locales/client.en.yml
- lib/completions/endpoints/anthropic.rb
- lib/completions/endpoints/aws_bedrock.rb
- lib/completions/endpoints/open_ai.rb
- lib/completions/endpoints/open_router.rb
- spec/lib/completions/endpoints/anthropic_spec.rb
- spec/lib/completions/endpoints/aws_bedrock_spec.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
- spec/lib/completions/endpoints/open_router_spec.rb
thinking models such as Claude 3.7 Thinking and o1 / o3 do not
support top_p or temp.
Previously you would have to carefully remove it from everywhere
by having it be a provider param we now support blanker removing
without forcing people to update automation rules or personas
> FEATURE: allow disabling of top_p and temp for thinking models

- lib/ai_bot/playground.rb
- lib/utils/search.rb
- spec/lib/discourse_automation/llm_persona_triage_spec.rb
- spec/lib/modules/ai_bot/playground_spec.rb
- spec/lib/utils/search_spec.rb
- Fix search API to only include column_names when present to make the API less confusing
- Ensure correct LLM is used in PMs by tracking and preferring the last bot user
- Fix persona_id conversion from string to integer in custom fields
- Add missing test for PM triage with no replies - ensure we don't try to auto title topic 
- Ensure bot users are properly added to PMs
- Make title setting optional when replying to posts
- Add ability to control stream_reply behavior
These changes improve reliability and fix edge cases in bot interactions,
particularly in private messages with multiple LLMs and while triaging posts using personas
> FIX: various issues with llm and triage management

- assets/stylesheets/modules/ai-bot/common/ai-artifact.scss
Gets rid of this noise
```
Deprecation Warning [mixed-decls]: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.
More info: https://sass-lang.com/d/mixed-decls
╷
2550 │ ┌   @keyframes slideUp {
2551 │ │     to {
2552 │ │       transform: translateY(-100%);
2553 │ │     }
2554 │ │   }
│ └─── nested rule
...  │
2575 │     left: 0;
│     ^^^^^^^ declaration
╵
```
> DEV: Fix SCSS linting issue

- evals/lib/eval.rb
- evals/lib/prompt_evaluator.rb
- evals/lib/runner.rb
- evals/run
This PR moves dealing with prompts into its own evaluator class, and allows prompt evals to take in multiple prompts and messages.
It also tries its best to keep everything else non-prompt working, as we move to handle more results at a time from the change above.
> DEV: Allow prompt-type evals to take in several prompts and messages

- assets/javascripts/discourse/components/ai-embedding-editor.gjs
follow-up to 51ca942, tests for existing embeddings worked but new embeddings were throwing an error... this gets them working again
> FIX: need to create model when testing new embedding

- assets/stylesheets/modules/ai-bot/common/ai-discobot-discoveries.scss
Wanted to give this alternate layout a try, it's behind a media query so it will still work the same way it does now on smaller screens. 
This allows the topic results to still appear at the top, and removes the need to expand the AI result. 
Smaller screens don't change:
> UX: try AI search to side on large screens

- assets/javascripts/discourse/components/ai-embedding-editor.gjs
- assets/javascripts/discourse/components/ai-llm-editor-form.gjs
This is a temporary fix while we make this codepath of FormKit to correctly follow Data down action up pattern, re-rendering a component shouldn't be an issue.
> FIX: prevents fields in Object to re-render

- assets/javascripts/discourse/components/ai-full-page-search.gjs
This appEvent is not firing on click, but instead on `resetAiResults`. This action is fired many times during page load.
> FIX: Remove incorrect full-page-search app event

- lib/sentiment/emotion_filter_order.rb
- spec/lib/modules/sentiment/emotion_filter_order_spec.rb
To match the updates in discourse/discourse#31908.
Note: no need to update the `.discourse-compatibility` as it's already pinned for the current beta.
> DEV: add `guardian` argument to `TopicsFilter` callback

- lib/ai_bot/bot.rb
- lib/completions/dialects/dialect.rb
- lib/completions/dialects/xml_tools.rb
- lib/completions/endpoints/anthropic.rb
- lib/completions/endpoints/aws_bedrock.rb
- lib/completions/endpoints/gemini.rb
- lib/completions/endpoints/open_ai.rb
- spec/lib/completions/dialects/dialect_spec.rb
- spec/lib/completions/endpoints/anthropic_spec.rb
- spec/lib/completions/endpoints/aws_bedrock_spec.rb
- spec/lib/completions/endpoints/gemini_spec.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
This PR adds support for disabling further tool calls by setting tool_choice to :none across all supported LLM providers:
- OpenAI: Uses "none" tool_choice parameter
- Anthropic: Uses {type: "none"} and adds a prefill message to prevent confusion
- Gemini: Sets function_calling_config mode to "NONE"
- AWS Bedrock: Doesn't natively support tool disabling, so adds a prefill message
We previously used to disable tool calls by simply removing tool definitions, but this would cause errors with some providers. This implementation uses the supported method appropriate for each provider while providing a fallback for Bedrock.
> FEATURE: allow specifying tool use none in completion prompt

- assets/javascripts/discourse/components/ai-embedding-editor.gjs
- assets/javascripts/discourse/components/ai-llm-editor-form.gjs
- assets/javascripts/discourse/components/ai-persona-tool-options.gjs
This was causing errors in the forms under specific cases.
> FIX: prevents to call Object.keys on null

- assets/javascripts/discourse/components/ai-persona-editor.gjs
- assets/javascripts/discourse/components/ai-persona-list-editor.gjs
- config/locales/client.en.yml
> UX: Show AI bot toggles in the AI bot options section

- assets/javascripts/discourse/components/ai-artifact.gjs
- assets/stylesheets/modules/ai-bot/common/ai-artifact.scss
Some slight style adjustments and CSS cleanup 
<p>Before:</p>
<p>After (added a light grey background):</p>
<p>Before:</p>
<p>After (adjusted the expand button icon, added a slight shadow to the artifact):</p>
<p>Before:</p>
<p>After (larger, centered fullscreen escape hint):</p>
> UX: adjust artifact UI styles

- assets/stylesheets/modules/ai-bot/common/ai-artifact.scss
The fade animation was overriding core, this more specific naming avoids it
> FIX: less generic animation names

- spec/jobs/scheduled/summaries_backfill_spec.rb
- spec/lib/modules/summarization/fold_content_spec.rb
We started used a callback as a buffer in FoldContent, so the Fake endpoint is attempting to emulate delays in the streaming. However, we don't care about that in these specs.
> DEV: Don't use delays for streaming summaries.

- db/post_migrate/20250404045050_migrate_users_to_email_group.rb
- discourse_automation/llm_report.rb
- lib/automation/report_context_generator.rb
- lib/automation/report_runner.rb
- spec/lib/discourse_automation/llm_report_spec.rb
- spec/lib/modules/automation/report_runner_spec.rb
Previously we only allowed targeting users and emails with the ai llm report, we now also allow groups
> FEATURE: allow to send LLM reports to groups

- assets/javascripts/discourse/components/ai-persona-editor.gjs
- db/fixtures/personas/603_ai_personas.rb
- db/migrate/20250407125756_set_correct_default_for_short_summarizer_persona.rb
- lib/guardian_extensions.rb
- spec/lib/guardian_extensions_spec.rb
Previously, allowing "everyone" to access gists meant anons would see them too. With the move to Personas, we used "[]" to reflect that.
With discourse/discourse#32199 adding the "everyone" option to the personas-allowed groups, we are switching back to the original behavior. Leaving allowed groups empty should always mean nobody can use the feature.
> FIX: Restore gists previous group access behavior.

- .gitignore
- config/locales/client.en.yml
- lib/personas/tool_runner.rb
- lib/personas/tools/custom.rb
- plugin.rb
- spec/lib/modules/ai_bot/playground_spec.rb
- spec/models/ai_tool_spec.rb
- spec/requests/admin/ai_personas_controller_spec.rb
Add API methods to AI tools for reading and updating personas, enabling
more flexible AI workflows. This allows custom tools to:
- Fetch persona information through discourse.getPersona()
- Update personas with modified settings via discourse.updatePersona()
- Also update using persona.update()
These APIs enable new use cases like "trainable" moderation bots, where
users with appropriate permissions can set and refine moderation rules
through direct chat interactions, without needing admin panel access.
Also adds a special API scope which allows people to lean on API
for similar actions
> FEATURE: allow tools to amend personas

- lib/completions/prompt_messages_builder.rb
- spec/lib/completions/prompt_messages_builder_spec.rb
Previous to this fix we assumed the name field contained usernames
when in fact it was stored in the id field.
This fixes the context contruction and also adds some basic user
information to the context to assist responders in understanding
the cast of chars
> FIX: invalid context construction for responders

- lib/completions/prompt_messages_builder.rb
- spec/lib/completions/prompt_messages_builder_spec.rb
1. Add age of post to topic context (1 month ago, 1 year ago, etc)
2. Refactor code for simplicity
3. Fix handling of post context in DMs which was not using new handling of uploads
> FEATURE: improve context management

- spec/system/ai_helper/ai_proofreading_spec.rb
This core PR must be merged for this to work
https://github.com/discourse/discourse/pull/32280
We want to make sure we don't have regressions with this
functionality in the rich editor, which uses contendeditable
and other APIs than the old composer.
> DEV: Add test to cover proofreading in rich editor

- lib/ai_bot/playground.rb
- spec/lib/modules/ai_bot/playground_spec.rb
Thinking tokens lead chat to be basically unusable, cause they flood chat with useless info.
This fix explicitly omits them
> FIX: omit thinking tokens from chat

- spec/system/ai_helper/ai_proofreading_spec.rb
- spec/system/page_objects/modals/diff_modal.rb
Followup fe7e73a6a436795c053a611884431f663f4bdd27 and
1300cc8a36dc33870f0d3c81e1e1a21a93e1f1de
Reintroduces proofreader specs and unskips ones skipped when
streaming composer suggestions were added. We just need to make sure
the jobs run immediately in specs because the job is what sends the
MessageBus event to the UI.
Also adds a pageobject method to confirm a diff is shown
in the modal before pressing Confirm button.
> DEV: Re-introduce proofreading specs

- assets/javascripts/initializers/ai-gist-topic-list-class.js
Core adds this class for themes when excerpts are shown in the topic list, so this does the same for gists. This allows us to have more control over the gist layout in themes. 
No visual changes.
> DEV: include excerpt-expanded class when gists are enabled

- spec/system/ai_helper/ai_composer_helper_spec.rb
This second post was not used and is making the topic scroll
down to post 2, which can mess with editing the OP sometimes
> DEV: Update spec for topic tag suggester

- assets/javascripts/discourse/components/ai-bot-header-icon.gjs
- assets/javascripts/discourse/services/ai-conversations-sidebar-manager.js
- spec/system/ai_bot/homepage_spec.rb
- spec/system/page_objects/pages/discourse_ai/header.rb
This PR prevents the conversations sidebar from re-rendering (thus losing infinite-loaded content and flashing) when navigating between Bot PMs and the landing page. 
It also swaps out the header icon to be a toggle when you are on the conversations landing page.
> FIX: Do not re-render conversations sidebar on navigation

- assets/javascripts/discourse/templates/discourse-ai-bot-conversations.gjs
- assets/stylesheets/modules/ai-bot-conversations/common.scss
This PR makes some minor adjustments to align the AI chat page with industry norms.
> UX: Align styling with conventions

- assets/javascripts/discourse/components/ai-llms-list-editor.gjs
- assets/stylesheets/modules/llms/common/ai-llms-editor.scss
- config/locales/client.en.yml
- config/settings.yml
- db/migrate/20250424035234_remove_old_settings.rb
- lib/ai_bot/chat_streamer.rb
- lib/ai_bot/playground.rb
- lib/configuration/llm_enumerator.rb
- spec/configuration/llm_enumerator_spec.rb
- spec/system/admin_ai_persona_spec.rb
- Usage was not showing automation or image caption in llm list.
- Also: FIX - reasoning models would time out incorrectly after 60 seconds (raised to 10 minutes)
> FEATURE: display more places where AI is used

- app/controllers/discourse_ai/ai_bot/conversations_controller.rb
- assets/javascripts/initializers/ai-conversations-sidebar.js
- db/migrate/20250424163718_set_ai_bot_pm_custom_fields.rb
- spec/system/ai_bot/homepage_spec.rb
In the last commit, I introduced a topic_custom_field to determine if a PM is indeed a bot PM.
This commit adds a migration to backfill any PM that is between 1 real user, and 1 bot. The correct topic_custom_field is added for these, so they will appear on the bot conversation sidebar properly.
We can also drop the joining to topic_users in the controller for sidebar conversations, and the `isPostFromAiBot` logic from the sidebar.
> DEV: Migration to backfill bot PM custom field

- assets/javascripts/discourse/components/ai-bot-sidebar-new-conversation.gjs
- assets/stylesheets/modules/ai-bot-conversations/common.scss
- spec/system/ai_bot/homepage_spec.rb
- spec/system/page_objects/components/ai_pm_homepage.rb
The new question button was hidden on Mobile when navigation menu was set to header mode.. this fixes that. In order for the hamburger sidebar to close on button press, we need the fn passed into this connector. Core PR for it -> https://github.com/discourse/discourse/pull/32449
> UX: Bring back New Conversation button on mobile sidebar

- assets/stylesheets/modules/ai-bot-conversations/common.scss
These are very minor changes that get us some more consistent alignment 
This also avoids having this page scroll, especially when the "powered by discourse" badge is present
> UX: minor alignment adjustments for experiemental bot UI

- spec/system/ai_bot/tool_spec.rb
Playwright is going to be less permissive to this in the future.
> DEV: invalid selector

- app/controllers/discourse_ai/ai_bot/conversations_controller.rb
- assets/javascripts/initializers/ai-conversations-sidebar.js
- assets/stylesheets/modules/ai-bot-conversations/common.scss
- config/locales/client.en.yml
- spec/system/ai_bot/homepage_spec.rb
- spec/system/page_objects/components/ai_pm_homepage.rb
https://github.com/user-attachments/assets/3fe3ac8f-c938-4df4-9afe-11980046944d
- Group pms by `last_posted_at`. In this first iteration we are group by `7 days`, `30 days`, then by month beyond that. 
- I inject a sidebar section link with the relative (last_posted_at) date and then update a tracked value to ensure we don't do it again. Then for each month beyond the first 30days, I add a value to the `loadedMonthLabels` set and we reference that (plus the year) to see if we need to load a new month label.
- I took the creative liberty to remove the `Conversations` section label - this had no purpose
- I hid the _collapse all sidebar sections_ carrot. This had no purpose. 
- Swap `BasicTopicSerializer` to `ListableTopicSerializer` to get access to `last_posted_at`
> DEV: Group PMs by date

- assets/javascripts/initializers/ai-conversations-sidebar.js
- assets/stylesheets/modules/ai-bot-conversations/common.scss
- config/locales/client.en.yml
- spec/system/ai_bot/homepage_spec.rb
- Add `Today` label
- Make some minor UX changes
- Add specs
> DEV: Update sidebar grouping date labels

- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
> UX: keep composer actions above AI input icons

- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
This reverts commit 51a0516aa8c4caa13b01e47a6e8655659a9648ba.
> Revert "UX: keep composer actions above AI input icons (#1291)"

- config/locales/server.en.yml
- config/settings.yml
- db/migrate/20250429060311_move_dall_e_url.rb
- lib/ai_helper/painter.rb
- lib/completions/prompt_messages_builder.rb
- lib/inference/open_ai_image_generator.rb
- lib/personas/designer.rb
- lib/personas/persona.rb
- lib/personas/tools/create_image.rb
- lib/personas/tools/dall_e.rb
- lib/personas/tools/edit_image.rb
- spec/lib/completions/prompt_messages_builder_spec.rb
- spec/lib/modules/ai_bot/playground_spec.rb
- spec/lib/modules/ai_helper/painter_spec.rb
- spec/lib/personas/tools/create_image_spec.rb
- spec/lib/personas/tools/dall_e_spec.rb
- spec/lib/personas/tools/edit_image_spec.rb
- spec/models/ai_tool_spec.rb
This commit enhances the AI image generation functionality by adding support for:
1. OpenAI's GPT-based image generation model (gpt-image-1)
2. Image editing capabilities through the OpenAI API
3. A new "Designer" persona specialized in image generation and editing
4. Two new AI tools: CreateImage and EditImage
Technical changes include:
- Renaming `ai_openai_dall_e_3_url` to `ai_openai_image_generation_url` with a migration
- Adding `ai_openai_image_edit_url` setting for the image edit API endpoint
- Refactoring image generation code to handle both DALL-E and the newer GPT models
- Supporting multipart/form-data for image editing requests
> FEATURE: add OpenAI image generation and editing capabilities

- assets/javascripts/discourse/components/ai-bot-header-icon.gjs
- assets/javascripts/initializers/ai-conversations-sidebar.js
- spec/system/ai_bot/homepage_spec.rb
- spec/system/page_objects/components/ai_pm_homepage.rb
Context in dev conversation -- in hamburger mode we don't need the robot icon to swap to shuffle, AND we don't need back to forum like.
Relies on -> https://github.com/discourse/discourse/pull/32515
> UX: Adjust bot conversation header and sidebar on hamburger mode

- assets/javascripts/discourse/lib/ai-bot-helper.js
- assets/javascripts/initializers/ai-bot-replies.js
- assets/stylesheets/modules/ai-bot/common/bot-replies.scss
- config/locales/server.en.yml
- lib/ai_bot/entry_point.rb
- lib/ai_bot/playground.rb
- spec/lib/modules/ai_bot/playground_spec.rb
- spec/requests/ai_bot/topic_serialization_spec.rb
AI bots come in 2 flavors
1. An LLM and LLM user, in this case we should decorate posts with persona name
2. A Persona user, in this case, in PMs we decorate with LLM name
(2) is a significant improvement, cause previously when creating a conversation
you could not tell which LLM you were talking to by simply looking at the post, you would
have to scroll to the top of the page.
> FEATURE: correctly decorate AI bots

- assets/javascripts/discourse/components/ai-full-page-search.gjs
- assets/javascripts/discourse/connectors/full-page-search-below-search-header/ai-full-page-discobot-discoveries.gjs
- assets/stylesheets/modules/ai-bot/common/ai-discobot-discoveries.scss
- assets/stylesheets/modules/embeddings/common/semantic-search.scss
This puts the Discobot Discovery section into a right sidebar and adjusts related styles
Before:
After:
At narrow widths, we still stack:
> UX: put full page search discoveries in sidebar

- assets/javascripts/discourse/components/ai-bot-header-icon.gjs
- assets/javascripts/discourse/controllers/discourse-ai-bot-conversations.js
- assets/javascripts/discourse/services/ai-bot-conversations-hidden-submit.js
- assets/javascripts/discourse/templates/discourse-ai-bot-conversations.gjs
- assets/javascripts/initializers/ai-conversations-sidebar.js
- assets/stylesheets/modules/ai-bot-conversations/common.scss
- config/locales/server.en.yml
- config/settings.yml
- db/migrate/20250501002657_renamed_experimental_ai_bot_setting.rb
- spec/system/ai_bot/ai_bot_helper_spec.rb
- spec/system/ai_bot/homepage_spec.rb
> FEATURE: add support for uploads when starting a convo

- app/models/ai_persona.rb
- lib/ai_bot/playground.rb
- lib/personas/persona.rb
- spec/lib/modules/ai_bot/playground_spec.rb
- spec/lib/personas/persona_spec.rb
- spec/models/ai_persona_multisite_spec.rb
System personas leaned on reused classes, this was a problem
in a multisite environement cause state, such as "enabled"
ended up being reused between sites.
New implementation ensures state is pristine between sites in
a multisite
> FIX: system persona state leaking between sites

- lib/inference/open_ai_image_generator.rb
- lib/personas/tools/create_image.rb
- lib/personas/tools/edit_image.rb
- spec/lib/personas/tools/create_image_spec.rb
- spec/lib/personas/tools/edit_image_spec.rb
When image edit or creation fails for any sort of reason we should properly inform the LLM of what happened. 
This allows it to self correct.
> FIX: better LLM feedback for image generation failures 

- assets/javascripts/discourse/controllers/discourse-ai-bot-conversations.js
- assets/javascripts/discourse/services/ai-bot-conversations-hidden-submit.js
- assets/javascripts/initializers/ai-conversations-sidebar.js
- config/locales/client.en.yml
- spec/system/ai_bot/homepage_spec.rb
- spec/system/page_objects/components/ai_pm_homepage.rb
This PR addresses a bug where uploads weren't being cleared after successfully posting a new private message in the AI bot conversations interface. Here's what the changes do:
- Makes the `prepareAndSubmitToBot()` method async and adds proper error handling
- Adds `this.uploads.clear()` after successful submission to clear all uploads
- Adds a test to verify that the "New Question" button properly resets the UI with no uploads
1. **Dynamic Character Length Validation**:
- Uses `siteSettings.min_personal_message_post_length` instead of hardcoded 10 characters
- Updates the error message to show the dynamic character count
- Adds proper pluralization in the localization file for the error message
2. **Bug Fixes**:
- Adds null checks with optional chaining (`link?.topic?.id`) in the sidebar …
> FIX: clear uploads after successfully posting new PM

- lib/personas/github_helper.rb
- lib/personas/researcher.rb
The date / time is important cause it creates a bias towards
action.
Without it, model may think it is getting future annoucements vs
up to date info.
> FEATURE: ensure researcher and github helper know the date

- lib/completions/endpoints/base.rb
- lib/completions/endpoints/canned_response.rb
Non-streaming mode should always return a `StructureOutput` when a response format is given. Multi-turn responses aren't supported so `response_data` is always a string.
> FIX: Return structured output on non-streaming mode

- assets/javascripts/initializers/ai-conversations-sidebar.js
- spec/system/ai_bot/homepage_spec.rb
Button is misplaced and confusing, header returns to forum
> UX: stop rendering back to forum link

- assets/stylesheets/modules/ai-bot-conversations/common.scss
Fixes overflow on narrow screens...
before:
after:
Fixes input disabled background when submitting...
before:
after:
Removes extra controls...
before:
after:
> UX: style adjustments for conversations

- app/models/llm_model.rb
- config/locales/client.en.yml
- lib/completions/endpoints/gemini.rb
- spec/lib/completions/endpoints/gemini_spec.rb
Gemini 2.5 series models support configurable thinking tokens. 
This allows this to be configured. 
https://ai.google.dev/gemini-api/docs/thinking
> FEATURE: support configurable thinking tokens for Gemini

- lib/ai_bot/playground.rb
- lib/automation/llm_persona_triage.rb
- spec/lib/discourse_automation/llm_persona_triage_spec.rb
We were logging persona triage as "bot" in logs, causing some
confusions around real world usage
This amends it so we log usage to "automation - AUTOMATION NAME"
> FIX: persona triage should be logged to automation

- assets/javascripts/discourse/components/ai-bot-sidebar-new-conversation.gjs
- assets/stylesheets/modules/ai-bot-conversations/common.scss
On desktop we get an automatically sticky button at the top because the scrollable content is in a sibling container, but on mobile the entire sidebar content is scrollable... so we need to set the button to be sticky there specifically
> UX: stick new question button to top of mobile sidebar

- assets/javascripts/discourse/components/suggestion-menus/ai-tag-suggester.gjs
- assets/javascripts/discourse/connectors/after-composer-category-input/ai-category-suggestion.gjs
- assets/javascripts/discourse/connectors/after-composer-title-input/ai-title-suggestion.gjs
- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
Reported here: https://meta.discourse.org/t/disable-ai-title-generator-when-pm-title-cannot-be-edited/307595
This hides the composer AI suggestion buttons when the user can't edit the title/category/tags
> UX: don't show AI suggestions in composer when inputs are disabled

- app/controllers/discourse_ai/admin/ai_personas_controller.rb
- app/models/ai_persona.rb
- app/serializers/localized_ai_persona_serializer.rb
- assets/javascripts/discourse/admin/models/ai-persona.js
- assets/javascripts/discourse/components/ai-persona-editor.gjs
- assets/javascripts/discourse/components/ai-persona-example.gjs
- config/locales/client.en.yml
- config/locales/server.en.yml
- db/fixtures/personas/603_ai_personas.rb
- db/migrate/20250508154953_add_examples_to_personas.rb
- lib/personas/persona.rb
- lib/personas/summarizer.rb
- lib/summarization/strategies/topic_summary.rb
- spec/lib/personas/persona_spec.rb
- spec/models/ai_persona_spec.rb
- spec/requests/admin/ai_personas_controller_spec.rb
Examples simulate previous interactions with an LLM and come right after the system prompt. This helps grounding the model and producing better responses.
---
---
> FEATURE: Examples support for personas.

- lib/completions/dialects/claude_tools.rb
- lib/completions/dialects/cohere_tools.rb
- lib/completions/dialects/gemini.rb
- lib/completions/dialects/nova_tools.rb
- lib/completions/dialects/ollama_tools.rb
- lib/completions/dialects/open_ai_tools.rb
- lib/completions/dialects/xml_tools.rb
- lib/completions/endpoints/base.rb
- lib/completions/prompt.rb
- lib/completions/tool_definition.rb
- lib/completions/xml_tool_processor.rb
- spec/lib/completions/dialects/chat_gpt_spec.rb
- spec/lib/completions/dialects/dialect_context.rb
- spec/lib/completions/dialects/gemini_spec.rb
- spec/lib/completions/dialects/nova_spec.rb
- spec/lib/completions/dialects/ollama_spec.rb
- spec/lib/completions/dialects/ollama_tools_spec.rb
- spec/lib/completions/endpoints/nova_spec.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
- spec/lib/completions/tool_definition_spec.rb
- spec/lib/completions/xml_tool_processor_spec.rb
- spec/lib/personas/persona_spec.rb
This commit introduces a comprehensive refactoring of the AI tools system by adding a proper object-oriented interface for tool definitions. Instead of working with raw hash structures, tools are now represented by a proper `ToolDefinition` class with validation, parameter coercion, and schema generation capabilities.
- Add new `ToolDefinition` class with nested `ParameterDefinition` class
- Strong validation for parameter types, names, and values
- Type coercion for parameters (string, boolean, number, array, etc.)
- JSON schema generation via `parameters_json_schema` method
- Refactor all dialect adapters to use the new class:
- Replace direct hash manipulation with proper object methods
- Simplify code by delegating schema generation to the ToolDefinition class
- Consistent parameter …
> DEV: use a proper object for tool definition

- app/controllers/discourse_ai/ai_bot/shared_ai_conversations_controller.rb
AI share page assets are loaded via the app CDN, which means the requests have no authentication and will never appear to the app as "logged in". Therefore we should skip the `redirect_to_login_if_required` before_action.
> FIX: AI share page assets via CDN on login-required sites

- spec/tasks/backfill_spec.rb
This has nothing to do with `assets:precompile`. Likely a copy/paste from another spec
> DEV: Rename spec

- assets/javascripts/discourse/components/ai-bot-header-icon.gjs
- assets/javascripts/discourse/services/ai-conversations-sidebar-manager.js
This PR adds appEvents triggers for 'discourse-ai:bot-header-icon-clicked', 'discourse-ai:force-custom-sidebar', and 'discourse-ai:stop-forcing-custom-sidebar'.
> DEV: Add multiple appEvents trigger on AI Chatbot

- app/controllers/discourse_ai/ai_bot/artifacts_controller.rb
- assets/javascripts/discourse/components/ai-artifact.gjs
- assets/javascripts/initializers/ai-artifacts.gjs
- spec/system/ai_bot/artifact_spec.rb
Also allow artifact access to current username
Usage inside artifact is:
1. await window.discourseArtifactReady;
2. access data via window.discourseArtifactData;
```
<div class="ai-artifact" data-ai-artifact-id="482" data-hello="world"></div>
```
> FEATURE: allow passing in data attributes to an artifact

- spec/system/ai_bot/artifact_spec.rb
Generally speaking we never want to do:
```
expect(element.text).to eq("foo")
```
As these are rspec matchers and do not add further Capybara-style waiting specifically for the text content to become present.
> DEV: rewrites artifact spec with capybara waiters

- lib/ai_bot/entry_point.rb
In some rare cases a post can exist without a topic
> FIX: add safe navigation to serializer include conditions

- config/locales/server.en.yml
- lib/automation.rb
- lib/automation/llm_triage.rb
- spec/lib/modules/automation/llm_triage_spec.rb
Previously, this was only possible when flagging as spam.
> FEATURE: Triage can hide posts after adding them to the review queue

- spec/lib/completions/cancel_manager_spec.rb
Webmock can be a bit flaky under certain use cases.
> DEV: cancel manager should bypass webmock

- assets/javascripts/discourse/services/ai-conversations-sidebar-manager.js
This PR moves the stop-forcing-conversations-sidebar appEvents trigger.
> DEV: Move the stop-forcing-conversations-sidebar appEvents trigger

- assets/javascripts/discourse/connectors/topic-map-expanded-after/ai-summary-trigger.gjs
- assets/javascripts/discourse/connectors/topic-map-participants-after/ai-conversation-invite.gjs
- assets/stylesheets/modules/ai-bot-conversations/common.scss
- config/locales/client.en.yml
This adds a custom topic map participant list to AI Conversations... most of the time it will look like this: 
but it may have many users and groups: 
This also adds a condition to hide topic summaries from AI Conversations.
This is dependent on an outlet added here: https://github.com/discourse/discourse/pull/32826
> FEATURE: add participants and invite button to AI conversations

- lib/completions/json_streaming_tracker.rb
- spec/lib/completions/endpoints/anthropic_spec.rb
- spec/lib/completions/endpoints/aws_bedrock_spec.rb
- spec/lib/completions/endpoints/cohere_spec.rb
- spec/lib/completions/endpoints/gemini_spec.rb
The structured output JSON comes embedded inside the API response, which is also a JSON. Since we have to parse the response to process it, any control characters inside the structured output are unescaped into regular characters, leading to invalid JSON and breaking during parsing. This change adds a retry mechanism that escapes the string again if parsing fails, preventing the parser from breaking on malformed input and working around this issue.
For example:
```ruby
original = '{ "a": "{\\"key\\":\\"value with \\n newline\\"}" }'
JSON.parse(original) => { "a" => "{\"key\":\"value with \n newline\"}" }
```
> FIX: Retry parsing escaped inner JSON to handle control chars.

- assets/javascripts/discourse/components/modal/diff-modal.gjs
- assets/javascripts/discourse/lib/diff-streamer.gjs
- assets/stylesheets/common/streaming.scss
Previously we attempted to add a diff streaming animation to the AI composer helper: https://github.com/discourse/discourse-ai/pull/1332, but it resulted in issues despite attempted fixes (https://github.com/discourse/discourse-ai/pull/1338) so we temporarily suppressed the diff animation (https://github.com/discourse/discourse-ai/pull/1341).
This update makes a second attempt at implementing the diff streaming animation. Instead of creating a custom diff algorithm, we make use of a third-party library [`jsDiff`](https://github.com/kpdecker/jsdiff) (which we added to core here: https://github.com/discourse/discourse/pull/32833). While streaming, the diff animation often struggles with markdown links and images, so we make use of `markdown-it` parser to detect those cases and prevent …
> FEATURE: Add diff streaming animation

- assets/javascripts/discourse/lib/ai-streamer/updaters/post-updater.js
Before this commit you could end up in this situation where a `post-updater` is constructed for a specific topic, but the user changes topic mid steam and it ends up updating the same post number but in a  different topic as we were only checking for `post_number` and not the combination of `topic_id` + `post_number`.
No test as there's only a unit test at the moment which wouldn't confirm the topic logic.
> FIX: ensures stream update object is scoped to its initial topic

- lib/completions/dialects/claude.rb
- spec/lib/completions/endpoints/anthropic_spec.rb
- spec/lib/completions/endpoints/aws_bedrock_spec.rb
The `ClaudePrompt` object couldn't access the original prompt's tool_choice attribute, affecting both Anthropic and Bedrock.
> FIX: Correctly pass tool_choice when using Claude models.

- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
This PR allows these inputs to inherit `--d-border-radius`.
> UX: Allow rounded corners

- assets/javascripts/discourse/components/modal/diff-modal.gjs
- assets/javascripts/discourse/lib/diff-streamer.gjs
- assets/stylesheets/modules/ai-helper/common/ai-helper.scss
1. Do escaping direct in diff streamer, that way HTML tags and other unsafe chars can be displayed and fixed
2. Add safeguard to ensure streaming always stops when it was terminated elsewhere
> FIX: apply diffs more consistently

- config/locales/client.en.yml
- lib/personas/tools/researcher.rb
- lib/utils/research/filter.rb
- spec/lib/personas/tools/researcher_spec.rb
- **Enhanced filter validation**: Added tracking of invalid filter fragments in the research filter system
- **Better error reporting**: The researcher tool now returns descriptive error messages when invalid filters are used, including suggestions for valid filters
- **Optimized topic filtering**: Improved query logic when filtering by topic IDs to avoid unnecessary complex queries
- **Updated documentation**: Fixed misleading text about reasoning feature scope (not just Sonnet 3.7)
- Added `invalid_filters` tracking in `Filter` class to collect unrecognized filter terms
- Modified `process_filters` method to accumulate invalid filters instead of returning filtered terms
- Enhanced researcher tool to check for invalid filters and return early with helpful error messages
- Fixed database …
> FIX: improve researcher tool - fix topic filters

- assets/javascripts/discourse/connectors/full-page-search-below-search-header/ai-full-page-discobot-discoveries.gjs
Follow-up to 59d6e2b467d1d1e558b59d9d32794231791ee241
Error encountered in prod.
```
ai-full-page-discobot-discoveries.js:21 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'viewport')
at get previewLength (ai-full-page-discobot-discoveries.js:21:1)
at eM (cache-BESCGvbE.js:1647:18)
at index.js:95:32
at index.js:75:37
at Z (index.js:418:5)
at T (index.js:74:16)
at p.get (index.js:26:32)
at k.<anonymous> (ai-search-discoveries.js:37:1)
at getter (index.js:444:104)
at k.o [as discoveryPreviewLength] (cache-BESCGvbE.js:1878:17)
at get canShowExpandtoggle (ai-search-discoveries.js:114:1)
at get renderPreviewOnly (ai-search-discoveries.js:117:1)
```
> FIX: Full page search broken

- assets/javascripts/discourse/components/modal/debug-ai-modal.gjs
- assets/stylesheets/modules/ai-bot/common/bot-replies.scss
This is showing as the second-most expensive CSS selector in Discourse at the moment. Adding specific classes and dropping the general `span` selector will make this much cheaper.
> PERF: Optimize `.ai-debug-modal__tokens` selector

- spec/system/ai_helper/ai_composer_helper_spec.rb
Fix due to https://github.com/discourse/discourse/pull/32941
> FIX: edit-topic is not invisible on desktop

- config/locales/server.en.yml
- lib/personas/tools/researcher.rb
- lib/utils/research/filter.rb
- spec/lib/personas/tools/researcher_spec.rb
- spec/lib/utils/research/filter_spec.rb
Adds context length controls to researcher (max tokens per post and batch)
Allow picking LLM for researcher
Fix bug where unicode usernames were not working
Fix documentation of OR logic
> FEATURE: add context and llm controls to researcher, fix username filter

- assets/javascripts/discourse/components/ai-persona-editor.gjs
- assets/javascripts/discourse/components/ai-tool-editor-form.gjs
- assets/stylesheets/modules/ai-bot/common/ai-persona.scss
- assets/stylesheets/modules/ai-bot/common/ai-tools.scss
This commit changes the RAG uploader form elements to
be `@format="full"` instead of doing a hardcoded 500px width,
which was causing a horizontal scrollbar in the tools form
on mobile.
Also, it moves the 80% max width for the tools form into the
new viewport CSS API, and only applies it on desktop, because
this was also causing width issues on mobile.
**Add files causing horizontal scroll before**
**Width of description & script being off before**
**After**
> UX: Style tweaks for RAG uploader and form width

- lib/ai_helper/assistant.rb
- lib/personas/tools/researcher.rb
- lib/summarization/fold_content.rb
- lib/utils/research/filter.rb
- spec/lib/utils/research/filter_spec.rb
Allows searching through assigns in researcher, if assigns are enabled
> FEATURE: allow access to assigns from forum researcher

- ai_artifact_key_value_api_spec.rb
- app/controllers/discourse_ai/ai_bot/artifact_key_values_controller.rb
- app/controllers/discourse_ai/ai_bot/artifacts_controller.rb
- app/models/ai_artifact.rb
- app/models/ai_artifact_key_value.rb
- app/models/shared_ai_conversation.rb
- app/serializers/ai_artifact_key_value_serializer.rb
- app/views/discourse_ai/ai_bot/shared_ai_conversations/show.html.erb
- assets/javascripts/discourse/components/modal/share-full-topic-modal.gjs
- assets/stylesheets/modules/ai-bot/common/ai-artifact.scss
- config/locales/client.en.yml
- config/locales/server.en.yml
- config/routes.rb
- config/settings.yml
- db/migrate/20250607071239_create_ai_artifacts_key_values.rb
- lib/personas/artifact_update_strategies/base.rb
- lib/personas/artifact_update_strategies/diff.rb
- lib/personas/artifact_update_strategies/full.rb
- lib/personas/tools/create_artifact.rb
- lib/personas/web_artifact_creator.rb
- public/ai-share/share.css
- spec/fabricators/ai_artifact_fabricator.rb
- spec/models/ai_artifact_key_value_spec.rb
- spec/models/shared_ai_conversation_spec.rb
- spec/requests/ai_bot/artifact_key_values_controller_spec.rb
- spec/system/ai_artifact_key_value_api_spec.rb
Introduces a persistent, user-scoped key-value storage system for
AI Artifacts, enabling them to be stateful and interactive. This
transforms artifacts from static content into mini-applications that can
save user input, preferences, and other data.
The core components of this feature are:
1.  **Model and API**:
- A new `AiArtifactKeyValue` model and corresponding database table to
store data associated with a user and an artifact.
- A new `ArtifactKeyValuesController` provides a RESTful API for
CRUD operations (`index`, `set`, `destroy`) on the key-value data.
- Permissions are enforced: users can only modify their own data but
can view public data from other users.
2.  **Secure JavaScript Bridge**:
- A `postMessage` communication bridge is established between the
sandboxed artifact …
> FEATURE: persistent key-value storage for AI Artifacts

- app/jobs/regular/detect_translate_post.rb
- app/jobs/regular/detect_translate_topic.rb
- spec/jobs/regular/detect_translate_post_spec.rb
- spec/jobs/regular/detect_translate_topic_spec.rb
We will fine tune updating an outdated localization in the future. For now we are seeing that quick edits are happening and we need to prevent the job from being too trigger-happy.
/t/156185
> FIX: Skip edits if localization exists

- app/controllers/discourse_ai/ai_bot/artifact_key_values_controller.rb
- spec/requests/ai_bot/artifact_key_values_controller_spec.rb
Previously we had a logic error and were showing admins keys
that are not theirs when querying for all keys
This makes the API cleaner, to get all results you need to be explicit always
> FIX: improve admin api for artifact key values

- spec/system/ai_helper/ai_post_helper_spec.rb
This is needed for https://github.com/discourse/discourse/pull/33143 as we now rely on this pointerup event.
> DEV: a real selection change has a pointerup event

- assets/javascripts/discourse/components/ai-llm-editor-form.gjs
- assets/javascripts/discourse/components/ai-persona-editor.gjs
- assets/javascripts/discourse/components/ai-persona-tool-options.gjs
- assets/javascripts/discourse/components/ai-tool-editor-form.gjs
- db/fixtures/personas/603_ai_personas.rb
- spec/system/ai_bot/persona_spec.rb
- spec/system/llms/ai_llm_spec.rb
1. Improves logic so when we save llm/person/tool we don't have /new routes in our state stack. Breaking expected behavior of back button
2. Fixes implementation of enum in llm tool options
3. Improves seeding logic to avoid having information hidden from end users in the UI (show examples and structured output)
> FIX: various bugs in AI interface

- app/controllers/discourse_ai/ai_bot/artifacts_controller.rb
- app/models/shared_ai_conversation.rb
- assets/javascripts/discourse/components/ai-artifact.gjs
- assets/javascripts/initializers/ai-artifacts.gjs
- assets/javascripts/lib/discourse-markdown/ai-tags.js
- assets/stylesheets/modules/ai-bot/common/ai-artifact.scss
- config/locales/server.en.yml
- config/settings.yml
- lib/personas/persona.rb
`In hybrid mode ai artifacts can optionally automatically run.
This is useful for cases where you may want to embed a survey and so on.
Additionally, artifacts now allow for better fidelity around display:
Eg: `<div class="ai-artifact" data-ai-artifact-id="501" data-ai-artifact-height="300px" data-ai-artifact-autorun data-ai-artifact-seamless></div>`
User can supply height and seamless mode to be seamlessly rendered with no box shadow and show full screen button.
> FEATURE: hybrid artifact security mode

- app/controllers/discourse_ai/admin/ai_personas_controller.rb
- app/serializers/localized_ai_persona_serializer.rb
- assets/javascripts/discourse/components/ai-persona-list-editor.gjs
- assets/stylesheets/modules/ai-bot/common/ai-persona.scss
- config/locales/client.en.yml
This updates the persona list layout to include:
* Features used
* Default LLM
* Filterable list (by name, description, LLM, or features)
* optional card view 
Before:
After:
> UX: add features to persona list and other style updates

- config/locales/client.en.yml
- config/locales/server.en.yml
- config/settings.yml
- lib/configuration/feature.rb
- lib/configuration/module.rb
- lib/personas/bot_context.rb
- lib/personas/locale_detection.rb
- lib/personas/locale_detector.rb
- lib/personas/persona.rb
- lib/personas/post_raw_translator.rb
- lib/personas/short_text_translator.rb
- lib/personas/topic_title_translator.rb
- lib/translation/base_translator.rb
- lib/translation/language_detector.rb
- lib/translation/post_localizer.rb
- lib/translation/post_raw_translator.rb
- lib/translation/short_text_translator.rb
- lib/translation/topic_localizer.rb
- lib/translation/topic_title_translator.rb
- spec/lib/translation/base_translator_spec.rb
- spec/lib/translation/language_detector_spec.rb
- spec/lib/translation/post_localizer_spec.rb
- spec/lib/translation/topic_localizer_spec.rb
- spec/requests/admin/ai_features_controller_spec.rb
- spec/system/admin_ai_features_spec.rb
This PR moves translations into an AI Feature
| Ai Feature 📸 |
|---|
| <img width="1101" alt="Screenshot 2025-06-13 at 12 44 10 AM" src="https://github.com/user-attachments/assets/7a03dd5c-8788-49ee-8d5c-05197c8c5af2" /> |
| All settings 📸  |
|---|
| <img width="391" alt="Screenshot 2025-06-13 at 12 44 58 AM" src="https://github.com/user-attachments/assets/41130faf-066f-4bf4-818b-ad629b93ab8b" /> |
| Persona | Persona | Persona | Persona |
|---|---|---|---|
| <img width="360" alt="Screenshot 2025-06-13 at 12 45 50 AM" src="https://github.com/user-attachments/assets/db061cb9-55ba-4478-8164-b61b6de94dd5" /> | <img width="347" alt="Screenshot 2025-06-13 at 12 46 02 AM" src="https://github.com/user-attachments/assets/7ea6c64d-bf65-405c-9c97-f18b104a234f" /> | <img width="349" alt="Screenshot …
> DEV: Move AI translation feature into an AI Feature

- assets/javascripts/discourse/components/ai-bot-conversations.gjs
- assets/javascripts/discourse/components/ai-bot-sidebar-new-conversation.gjs
This improves the focus behavior in two situations:
1. When clicking "new question" from the sidebar when you're on the conversations index and the input isn't focused — this now refocuses the input. Previously it did nothing. 
2. When navigating from a PM to the conversations index (most likely when clicking the new question button in the sidebar), the input will now focus. Previously it was not focused.
> UX: focus conversation input on route transition and button click

- lib/personas/post_raw_translator.rb
- lib/personas/short_text_translator.rb
- lib/personas/topic_title_translator.rb
- spec/lib/translation/base_translator_spec.rb
In https://github.com/discourse/discourse-ai/pull/1424, we moved prompts into personas but did not extract examples out of the prompts. This PR corrects that.
Raw req payload after switch indicating compliance:
```
{"generationConfig"=>
{"temperature"=>0.3,
"responseSchema"=>
{"type"=>"object",
"properties"=>{"translation"=>{"type"=>"string"}},
"required"=>["translation"]},
"responseMimeType"=>"application/json"},
"safetySettings"=>
[{"category"=>"HARM_CATEGORY_HARASSMENT", "threshold"=>"BLOCK_NONE"},
{"category"=>"HARM_CATEGORY_SEXUALLY_EXPLICIT",
"threshold"=>"BLOCK_NONE"},
{"category"=>"HARM_CATEGORY_HATE_SPEECH", "threshold"=>"BLOCK_NONE"},
{"category"=>"HARM_CATEGORY_DANGEROUS_CONTENT",
"threshold"=>"BLOCK_NONE"}],
"contents"=>
[{"role"=>"user",
"parts"=>
[{"text"=> …
```
> DEV: Move examples out of prompt

- app/jobs/regular/detect_translate_post.rb
- app/jobs/regular/detect_translate_topic.rb
- lib/translation/entry_point.rb
- spec/lib/translation/entry_point_spec.rb
We're seeing an aggressive number of translations being enqueued for a single post and locale. Historically, we trigger translation on `cooked` not `raw`, but that has changed a while back.
```
zh_CN - 2025-06-17 13:02:31 UTC
zh_CN - 2025-06-17 13:02:34 UTC
zh_CN - 2025-06-17 13:02:35 UTC
zh_CN - 2025-06-17 13:02:36 UTC
zh_CN - 2025-06-17 13:02:38 UTC
zh_CN - 2025-06-17 13:02:39 UTC
zh_CN - 2025-06-17 13:02:40 UTC
zh_CN - 2025-06-17 13:02:40 UTC
zh_CN - 2025-06-17 13:02:43 UTC
zh_CN - 2025-06-17 13:02:44 UTC
```
This PR prevents this from happening.
> DEV: Prevent multiple translation per post

- assets/javascripts/discourse/services/ai-conversations-sidebar-manager.js
- assets/stylesheets/modules/ai-bot-conversations/common.scss
- spec/system/ai_bot/homepage_spec.rb
In [this commit](https://github.com/discourse/discourse-ai/commit/4f980d5514f571683596bb9042968d210feb0cef) the today section was added always, but a side-effect was that we hid the empty state component. This commit brings back the empty state, when appropriate:
Same as now when today is empty, BUT the sidebar has other sections:
Today still works:
When there are no messages we show the empty component, and hide the "today" header
> FIX: Bring back empty state message when appropriate

- app/jobs/regular/detect_translate_post.rb
- app/jobs/regular/detect_translate_topic.rb
- app/jobs/regular/localize_categories.rb
- app/jobs/regular/localize_posts.rb
- app/jobs/regular/localize_topics.rb
- lib/translation/base_translator.rb
- lib/translation/content_splitter.rb
- lib/translation/post_localizer.rb
- spec/lib/translation/base_translator_spec.rb
- spec/lib/translation/content_splitter_spec.rb
In https://github.com/discourse/discourse-translator/pull/249 we introduced splitting content (`post.raw`) prior to sending to translation as we were using a sync api. 
Now that we're streaming thanks to https://github.com/discourse/discourse-ai/pull/1424, we'll chunk based on the `LlmModel.max_output_tokens`.
> DEV: Split content based on llmmodel's max_output_tokens

- lib/personas/tool_runner.rb
- lib/personas/tools/custom.rb
- spec/models/ai_tool_spec.rb
- Add support for `chain.streamCustomRaw(test)` that can be used to stream text from a JS tool direct to composer
- Add support for llm params in `llm.generate` which unlocks stuff like structured outputs
- Add discourse.createStagedUser, discourse.createTopic  and discourse.createPost - for content creation
> FEATURE: improve custom tool infra

- admin/assets/javascripts/discourse/routes/admin-plugins-show-discourse-ai-features-edit.js
- app/controllers/discourse_ai/admin/ai_features_controller.rb
- assets/javascripts/discourse/components/ai-features-list.gjs
- assets/stylesheets/common/ai-features.scss
- config/locales/client.en.yml
- config/settings.yml
- lib/configuration/feature.rb
- lib/configuration/module.rb
- spec/configuration/feature_spec.rb
- spec/requests/admin/ai_features_controller_spec.rb
- spec/system/admin_ai_features_spec.rb
- allows features to have multiple llms and multiple personas
- sorts module list
- adds Bot as a first class module
- fixes issue where search module was always configured
- some tests
> FEATURE: Display bot in feature list

- lib/completions/llm.rb
- spec/lib/completions/endpoints/gemini_spec.rb
- spec/system/ai_helper/ai_composer_helper_spec.rb
Previously we did not validate the hash passed in to structured
outputs which could either be string based or symbol base
Specifically this broke structured outputs for Gemini in some
specific cases.
> FIX: normalize keys in structured output

- assets/javascripts/discourse/components/ai-features-list.gjs
- config/locales/client.en.yml
- lib/configuration/feature.rb
- lib/configuration/module.rb
- spec/requests/admin/ai_features_controller_spec.rb
- spec/system/admin_ai_features_spec.rb
> FEATURE: Display spam module on features list.

- assets/javascripts/discourse/components/ai-features-list.gjs
- assets/javascripts/discourse/components/ai-features.gjs
- assets/stylesheets/common/ai-features.scss
- config/locales/client.en.yml
- spec/system/page_objects/pages/admin_ai_features.rb
This makes the features list filterable and searchable, and does some light restyling on the feature boxes (including fixing some overflow issues)
Before:
After:
> UX: add filter to features page, update styles

- lib/embeddings/semantic_related.rb
- spec/lib/modules/embeddings/semantic_related_spec.rb
- spec/lib/modules/embeddings/semantic_topic_query_spec.rb
When an invalid model is set for embeddings, topics do not load even if embeddings is disabled.
Error:
> ## RuntimeError in TopicsController#show
> 
> Invalid embeddings selected model
This PR checks for valid settings before attempting to load related topics.
> FIX: Return no topics when embeddings is disabled

- assets/javascripts/discourse/components/ai-features-list.gjs
replacing the old deprecated `sortBy` with the newer vanilla JS `toSorted` — also learned that `localeCompare` is handy for comparisons like this
> DEV: replace sortBy with toSorted

- config/locales/client.en.yml
Introducing a typo isn't the right way to bypass the check that blocks the term "private messages".
Nice try, though ;)
I changed it to "personal messages".
> UX: Fix typo in bot.description text

- app/controllers/discourse_ai/ai_helper/assistant_controller.rb
- app/jobs/regular/stream_composer_helper.rb
- app/jobs/regular/stream_post_helper.rb
- assets/javascripts/discourse/components/ai-post-helper-menu.gjs
- assets/javascripts/discourse/components/modal/diff-modal.gjs
- lib/ai_helper/entry_point.rb
- spec/jobs/regular/stream_composer_helper_spec.rb
- spec/jobs/regular/stream_post_helper_spec.rb
- spec/requests/ai_helper/assistant_controller_spec.rb
- test/javascripts/acceptance/post-helper-menu-test.js
Previous to this change we reused channels for proofreading progress and
ai helper progress
The new changeset ensures each POST to stream progress gets a dedicated
message bus channel
This fixes a class of issues where the wrong information could be displayed
to end users on subsequent proofreading or helper calls
> FIX: cross talk when in ai helper

- lib/personas/locale_detector.rb
- lib/personas/post_raw_translator.rb
- lib/translation/language_detector.rb
- lib/translation/post_detection_text.rb
- lib/translation/post_locale_detector.rb
- lib/translation/topic_locale_detector.rb
- spec/lib/translation/post_detection_text_spec.rb
- spec/lib/translation/post_locale_detector_spec.rb
- spec/lib/translation/topic_locale_detector_spec.rb
A more deterministic way of making sure the LLM detects the correct language (instead of relying on prompt to LLM to ignore it) is to take the cooked and remove unwanted elements.
In this PR 
- we remove quotes, image captions, etc. and only take the remaining text, falling back to the unadulterated cooked
- and update prompts related to detection and translation
/152465/12
> FIX: Ignore captions and quotes when detecting locale and update prompts

- assets/javascripts/discourse/components/ai-llms-list-editor.gjs
- config/locales/client.en.yml
The key is `persona`, not `name`.
Before:
After the fix:
> FIX: correctly translate automation name

- app/models/llm_model.rb
- config/eval-llms.yml
- config/locales/client.en.yml
- evals/lib/eval.rb
- lib/ai_helper/assistant.rb
- lib/completions/endpoints/base.rb
- lib/completions/endpoints/gemini.rb
- lib/completions/json_streaming_parser.rb
- lib/completions/structured_output.rb
- lib/configuration/feature.rb
- lib/personas/translator.rb
- lib/utils/best_effort_json_parser.rb
- spec/lib/completions/endpoints/open_ai_spec.rb
- spec/lib/completions/structured_output_spec.rb
- spec/lib/utils/best_effort_json_parser_spec.rb
- If JSON is broken for structured output then lean on a more forgiving parser
- Gemini 2.5 flash does not support temp, support opting out
- Evals for assistant were broken, fix interface
- Add some missing LLMs
- Translator was not mapped correctly to the feature - fix that
- Don't mix XML in prompt for translator
> FIX: make AI helper more robust

- lib/translation/category_localizer.rb
- spec/lib/translation/category_localizer_spec.rb
Category descriptions [don't have limits](https://github.com/discourse/discourse/blob/5200bff76574fd52c01216a746d071dfe7246945/app/models/category.rb#L1346), but [their excerpts do](https://github.com/discourse/discourse/blob/5200bff76574fd52c01216a746d071dfe7246945/app/models/category.rb#L657). Localize them instead as they're the ones shown in category boxes
> FIX: Localize description excerpts as they have limits

- app/jobs/scheduled/categories_locale_detection_backfill.rb
- app/jobs/scheduled/posts_locale_detection_backfill.rb
- app/jobs/scheduled/topics_locale_detection_backfill.rb
Logs don't show backtrace, so this adds it.
> DEV: Add backtrace to logs

- app/jobs/regular/detect_translate_post.rb
- app/jobs/regular/detect_translate_topic.rb
- app/jobs/regular/localize_categories.rb
- app/jobs/regular/localize_posts.rb
- app/jobs/regular/localize_topics.rb
- app/jobs/scheduled/categories_locale_detection_backfill.rb
- app/jobs/scheduled/category_localization_backfill.rb
- app/jobs/scheduled/post_localization_backfill.rb
- app/jobs/scheduled/posts_locale_detection_backfill.rb
- app/jobs/scheduled/topic_localization_backfill.rb
- app/jobs/scheduled/topics_locale_detection_backfill.rb
- config/locales/server.en.yml
- lib/translation.rb
- lib/translation/entry_point.rb
- lib/translation/locale_normalizer.rb
- spec/jobs/regular/detect_translate_post_spec.rb
- spec/jobs/regular/detect_translate_topic_spec.rb
- spec/jobs/regular/localize_categories_spec.rb
- spec/jobs/regular/localize_posts_spec.rb
- spec/jobs/regular/localize_topics_spec.rb
- spec/jobs/scheduled/categories_locale_detection_backfill_spec.rb
- spec/jobs/scheduled/posts_locale_detection_backfill_spec.rb
- spec/jobs/scheduled/topics_locale_detection_backfill_spec.rb
- spec/lib/translation/entry_point_spec.rb
- spec/lib/translation/locale_normalizer_spec.rb
This PR
- normalizes locales like en_GB and variants to en. With this, the feature will not translate en_GB posts to en (or similarly pt_BR to pt_PT)
- consolidates whether the feature is enabled in `DiscourseAi::Translation.enabled?`
- similarly for backfill in  `DiscourseAi::Translation.backfill_enabled?`
- turns off backfill if `ai_translation_backfill_max_age_days` is 0 to keep true to what it says. Set it to a high number to backfill everything
> DEV: Normalize locales that are similar (e.g. en and en_GB) so they do not get translated

- assets/javascripts/discourse/components/ai-bot-conversations.gjs
- assets/javascripts/discourse/services/ai-bot-conversations-hidden-submit.js
- config/locales/client.en.yml
- spec/system/ai_bot/homepage_spec.rb
Try fix a flaky spec in /ai_bot/homepage_spec.rb by using ember
data rather than inspecting the DOM directly to see if there
are any in-progress uploads.
Also add missing translation for in progress uploads warning,
and spec for this behaviour.
> DEV: Improve AI bot conversation submit upload handling

- assets/javascripts/discourse/components/ai-features-list.gjs
Need to make sure modules is always an array to use toSorted, the "all" filter was throwing an error otherwise
> FIX: prevent crash in "all" filter on features page

- lib/personas/locale_detector.rb
- lib/personas/post_raw_translator.rb
- lib/personas/short_text_translator.rb
- lib/personas/topic_title_translator.rb
- lib/translation/base_translator.rb
- lib/translation/language_detector.rb
Since translations only require a single key back, there is little point in using structured output. This PR also includes some prompt updates dealing with quotes, details, and code.
Related: https://github.com/discourse/discourse-ai/pull/1502
This does mean reverting https://github.com/discourse/discourse-translator/pull/257, but we can see how it goes.
> DEV: Switch translations out of structured output as it returns only a single value

- lib/translation/base_translator.rb
- spec/lib/translation/base_translator_spec.rb
We're seeing that some LLMs are using 65000+ tokens for raw text that is only 10-1000 characters long.
This PR adds a max_token to be passed to the LLM API for each translation based on the length of the text.
> FIX: Add a max token limit based on the text to be translated
